### ISSUE TITLE
Make prebuilt binaries available in releases?

### ISSUE THREAD

**Issue by nosferalatu** [wolfpld/tracy#10]
Would it be possible to add prebuilt binaries of the visualizer app? Making prebuilt binaries available would reduce the friction of the initial setup. It's easy to add the Tracy runtime to an app, but a little harder to build the visualizer (fiddling with vcpkg, and requires VS2019 which isn't necessarily available in a commercial shop).

For example the Optick profiler:
https://github.com/bombomby/optick/releases
has its visualizer app prebuilt and available for download, which is all that's needed most of the time.

**Comment by wolfpld** [comment]
0.6.3 binary added to the release. Providing nightly builds would require additional CI work.

**Comment by nosferalatu** [comment]
Awesome. Thanks!

**Comment by wolfpld** [comment]
Win32 binaries and manual are now available as CI build artifacts.

**Comment by nosferalatu** [comment]
Thanks!

**Comment by kvark** [comment]
@wolfpld would it be possible to also generate macOS and Linux binaries for the releases?

**Comment by wolfpld** [comment]
No, unless someone is willing to automate the CI process.
