### ISSUE TITLE
The API does not accurately reflect the limits of data

### ISSUE THREAD

**Issue by nagisa** [wolfpld/tracy#100]
Functions like `Profiler::Message` have asserts like these:

https://github.com/wolfpld/tracy/blob/b5f76f2cea1dbf411bdd6f90b5e2aa3286622a88/client/TracyProfiler.hpp#L282

even though the APIs that allow supplying the message length are all `size_t`. Looking at the function signatures it would be reasonable to assume that tracy will support support strings longer than 64kB. Instead they will encounter a crash they do not expect (this can especially happen if they are printing dynamically formatted data).

The manual does not mention this limitation either as far as I can tell. Not entirely sure if this behaviour wants a change or just a plain mention in the manual.

**Comment by wolfpld** [comment]
Using `size_t` as an input type has its benefits, e.g. being able to use results from `strlen` without a downcast. The message size is indeed limited to 64 KB and that probably should be mentioned in the manual. I don't see a practical benefit from supporting longer messages, which are supposed to be human readable and presentable in the UI.

**Comment by wolfpld** [comment]
Documented in b90d1cca.

**Comment by nagisa** [comment]
:+1: Thanks!
