### ISSUE TITLE
Tracy overrides application defined crash handler

### ISSUE THREAD

**Issue by hexc4t** [wolfpld/tracy#102]
The simplest solution is to not execute Tracy's crash handler if the profiler is connected.
Adding 
```cpp
     if ( !GetProfiler().IsConnected() )
     {
         return EXCEPTION_CONTINUE_SEARCH;
     }
```
at the beginning of the CrashFilter function solves the problem.

**Comment by wolfpld** [comment]
Applied in f3eabc28.
