### ISSUE TITLE
Performance issue when limiting statistics time window

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#104]
When using the new feature of setting limits to restrict the statistics window to a time zone, tracy struggles with performance. On my machine (ryzen 3700x, gtx 1070), I see a drop from constant 60 fps (probably vsynced) to 20 fps, when limiting the time and having the statistics-window open.

Repro: open [this](https://1drv.ms/u/s!AsdZfH5hzKtp3UJRhpqcv3O7tp-g?e=oD3zdu) trace in tracy 0.7.1, open the statistics window, and restrict the evaluated zone to frame 1,114. While the statistics window is open, fps should drop considerably.

**Comment by wolfpld** [comment]
Yes, this is currently slow. Proper caching will be implemented in the future.

**Comment by wolfpld** [comment]
Fixed in a48d5408.
