### ISSUE TITLE
Hide allocations from Tracy events while Memory profiling

### ISSUE THREAD

**Issue by Dahrkael** [wolfpld/tracy#107]
I haven't seen anything in the PDF.
I'm trying to see my program allocations which are not that many, but the list is full of allocations made by the ZoneScoped macros that make very hard to see whats really going on.

Is it possible to hide those without disabling them? (So i'd have to profile frames OR memory but not both)

**Comment by wolfpld** [comment]
What exactly are you seeing reported from Tracy side? Tracy uses its own memory allocator, which is not tracked by memory usage tracing.

**Comment by Dahrkael** [comment]
You sir are indeed correct and I misunderstood the profiler data.
It is telling me in which zone the allocation happened but not which line exactly. I thought the highlighted line when clicking the zone then Source was the culprit. Sorry for the trouble.

While we are at it though, is there a way of finegraining which line is actually doing the allocation? through callstack sampling or something?

Thanks

**Comment by wolfpld** [comment]
Yes, use callstack sampling. The precise place in which memory allocation is tracked can be a couple function calls away from the memory allocation in user code.

**Comment by Dahrkael** [comment]
all clear now, thank you!
