### ISSUE TITLE
Hang in Tracy.exe when profiled app run with admin privileges

### ISSUE THREAD

**Issue by Niadb** [wolfpld/tracy#109]
I spoke to wolfpld in discord about this earlier, just writing down the details here.

This is on Windows 10
Everything compiled with VS2019 latest

_Repro for me:_
1. Run server/GUI tracy.exe, and tell it to wait for connection
2. Run application to be profiled with admin privileges(app use 30+threads on 12c/24t CPU)
3. Tracy hangs within 2-3 seconds & uses 5-10GB of memory

If the app is run without admin privileges, no hang occurs & it only uses 100mb in the same time frame.
If I use the capture tool to record the trace, and then open in the GUI, it does not hang nor use so much memory

_Other info:_

In **DrawZoneFramesHeader**:

it was observed that this line

`  const auto timespan = m_vd.zvEnd - m_vd.zvStart;`

zvEnd was less than zvStart, producing a negative timespan, this leads to a negative dx value
```

 while( x < w )
...
  x += dx;

```
Resulting in a loop that never terminates.
The high memory usage is likely just a side effect of this loop, as it is pushing lines into IMGUI endlessly.

I might look into this with more detail sometime in the next week

**Comment by wolfpld** [comment]
0.10 reimplemented timeline drawing. This bug is probably fixed.
