### ISSUE TITLE
False dependency in system tracing (was: How to enable call stack sampling under Android?)

### ISSUE THREAD

**Issue by vinjn** [wolfpld/tracy#121]
I've enabled this feature in Windows and would love to have this enabled in Android.
My device is already rooted.

**Comment by wolfpld** [comment]
Have you followed the manual wrt to required setup?

```sh
setenforce 0
mount -o remount,hidepid=0 /proc
echo 0 > /proc/sys/kernel/perf_event_paranoid
```

**Comment by vinjn** [comment]
I've succeeded at step 1 and 3, but step 2 failed with error message like  `mount: /proc not in /proc/mounts`.
Is step 2 must have for call stack sampling? If yes, I will find a solution.

**Comment by wolfpld** [comment]
Skipping step 2 shouldn't be a problem.

To find the reason why this is failing, you should look at what's happening in the tracing setup code at `client/TracySysTrace.cpp:871`. There are unfortunately some false dependencies here, i.e. sampling is only considered for usage if context switch tracing is successfully setup.

Note that certain kernel features may or may not be enabled on your device, or in the kernel headers you're using.

**Comment by vinjn** [comment]
Thanks for the tips, I will setup my debugger and have some fun today.
Tracy is awesome, thanks for your work.

**Comment by vinjn** [comment]
Sampling is running after I workarounded the false dependencies (move `SetupSampling(samplingPeriod);` to top) . But the function symbol resolving seems not working as expected.
Any hints?
![image](https://user-images.githubusercontent.com/558657/98758143-05782e80-2409-11eb-8bcf-9bf5d1481cef.png)

**Comment by wolfpld** [comment]
You need to follow instructions in 3.10.1 Debugging symbols.

> On gcc or clang remember to specify the debugging information -g parameter during compilation and
> do not add the strip symbols -s parameter. Additionally, omitting frame pointers will severely reduce
> the quality of stack traces, which can be fixed by adding the -fno-omit-frame-pointer parameter.
> Link the executable with an additional option -rdynamic (or --export-dynamic , if you are passing
> parameters directly to the linker).

**Comment by vinjn** [comment]
Thanks wolfpld, we can close this ticket.

**Comment by wolfpld** [comment]
I'll keep this open, as sampling / context switch capture shouldn't depend on each other.

**Comment by wolfpld** [comment]
> I'll keep this open, as sampling / context switch capture shouldn't depend on each other.

Due to development of new features this is no longer the case. Context switch data is now needed to properly determine where the sample data comes from.
