### ISSUE TITLE
Invalid DockId in imgui.ini causes window to never appear

### ISSUE THREAD

**Issue by annacrombie** [wolfpld/tracy#122]
Perhaps this is an upstream issue, but I am not very familiar with Dear ImGUI and this caused me some frustration, so maybe it can help others.

Recently I found the "Zone info" window would never appear, clicking on zones in the timeline selected them, but that is all.  Through some printf debugging, I verified that `DrawZoneInfoWindow` was being called.  Next I tried running `XDG_CONFIG_HOME=/tmp ./Tracy-debug`, and voilà, clicking on a zone opened the Zone info window.  After some trial and error, I narrowed the problem down to this section in my `imgui.ini`:

```ini
[Window][Zone info]
Size=1068,289
Collapsed=0
DockId=0x00000003,0
```

removing the `DockId` line fixes the problem.  

I guess the dock became invalid but ImGUI was still trying to dock to it anyway?

**Comment by wolfpld** [comment]
The way docking is setup in Tracy hasn't changed for over a year and a half. As a consequence, this shouldn't be a case of the window being docked somewhere, and this "somewhere" being internally changed in the meantime, causing the trouble.

This rather looks like some edge case in ImGui and I'd suggest reporting the issue there.

**Comment by annacrombie** [comment]
I assumed as much, but decided to ask here first just in case.  Thanks
