### ISSUE TITLE
Potentially unitialized variable warning on g++10

### ISSUE THREAD

**Issue by seanmiddleditch** [wolfpld/tracy#126]
The `ScopedZone` macro (among probably others) triggers warnings on g++ 10 for a potentially uninitialized variable:

```
In file included from ../deps/tracy-src/Tracy.hpp:102,
                 from ../shell_app.cpp:56:
../deps/tracy-src/client/TracyScoped.hpp: In member function ‘void up::shell::ShellApp::_displayUI()’:
../deps/tracy-src/client/TracyScoped.hpp:102:9: error: ‘___tracy_scoped_zone.tracy::ScopedZone::m_connectionId’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  102 |         if( GetProfiler().ConnectionId() != m_connectionId ) return;
      |         ^~
```

Full build command (... some include paths trimmed), for reference of any options enabled:

`/usr/bin/g++-10  -DGLM_ENABLE_EXPERIMENTAL -DIMGUI_DEFINE_MATH_OPERATORS=1 -DTRACY_ENABLE=1 -DTRACY_IMPORTS=1 -DTRACY_NO_BROADCAST=1 -DTRACY_ON_DEMAND=1  -isystem /usr/include/SDL2 -O3 -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Werror -Wno-volatile -pthread -std=c++2a -MD -MT shell_app.cpp.o -MF shell_app.cpp.o.d -o shell_app.cpp.o -c ../shell_app.cpp`

**Comment by wolfpld** [comment]
The compiler seems to be pretty crappy at doing static analysis here. The only way for `m_connectionId` to be uninitialized is for `m_active` to be `false`, i.e. in all constructors:

```c++
        if( !m_active ) return;
        m_connectionId = GetProfiler().ConnectionId();
```

The code you're getting your warning is:

```c++
        if( !m_active ) return;
        if( GetProfiler().ConnectionId() != m_connectionId ) return;
```

To make things even worse for gcc, `m_active` is declared as a `const` class member, so its value cannot change in the meantime. As you can see, everything is behaving properly here and there are no uninitialized variable references.

I would suggest opening an issue against gcc.
