### ISSUE TITLE
Bug in TracySysTrace parsing

### ISSUE THREAD

**Issue by kaiscode** [wolfpld/tracy#127]
If you have a process running that starts with `pid`, an assert is triggered in the ReadNumber call. For example on my system, I unfortunately had a process running called `pid-file-watche`. Because of this, it looks like I'd have a line like

`sched_wakeup: comm=pid-file-watche pid=1234 .....`

Which causes the memcmp to return early. 

Relevant code in Tracy:
```
    else if( memcmp( line, "sched_wakeup", 12 ) == 0 )
    {
        line += 14;

        while( memcmp( line, "pid", 3 ) != 0 ) line++;
        line += 4;

        const auto pid = ReadNumber( line );

        TracyLfqPrepare( QueueType::ThreadWakeup );
        MemWrite( &item->threadWakeup.time, time );
        MemWrite( &item->threadWakeup.thread, pid );
        TracyLfqCommit;
    }
```
Maybe a quick hack that would reduce the frequency of the issue is to memcmp for `pid=` instead, but I think `=` may still technically be a valid character for a process name in linux.

Will add more details later - let me know if this is clear or not.

**Comment by wolfpld** [comment]
Fixed in 119e357d.

> Maybe a quick hack that would reduce the frequency of the issue is to memcmp for pid= instead, but I think = may still technically be a valid character for a process name in linux.

You can also name your process "pid=1 pid=2", for extra fun. Linux has *horribly bad* interfaces.
