### ISSUE TITLE
Offer per-plot option to render staircases instead of straight line segments 

### ISSUE THREAD

**Issue by dominikh** [wolfpld/tracy#131]
Currently, all plots are line plots, connecting data points with straight lines. It would be nice to have staircase plots as an option. Unlike line plots, staircases don't suggest a gradual change where there is none. For example, memory allocations and frees are instantaneous changes in memory usage. A huge allocation at point X and a huge free at point X+100s doesn't mean that we've freed X/100 of memory per second. As such, staircase plots are a more accurate representation of overall memory usage at any point in time.

Ideally, this would be a per-plot option and not global. Line plots make sense for sampled data like system CPU usage, but not for precisely captured data like memory allocations.

**Comment by wolfpld** [comment]
Implemented in c9249810.

![Clipboard01](https://user-images.githubusercontent.com/600573/180647566-381e2bb4-191c-46bb-97f9-75bb3b86106f.png)
