### ISSUE TITLE
Constant freezing/crashing

### ISSUE THREAD

**Issue by CZDanol** [wolfpld/tracy#133]
Hello,
unfortunately Tracy is constantly freezing/crashing with my application. When looking in task manager, it starts hoarding up the ram (up the all available RAM - I have 32 GB).

It also happens when I'm scrolling through the attached capture.
[tt.zip](https://github.com/wolfpld/tracy/files/5583519/tt.zip)

**Comment by wolfpld** [comment]
One of your plots contains non-finite values:

![obraz](https://user-images.githubusercontent.com/600573/100019473-65de7700-2dde-11eb-8ffb-bcfb250993bb.png)

Please check if de69fc98 fixes this for you. This only fixes new captures (by discarding invalid values). To open already existing traces rebuild the profiler with "Floating Point Model" set to "Precise".
