### ISSUE TITLE
Tracy 0.7.4 fails to launch - MSVCP140_ATOMIC_WAIT.dll not found

### ISSUE THREAD

**Issue by aclysma** [wolfpld/tracy#135]
Full error message: "The code execution cannot proceed because MSVCP140_ATOMIC_WAIT.dll was not found. Reinstalling the program may fix this problem."

0.7.3 launches successfully. I tried installing the VS 2015 redistributable but it fails, indicating that it was already installed. This is on windows 10 1909

**Comment by Querijn** [comment]
MSVCP140 is the visual studio 2019 redist. You can fix this issue by installing the correct redist for your platform: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by aclysma** [comment]
Thanks, that was it. Usually "14" means VS 2015.

**Comment by wolfpld** [comment]
MS is now only providing combined VS 2015+2017+2019 redist package. How were you able to obtain redist limited just to VS 2015?

**Comment by Querijn** [comment]
It can be retrieved from this URL; one of Google's top results for me: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by aclysma** [comment]
It was the first result for me when searching "visual studio 2015 redistributable". I think offering a combined redist is new and it's pretty confusing that a VS 2019 dependency has a "14" in the file name. :)

**Comment by wolfpld** [comment]
I see. Will add a paragraph to the manual to make it less confusing.

**Comment by Querijn** [comment]
I've modified my previous comment, you are correct, it is vs2015.. But I don't understand how they're split up now?

**Comment by aclysma** [comment]
Is it possible the exe was built with a newer version of VS 2015 than the redist I found that was published on 7/10/2015?

**Comment by wolfpld** [comment]
The VC 2019 libraries are ABI-compatible back to VC 2015 and share the name with the older ones. Of course, newer additions are not available if you only have VC 2015/2017 (or older VC 2019) redist installed.

The executable is created using the ~latest MSVC 2019.
