### ISSUE TITLE
Being able to name GpuZones

### ISSUE THREAD

**Issue by GenuineAster** [wolfpld/tracy#140]
We are running a RenderGraph-like Vulkan architecture where all of our command buffers are created from the same C++ source location, and since the source location is `constexpr` in Tracy, and that contains the GpuZone name and we refer to it by address, there is no way for us to use custom names for our GpuZones.

It would be great if Tracy could support this feature, as it does for `ScopedZone`!

I have been messing around with TracyVulkan to support our use case, as we don't re-record command buffers every frame and we don't submit every command buffer every frame, and I have a working implementation! It's just a bit useless because nothing has names. We'd be open to implementing named zones ourselves with some guidance!

Being able to name contexts (compute, graphics..) would be awesome as well :)

**Comment by GenuineAster** [comment]
We got around this by allocating our own `tracy::SourceLocationData` objects for each shader and now it works pretty fine! We had to add a macro for `TracyVkZone` that accepts a `uint64_t` source location.

**Comment by wolfpld** [comment]
Implemented in 538352d as transient zones (which allocate a separate source location for each zone).

**Comment by wolfpld** [comment]
Note that contexts can be named since 468babe56ad692ea65997039a902cea16f92d647.
