### ISSUE TITLE
Exporting to Chrome Trace

### ISSUE THREAD

**Issue by avoroshilov** [wolfpld/tracy#143]
Hello!
It seems somewhat useful to be able to export to Chrome Trace JSON, for example in cases where existing automation exists that collects/analyzes profiling data using the existing Chrome Trace format, with no or minimal changes to the automation pipeline.

There is a CSV exporter from what I see, and having CT export option would be a nice addition.

I wonder if that is in plans or if not, what are general thoughts on this subject - are there any estimated difficulties?

**Comment by wolfpld** [comment]
There are no plans to implement exporters to other formats. Doing so shouldn't be hard at all - it's a matter of writing data collected by `Worker` in an appropriate format.

Do consider that Tracy traces are:
- structured in an optimal way (zone relations are derived from their order, and not explicitly stated),
- delta-encoded where it makes sense,
- using deduplication and referencing to further reduce data size,
- internally compressed,
- etc.

To sum it up, a considerate effort was put to make them as small as possible. For example, a trace with billion zones can take 350 MB on disk.

In comparison, chrome tracing json files are horribly overblown, by being textual, by writing numbers in a human-readable format, by repeating the same text strings over and over again, and so on, e.g.:

https://github.com/jlfwong/speedscope/blob/6a979bb568f548dd347dba5b18e69e4401a2dda3/sample/profiles/Chrome/70/worker.json#L14-L16

GitHub helpfully shows that this file is 584 KB and contains 2613 lines (events of some kind). Also, "will happily display multi-megabyte profiles without crashing your browser" is a very funny quote about chrome tracing and what can be expected from it :)

**Comment by avoroshilov** [comment]
Thanks for the info!

Indeed, I saw comparisons of similar traces captured by Tracy and Chrome Trace backends in the past, and Tracy was just wonderful in this regard!

Closing the issue. If I'll ever get to implementing the exporter I will provide a PR then.

**Comment by NicTanghe** [comment]
Im zombieing this here becouse the bloated extra text whould help llm`s reading the data in all text.
and since it`s just for export a larger file seems like a worthwile trade.
