### ISSUE TITLE
TracyClient.obj : error LNK2001: unresolved external symbol __imp__SymAddrIncludeInlineTrace@12

### ISSUE THREAD

**Issue by imanokZ** [wolfpld/tracy#144]
My project is a C++ game demo based on GLFW
IDE is visual studio 2019
My step:
add TracyClient.cpp to project( 
add TRACY_ENABLE to project( Project property -> C/C++ -> Preprocessor ),
compile the project in RELEASE mode..

I got following errors:

1>TracyClient.obj : error LNK2001: unresolved external symbol __imp__SymAddrIncludeInlineTrace@12
1>TracyClient.obj : error LNK2001: unresolved external symbol __imp__SymQueryInlineTrace@40
1>TracyClient.obj : error LNK2001: unresolved external symbol __imp__SymGetLineFromInlineContext@32
1>TracyClient.obj : error LNK2001: unresolved external symbol __imp__SymFromInlineContext@24

Help me plz...

**Comment by imanokZ** [comment]
solved， close issue.

**Comment by ezhikus** [comment]
But how did you solve it?

**Comment by Galathea13** [comment]
Clean the solution and recompile. That should do it.
