### ISSUE TITLE
0.7.4 fails to load with "MSVCP140_ATOMIC_WAIT.dll was not found" error

### ISSUE THREAD

**Issue by avoroshilov** [wolfpld/tracy#145]
Just tried running Tracy 0.7.4 and got this error message regarding the missing DLL.
0.7.3 runs fine.
Never dealt with this particular DLL to be honest, so a bit puzzled as to what to do. This seems somehow related to UWP maybe? Were there any drastic changes in the build process/orchestration lately?

I've found an instance of that DLL in `Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0`, copied it over to the Tracy bin folder, and 0.7.4 launched - but that doesn't seem like normal operation mode.
https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge this is what Microsoft has to say about that particular package.

**Comment by wolfpld** [comment]
You need to have the latest redist package: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by avoroshilov** [comment]
Ah, thanks. I tried some redists but they didn't work, this one worked.
