### ISSUE TITLE
Tracy 0.7.4 doesn't capture Vsync-Frames or Profiling-Samples in Program with elevated permissions on Windows 10 64-bit

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#150]
I upgraded to Tracy 0.7.4 today, hoping this would resolve the issue, but it doesn't:

When I start my profiled application (written in D) from an Administrator cmd-shell on Windows 10 64-Bit, the Trace will miss some features that should be present. I do get information about CPU-usage, Thread-Scheduling (like this:)
![grafik](https://user-images.githubusercontent.com/10748498/102690671-50a30f80-4207-11eb-899e-c32b36d33b1c.png)
, but there is only the single Frame-Set I instrumented myself, no Vsync Frame-set, and no profiling samples were taken (in the statistics window, I can only chose between Instrumentation and Symbols, not Samples). I don't know if there are more things missing, since I mainly care about vsync and sampling right now.

I don't have TRACY_NO_VSYNC_CAPTURE or TRACY_NO_SAMPLING defined, my only defines are TRACY_ENABLE (of course), TRACY_ON_DEMAND and TRACY_DELAYED_INIT.

I have looked through the manual, but couldn't find any other mentions of conditions that need to hold for these features to work. Since I do get CPU information, which wouldn't be there without admin privilege, elevated rights don't seem to be the problem.

I tried this with both the Tracy.exe from the 0.7.4 Release on Github and a self-compiled version using Visual Studio 2019.

**Comment by wolfpld** [comment]
Can you check if the missing features are present if you omit TRACY_ON_DEMAND and/or TRACY_DELAYED_INIT?

**Comment by simonvanbernem** [comment]
Turning them of individually or together doesn't change anything unfortunately.

**Comment by wolfpld** [comment]
Can you step through `SysTraceStart()` (and `SetupVsync()`) to see what's happening there?

**Comment by simonvanbernem** [comment]
Since I don't exactly know what you are looking for, I just tracked the Windows-API calls and sanity-checked some values.

- 343: isOs64Bit is true
- 349: LookupPrivilegeValue returns non-zero, Privileges[0].Luid has LowPart=11, HighPart=0
- 363: TraceSetInformation retuns ERROR_SUCCESS
- 373 and 376: we set the flags.
- 378: flags is 0x01000812 (EVENT_TRACE_FLAG_CSWITCH | EVENT_TRACE_FLAG_DISPATCHER | EVENT_TRACE_FLAG_THREAD | EVENT_TRACE_FLAG_PROFILE)
- We don't use QPC (385: s_prop->Wnode.ClientContext = 3)
- 390: MaxBuffers is 96, MinBuffers is 64 (We have 16 threads)
- 392: KERNEL_LOGGER_NAME is "NT Kernel Logger"
- 397: ControlTrace returns ERROR_WMI_INSTANCE_NOT_FOUND
- 408: StartTrace returns ERROR_SUCCESS
- 420: TraceSetInformation returns ERROR_SUCCESS
- 439: OpenTrace returns 65

and then we go into SetupVsync:

- 251: #if _WIN32_WINNT >= _WIN32_WINNT_WINBLUE is true
- 269: ControlTraceA returns ERROR_SUCCESS
- 279: StartTraceA returns ERROR_SUCCESS. s_propVsync->Wnode.Guid contains what looks like a proper GUID.
- 304: EnableTraceEx2 returns ERROR_SUCCESS. This value isn't checked though (is this intended?).
- 314: OpenTraceA returns 66

 And then we spin up the thread and are done with SetupVsync. SysTraceStart returns true. Looks all fine to me.

**Comment by wolfpld** [comment]
Everything is looking correct. At this point both `EventRecordCallbackVsync()` and `EventRecordCallback()` should be firing. The second one obviously is, as you're getting the context switch data (the 0x3d6fa8d1 part of the switch).

Can you check what's happening in these callbacks? The vsync callback should be inspected in its entirety and the non-vsync callback in the 0xdef2fe46 part, especially the PID matching (the high bit check is to filter out kernel frames).

**Comment by simonvanbernem** [comment]
EventRecordCallback() only ever goes into case 0x3d6fa8d1. case 0xdef2fe46 is never hit. EventRecordCallbackVsync() is not called.

**Comment by wolfpld** [comment]
Hm... Both these cases depend on providing guids (PerfInfoGuid and DxgKrnlGuid). Can you check if the guid is properly set in the appropriate struct, e.g.:

![obraz](https://user-images.githubusercontent.com/600573/102790962-92b68780-43a6-11eb-9cbd-3d0a3d805062.png)

**Comment by simonvanbernem** [comment]
stackId.EventGuid is all zeros for me. PerfInfoGuid and DxgKrnlGuid are also all zeros.

**Comment by wolfpld** [comment]
Does dab68b2f fix the problem?

**Comment by simonvanbernem** [comment]
**It does** 👍 Thank you very much for your help!

Oh, my, thats a lot of data  😄

**Comment by simonvanbernem** [comment]
I wouldn't have excepted that many threads in a single-threaded application :D.

**Comment by wolfpld** [comment]
Nothing is really single threaded these days ;)

**Comment by simonvanbernem** [comment]
I expected that, but I wasn't ready for 59 threads. Thats A LOT.
