### ISSUE TITLE
Tracy 0.7.4 Release Binary crashing without msvcp140_atomic_wait.dll

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#151]
I downloaded Tracy-0.7.4.7z from the Release-Section of github. When I try to execute the contained Tracy.exe I get a windows system error complaining about a missing MSVCP140_ATOMIC_WAIT.dll. This can be fixed by copying the dll in question into the folder of the executable (in my case I had a copy in C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe\msvcp140_atomic_wait.dll).

Is this supposed to be necessary? Its a bit alienating to download an executable only to have to find a dll on your system _somewhere_ and copy it into the folder. When I compile the profiler myself, the dll is not needed.

I'm on Windows 10 64-bit.

**Comment by wolfpld** [comment]
You need to install the latest combined MSVC redist, available at https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by wolfpld** [comment]
VC redist is now included in the release files for people who don't have it.
