### ISSUE TITLE
Plots: Improve display of min/max values

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#152]
When I scroll around the timeline and have plots visible, tracy updates the min and max of the displayed range in a smooth manner: I guess there is some polynomial or exponentional blend function at work. This leads to some strange behavior:

- Values take a long time to settle: When I stop scrolling around, the values change for another 2 seconds before settling on a fixed value. Thats a long time, if I just want to have a quick glance at it. Additionally: The changing values also have a different amount of significant digits in base 10, which means the "visible data points:" text right to the y-range is jumping around, because the y-range value is changing length of text all the time. I would prefer to have a very short smoothing (<0.3s) or none at all.
- Once the values have settled, they still don't show the right number. They are slightly off. So instead 11,131,120 it will settle on 11,131,120.000000005. We never get to the real number, unless:
- We settle on the actual value on focus loss. When I click into another window tracy displays the correct value, without that tiny error. That even happens if the value already settled on the slightly-off value. Losing focus just fixes everything.
- Having fractional min and max for plots that only contain integers is strange anyway. I currently plot how big my temp allocator is (I cant use allocation/dealloc, since there are no free() calls for the temp allocator), and since this is just a (large) byte-count, it becomes really annoying trying to see if this is a dot or a comma on the value. It would be nice if there was a way to tell tracy that this plot is integers (maybe just adding another plot function for integers?) so it never displays fractional values in the first place.

**Comment by simonvanbernem** [comment]
One more thing: 

- The min and max values are hard to read anyway, because there may be a line of the plot underneath (like here) which is of the same color: ![grafik](https://user-images.githubusercontent.com/10748498/102884381-d1ede280-4451-11eb-82fe-305637bfc4cb.png) It would be nice to have a high-contrast background (black?) behind the font but over the graph, or some prominent outlining to improve readibility.

**Comment by wolfpld** [comment]
> When I scroll around the timeline and have plots visible, tracy updates the min and max of the displayed range in a smooth manner

This has been fixed in 0.8.2.

**Comment by wolfpld** [comment]
> It would be nice to have a high-contrast background (black?) behind the font but over the graph, or some prominent outlining to improve readibility.

In 6748756fa this looks as follows:

![obraz](https://user-images.githubusercontent.com/600573/177036706-6d49d4ba-b948-470c-8a6c-33aa7b91c86d.png)
