### ISSUE TITLE
Crash v0.7.4 on startup on ARM64 Raspberry Pi 400 

### ISSUE THREAD

**Issue by grrussel** [wolfpld/tracy#155]
```
Error 65543: GLX: Failed to create context: GLXBadFBConfig
terminate called without an active exception
Aborted (core dumped)

```

I suspect the issue is that the Pi can only provide OpenGL 2.1

Linux pi400-desktop 5.8.0-1010-raspi #13-Ubuntu SMP PREEMPT Wed Dec 9 17:14:07 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 4.2 (0xffffffff)
    Version: 20.2.1
    Accelerated: yes
    Video memory: 3740MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 4.2
OpenGL version string: 2.1 Mesa 20.2.1
OpenGL shading language version string: 1.20

**Comment by wolfpld** [comment]
Yes, Tracy expects OpenGL core profile 3.2.

**Comment by grrussel** [comment]
OK! I expect its a significant amount of work to use a really old OpenGL version, so it may be enough to note the OpenGL version required in the (excellent + amusing) manual.

**Comment by wolfpld** [comment]
> I expect its a significant amount of work to use a really old OpenGL version

Not really. It should be fairly easy to (conditionally) switch to e.g. GLES 3.0. I don't see much sense in doing so, however, as the very limited 4 GB of RAM on rpi will severely limit the profiling capabilities.

**Comment by grrussel** [comment]
Ok, this was in fact trivial for me to fix

In main.cpp of the profiler,

```
    //glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    //glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    //glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

```
    ImGui_ImplOpenGL3_Init( "#version 100" );
```

and I have it working!
