### ISSUE TITLE
Can tracy profile GPU on Android ？

### ISSUE THREAD

**Issue by catdoc** [wolfpld/tracy#16]
HI, Can tracy profile GPU on Android ？

I've added TracyGpuContext and TracyGpuNamedZone at the code, but it doesn't work. 
After breakpoints, it is found that the code is executed, There was no error.
On the server profiler, it just shows OpenGL context 0 with empty GPU zones.

**Comment by wolfpld** [comment]
Yes, but getting good results is a bit of lottery. You need to have properly working gfx drivers, as Tracy is only reporting what it gets from the OpenGL queries.

The sad reality is that Android drivers only work reliably when common workflow paths are used. Stray a bit off and you're in trouble (e.g. https://issuetracker.google.com/issues/37000141). Receiving timestamps is a very niche use-case.

**Comment by catdoc** [comment]
I found that GPU can be captured occasionally, but not most of the time.
