### ISSUE TITLE
Tracy 0.7.4 can hang on shutdown on Linux as root

### ISSUE THREAD

**Issue by jkriegshauser** [wolfpld/tracy#160]
1. Create an application that calls `tracy::StartupProfiler()`, creates at least one profiler zone, waits a bit of time and then calls `tracy::ShutdownProfiler()`
2. Run the application as root on Linux (I was running on aarch64) so that systrace gets initialized

Expected: the application exits
Actual: the application hangs on shutdown

**Comment by wolfpld** [comment]
Fix already on master.
