### ISSUE TITLE
File name in viewer window title missing for chrome-imported traces

### ISSUE THREAD

**Issue by jkriegshauser** [wolfpld/tracy#163]
Currently when you open a saved trace (and you have multiple Tracy client windows open) it isn't possible to tell at a glance which file is open in which window.
![image](https://user-images.githubusercontent.com/1697375/104348586-c02eb680-54b6-11eb-8fa0-57e5bb5d9890.png)

This request is so that the filename could be displayed in the window title bar such as:
`Tracy Profiler 0.7.4 - saved_trace.tracy`

**Comment by wolfpld** [comment]
This has been a feature for a long time.

![obraz](https://user-images.githubusercontent.com/600573/104356968-e2532380-550c-11eb-833d-d49b378b9e14.png)

Are you importing chrome traces?

**Comment by jkriegshauser** [comment]
> Are you importing chrome traces?

Yes, this is from an imported Chrome trace

**Comment by wolfpld** [comment]
There's your problem. To resolve this you may extend the existing conversion utility to pass the name annotation to the profiler.
