### ISSUE TITLE
Why GPU and CPU time differ greatly in the same frame

### ISSUE THREAD

**Issue by catdoc** [wolfpld/tracy#17]
HI, Why GPU and CPU time differ greatly in the same frame on Android ?

Here is a screenshot of the profile,  "9:36.8" What do these numbers mean ?
![image](https://user-images.githubusercontent.com/4272019/81463547-1d77a880-916f-11ea-9513-11ad18f19428.png)

**Comment by wolfpld** [comment]
This is fundamentally the same issue as #16. You can either try to find a device that works as advertised, or try to bug your vendor about broken drivers and hope someone cares. You can see how well that goes in the issue I linked in the previous issue (the stencil problem still persists on new devices, 6 years later).
