### ISSUE TITLE
App fails on Android AVD when calling SetupHwTimer

### ISSUE THREAD

**Issue by SuperWangKai** [wolfpld/tracy#173]
In Android AVD `SetupHwTimer()` function fails which then causes application `exit(0)`
https://github.com/wolfpld/tracy/blob/6b276a1a64c84e6005aab207d42c30e960ffffa2/client/TracyProfiler.cpp#L241

The same app with Tracy runs well on physical Android devices.

I wonder if we can still have one target for both physical devices and AVDs? (Shall we need some fallback when HwTimer is not avaiable on an AVD?)

How can I define `TRACY_NO_INVARIANT_CHECK=1` environment variable for an AVD?

Thanks!

**Comment by SuperWangKai** [comment]
Or if there is some way to disable Tracy, we can turn it off as the other code path.

**Comment by wolfpld** [comment]
With 33ca38b5 you can set the `TRACY_TIMER_FALLBACK` define to use lower resolution timer on platforms that do not properly expose TSC.

**Comment by SuperWangKai** [comment]
The issue still exists since `SetupHwTimer` function with RDTSC check still entered. We are supposed to call the fallback version -
```c++
static int64_t SetupHwTimer()
{
    return Profiler::GetTime();
}
```
with `TRACY_TIMER_FALLBACK` on.

**Comment by wolfpld** [comment]
Ah, this one had slightly different #ifdef logic. Fixed in a3bfbab6.

**Comment by SuperWangKai** [comment]
Now it's working on both physical and virtual Android devices.

Addtionally, I wonder if AVD supports connection from Tracy? Though it may sound not that important.

**Comment by wolfpld** [comment]
Tracy opens a listening socket. The accessibility of that socket is a system configuration issue and is outside of Tracy scope.
