### ISSUE TITLE
Linking error with MinGW

### ISSUE THREAD

**Issue by 1vanK** [wolfpld/tracy#179]
`MinGW64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\lib\libdbghelp.a`

contains SymAddrIncludeInlineTrace, but

`MinGW64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\i686-w64-mingw32\lib\libdbghelp.a`

not contains, so this https://github.com/wolfpld/tracy/blob/master/client/TracyCallstack.cpp#L84-L95 cause linking error when DWARF is used

**Comment by wolfpld** [comment]
This is likely fixed now.
