### ISSUE TITLE
GPU Context naming does not work with TRACY_ON_DEMAND

### ISSUE THREAD

**Issue by egorodet** [wolfpld/tracy#183]
GPU Context naming introduced in Tracy v0.7.6 works as expected when application is collecting data from the startup, but has no effect when application is built with `TRACY_ON_DEMAND` for data collection from the moment of profiler connection. I use [custom implementation of the GPU context](https://github.com/egorodet/MethaneKit/blob/c98934e15da2572271b7a44e380ad7b274b8ef38/Modules/Common/Instrumentation/Include/Methane/TracyGpu.hpp#L147), but it sends the same messages and should have same behaviour as API-specific GPU Contexts provided with Tracy.

**Comment by wolfpld** [comment]
Fixed in 99c6b91.
