### ISSUE TITLE
compilation fail on MSVC due to StartupProfiler and ShutdownProfiler having different linkage

### ISSUE THREAD

**Issue by Dahrkael** [wolfpld/tracy#185]
I'm trying to compile the library TracyProfiler project adding TRACY_DELAYED_INIT and TRACY_MANUAL_LIFETIME as mentioned on the documentation. 
This fails with **error C2375: redefinition; different linkage** because StartupProfiler() and ShutdownProfiler() declarations in TracyProfiler.hpp are missing the TRACY_API macro in front of them, while their definition in the .cpp do have it.

**Comment by wolfpld** [comment]
Should be fixed in c288a790.
