### ISSUE TITLE
Fast memory leak/accumulation in simple sample

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#189]
Integrating Tracy for the first time into our build. No problems building (including only TracyClient.cpp) and linking into a simple sample (TRACY_ENABLE compiler flag set). However upon running that sample I'm seeing a very rapid memory growth from the process, about 1gb / s for this code:

```
flt64 delay() {
  ZoneNamedN(delayVar, "delay", true);
  int32 i, end;
  flt64 j = 0;

  for( i = 0, end = rand()/100; i < end; ++i ) {
    ZoneNamedN(loopVar, "loop iteration", true);
    j += sin(i);
  }

  return j;
}
``
int32 main( ) {
  while (true) {
    ZoneNamedN(outerVar, "outer", true);
    delay();
  }

  return 0;
}
```

Was searching through the docs/issues and may have missed a relevant post (if so apologies, and could you point me in the right direction?). Was following guidelines from the doc here:

3.4.2 Multiple zones in one scope
Using the ZoneScoped family of macros creates a stack variable named ___tracy_scoped_zone. If you want
to measure more than one zone in the same scope, you will need to use the ZoneNamed macros, which require
that you provide a name for the created variable. For example, instead of ZoneScopedN("Zone name"), you
would use ZoneNamedN(variableName, "Zone name", true)32.

**Comment by robertblaketaylor** [comment]
Seems like I missed the obvious answer:

  for( i = 0, end = rand()/100; i < end; ++i ) {
    ZoneNamedN(loopVar, "loop iteration", true);
    j += sin(i);
  }
  
Rough calculation, from the statistics (~6.7mil loop iterations/sec) puts growth at ~150b/zone. I imagine this is about the expected growth rate? Was looking around is there any define where I can have it work off a sliding time window or set a buffer limit (to drop old samples)?

**Comment by wolfpld** [comment]
CPUs are *fast*. 150 bytes per zone seems a bit excessive, as each one should only consume 32 bytes. There are of course additional costs related to organization of buffers and the inner workings of memory allocator, but these should be all fairly well amortized.

Tracy will not drop any recorded zones until they are delivered to the server, as a design decision. You may want to try the on-demand mode, which will skip recording zones until a connection is made, but it won't solve the problem you are having with your usage pattern. #182 proposes a solution for measuring performance of tight loops.

**Comment by robertblaketaylor** [comment]
I see though that even after the zone has been delivered to the server the memory footprint is retained in the client itself. This was a bit unexpected, and wanted to verify if that is expected behavior?

**Comment by wolfpld** [comment]
The buffers are never freed, but they are reused for storage of events in future. The reasoning here is that if you had a zone spike, it is likely that it will happen again, and we don't want to be constantly allocating and freeing memory.

**Comment by robertblaketaylor** [comment]
Should I expect to see the memory on the client continue to grow until
running out of memory on the machine? This was the concerning part as even
after the data is available to the profiler I don’t see the memory being
released.

**Comment by wolfpld** [comment]
If events are being generated faster than they are being drained, then yes, the memory usage will grow until OOM happens. I will repeat that emptied buffers are being kept for reuse, so generating new events does not necessarily cause memory usage growth.

**Comment by robertblaketaylor** [comment]
I understand, I’ll toss in some delays to observe the drain.
