### ISSUE TITLE
Compile failure: calloc argument value exceeds maximum object size

### ISSUE THREAD

**Issue by jwdevel** [wolfpld/tracy#193]
Building v0.7.7 and .6, I got this compile failure:

```
../../../server/TracyWorker.cpp: In member function ‘UpdateSampleStatisticsImpl’:
../../../server/TracyWorker.cpp:6536:40: warning: argument 1 value ‘18446744073709551598’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
         auto cfdata = (CallstackFrame*)alloca( ( fxsz-1 ) * sizeof( CallstackFrame ) );
                                        ^
../../../server/TracyWorker.cpp:6536:40: note: in a call to built-in allocation function ‘__builtin_alloca’
```

However, I can build v0.7.5 just fine.
I did some bisecting, and it looks like this was introduced in: 57ca6112
(that's the first commit that fails to compile, for me)

Perhaps this is some obscure compiler behavior change when `-flto` is turned on?

My compiler:

```
$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
```

**Comment by wolfpld** [comment]
18446744073709551598 is -18 signed, which conveniently is the result of `( fxsz-1 ) * sizeof( CallstackFrame )`, should `fxsz` be 0 (assuming this ever happens, and with valid data it won't).

07996c16 should fix this.

**Comment by jwdevel** [comment]
Ah, that fixed that case, but then I got a similar error later:

I'm guessing the fix is the same, so with this patch applied, now master is compiling (and running) for me.

```
diff --git a/server/TracyWorker.cpp b/server/TracyWorker.cpp
index 7cb74857..1cf9e59d 100644
--- a/server/TracyWorker.cpp
+++ b/server/TracyWorker.cpp
@@ -6519,7 +6519,7 @@ void Worker::UpdateSampleStatisticsImpl( const CallstackFrameData** frames, uint
     CallstackFrameId parentFrameId;
     if( fxsz != 1 )
     {
-        auto cfdata = (CallstackFrame*)alloca( ( fxsz-1 ) * sizeof( CallstackFrame ) );
+        auto cfdata = (CallstackFrame*)alloca( uint8_t( fxsz-1 ) * sizeof( CallstackFrame ) );
         for( int i=0; i<fxsz-1; i++ )
         {
             cfdata[i] = fexcl->data[i+1];
```

**Comment by wolfpld** [comment]
There is only one place with such `alloca` call.

```
% git grep alloca|grep fxsz
server/TracyWorker.cpp:        auto cfdata = (CallstackFrame*)alloca( uint8_t( fxsz-1 ) * sizeof( CallstackFrame ) );
%
```

What was the second error you got?

**Comment by jwdevel** [comment]
Ack, my mistake — I had my git branches out-of-sync, so didn't actually have your fix.

It works as-is, feel free to close this.
