### ISSUE TITLE
ubuntu 20.04 gcc-9 borks the compile

### ISSUE THREAD

**Issue by dchapiesky** [wolfpld/tracy#198]
yeah.... so ubuntu 20.04 LTS packages the default gcc/g++ as version 9 which includes c++17 experimental backend stuff which depends on the no longer latest revision of intel tbb....   so you first get messages from TracySort.hpp about wrong tbb version etc... 

So you download tbb and figure out it's weird compile from source documentation and get that installed and now you find g++-9's c++ 17 standard library making calls to tbb::task which believe it or not has been deprecated as experimental...

So you look and find out that ubuntu packages gcc-10 for long term service.... so you install that... and well.. same errors...

finally you try clang which you compiled from source too but which still uses (for some reason) gcc-9's c++17 headers which, of course, continue to refer to deprecated tbb functions...

the upshot of all this is....  a build configuration variable for NO_PARALLEL_SORT in TracySort.hpp would be super great to have for those of us dealing with LTS distributions which lack actual support...

(btw - forcing NO_PARALLEL_SORT fixed the problem)
love the tool!
thanks!

**Comment by wolfpld** [comment]
I have added `#ifdef` check for `NO_PARALLEL_SORT` in d71d7641 (in your case more as a precaution than as a necessity). You can build the profiler with `make CFLAGS=-DNO_PARALLEL_SORT` and it will do what you want.

**Comment by dchapiesky** [comment]
Thanks! absolutely love the tool!
