### ISSUE TITLE
Linux Compiler Error

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#199]
Bringing tracy online on linux for the first time (currently targeting windows/android). HItting this:

`Warning: LD_LIBRARY_PATH= environment not found
Tracy Profiler initialization failure: CPU doesn't support invariant TSC.
Define TRACY_NO_INVARIANT_CHECK=1 to ignore this error, if you know what you are doing.
Alternatively you may rebuild the application with the TRACY_TIMER_FALLBACK define to use lower resolution timer.`

The system we have doesn't default to having  LD_LIBRARY_PATH defined for accounts on linux. Also, for the TSC initialization issue, should we target the TRACY_TIMER_FALLBACK or is there a better path?

**Comment by wolfpld** [comment]
The `LD_LIBRARY_PATH` warning doesn't come from Tracy. The invariant check failure means that you either have a very old CPU, or you're running inside a VM that doesn't virtualize TSC. Using a fallback timer is the best option in such circumstances.
