### ISSUE TITLE
import-chrome: "args" is not imported

### ISSUE THREAD

**Issue by ethercrow** [wolfpld/tracy#20]
I'm importing trace data in Chrome format where most of the useful info is contained under `args` key like this:

``` 
 293   │   {
 294   │     "ts": 1589232324367717,
 295   │     "args": {
 296   │       "args": "[\"--user\",\"--no-user-package-db\",\"--package-db\",\"/Users/ethercrow/.stack/snapshots/x86_64-osx/87e154bcf63658f29f1e89e07af68ff63
       │ 963d64fc0e107f1e947001fc28f6600/8.6.5/pkgdb\",\"dump\",\"--expand-pkgroot\"]",
 297   │       "process": "/Users/ethercrow/.stack/programs/x86_64-osx/ghc-8.6.5/bin/ghc-pkg-8.6.5"
 298   │     },
 299   │     "tid": 4,
 300   │     "name": "sinkProcessStdout",
 301   │     "pid": 1,
 302   │     "ph": "B"
 303   │   },
 304   │   {
 305   │     "ts": 1589232324470187,
 306   │     "tid": 4,
 307   │     "name": "sinkProcessStdout",
 308   │     "pid": 1,
 309   │     "ph": "E"
 310   │   },
```

Unfortunately Tracy doesn't show this info:

<img width="1435" alt="Screen Shot 2020-05-11 at 11 27 02 PM" src="https://user-images.githubusercontent.com/222467/81615493-f96fcd80-93e1-11ea-8483-01f6dfb5ac20.png">

and as far as I can see in import-chrome.cpp, doesn't read that field. `tracy::Worker::ImportEventTimeline` doesn't appear to have a field where one could put this data.

**Comment by wolfpld** [comment]
Chrome tracing format is not well documented. While the format description lists every parameter possible, more often than not there's lack of explanation of the intended usage.

I have added support for passing per-zone custom text (as `std::string`) in https://github.com/wolfpld/tracy/commit/8e11cd5ebb38b488ea19bde071c6c7bf4bc6c792 (not tested), you can use that to extend parsing input data in the importer.

**Comment by ethercrow** [comment]
@wolfpld I'll try, thanks! Are there limitations on length and allowed characters like newlines there?

**Comment by wolfpld** [comment]
Fundamentally there shouldn't be. Newlines are explicitly supported (see `Worker::ProcessZoneText()`) and the text _might_ be cut-off by ImGui, or not fit on the screen, if too long, but there are no storage limits.
