### ISSUE TITLE
Client assertion fail in NextQueryId() from ~GpuCtxScope

### ISSUE THREAD

**Issue by tksuoran** [wolfpld/tracy#200]
After running program with OpenGL tracing for a bit, and having Tracy Profiler Stopped, I get assertion fail in this code:

```tracy_force_inline unsigned int NextQueryId()
    {
        const auto id = m_head;
        m_head = ( m_head + 1 ) % QueryCount;
        assert( m_head != m_tail );
        return id;
    }
```

`id = 65535`
`m_head = 0`
`m_tail = 0`
`QueryCount = 63336`

Callstack:

```
 	tracy::GpuCtx::NextQueryId() Line 184
 	tracy::GpuCtxScope::~GpuCtxScope() Line 304
```

- Tracy from master, commit 207a48e986063eaebbc18e0f7eb3838e0aaaf73d
- Windows 10
- GL Vendor: NVIDIA Corporation
- GL Renderer: GeForce RTX 3090/PCIe/SSE2
- GL Version: 4.6.0 NVIDIA 461.40
- GLSL Version: 4.60 NVIDIA

**Comment by wolfpld** [comment]
Are you calling `TracyGpuCollect` periodically?

**Comment by tksuoran** [comment]
I was not calling `TracyGpuCollect()` so that was a simple user error. Thanks!
