### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wolfpld/tracy#205]
I would like to point out that an identifier like “[`__TRACY_HPP__`](https://github.com/wolfpld/tracy/blob/d71d76414b8cc6a3d5658ceed57e540687d1c23e/Tracy.hpp#L1 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wolfpld** [comment]
This is a theoretical problem with no real consequences. In practice, most of the software is breaking this rule.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by wolfpld** [comment]
https://github.com/wolfpld/tracy/issues/205
