### ISSUE TITLE
Missing statistics for GPU Zones

### ISSUE THREAD

**Issue by slomp** [wolfpld/tracy#207]
I noticed that statistics don't show up for GPU Zones.
Is this due to a fundamental reason, or is this a regression/overlook?

**Comment by wolfpld** [comment]
Statistics for GPU zones are not implemented.

**Comment by slomp** [comment]
Ah, I see, so it boils down to disjoint operations.
Still, nothing is really preventing elapsed time statistics if we accept the risk of dealing with disjoint timestamps, right?
The bin concentration in the histogram of GPU zones could still provide insightful information, I imagine.

**Comment by wolfpld** [comment]
Yes, but someone has to do it. I don't feel like it, due to how unreliable capturing this data is.

**Comment by slomp** [comment]
Cool, I think I can give it a shot. I may have some questions about how the other zones and statistics are implemented.

**Comment by wolfpld** [comment]
This should be relatively easy job, you'll just have to replicate what is already there for the CPU zones.

**Comment by benvanik** [comment]
Would also love to see even a simple summary of GPU zones. Today we are stuck eyeballing the things that look like they take time, which really diminishes the value of using tracy for this type of investigation (vs tools like nsight, which are deficient in a lot of other areas for whole program investigation and can be much more annoying to setup).

Something that prevents the need to zoom around and hover over the boxes that show up would solve the 90% use case of "what is the low hanging fruit":
![image](https://user-images.githubusercontent.com/75337/126000500-bffabe66-491f-4f34-913e-5d3c05ec4bfd.png)

@wolfpld would an extra "GPU" tab on the statistics screen be ok? 
![image](https://user-images.githubusercontent.com/75337/126000818-ec912b32-34c8-4d79-bb6f-37aa8a3ff604.png)
(don't even need a fancy graph or anything, just a sorted list of total time/count/mtpc would be great)

happy to take this on unless @slomp already got started

**Comment by wolfpld** [comment]
> would an extra "GPU" tab on the statistics screen be ok?

Yeah, sure.

**Comment by stgatilov** [comment]
Not being able to see even the simple mean & histogram of one-per-frame GPU task is very limiting.

It is a bit strange to offer GPU-side profiling for many APIs, but not show any statistics because this data is bad. I guess that's what every user of GPU-side timings has to accept, and that has nothing to do with Tracy?...

**Comment by wolfpld** [comment]
Minimal statistics should be available with 361782f3.

**Comment by slomp** [comment]
This is now part of the 0.8.0 release, correct?

**Comment by wolfpld** [comment]
It is.
