### ISSUE TITLE
Support importing Location from chrome-import

### ISSUE THREAD

**Issue by JohanEngelen** [wolfpld/tracy#212]
Although there is no 'official' support for file location data in the chrome tracing file format, would it be possible to add the capability to chrome-import to import location data from a special json field?
For example:
```json
        {
            "args": {
                "detail": "some detail text",
                "loc": "dir/filename.d:27"  <--new, recognized by chrome-import
            },
            "dur": 10303297,
            "name": "Activity 1",
            "ph": "X",
            "pid": 130,
            "tid": 130,
            "ts": 9600257
        }
```

Thanks!

**Comment by wolfpld** [comment]
Added in 05b5f1cf. `args` is converted to zone text, so the `loc` tag should be at root level.

**Comment by JohanEngelen** [comment]
Thank you very much for the quick addition. Works well!
