### ISSUE TITLE
How to install tracy on linux?

### ISSUE THREAD

**Issue by WilliamWangPeng** [wolfpld/tracy#214]
Hi dear author,  
    I have read the user manual, but did not find what are the detailed steps for installing, could you show steps here?  

thank you  
best regards  
William

**Comment by wolfpld** [comment]
What do you mean by "installing"?

**Comment by WilliamWangPeng** [comment]
> What do you mean by "installing"?

building   
I find building errors in profiler/build/unix
do you know how to solve this?  

![image](https://user-images.githubusercontent.com/51076736/118131303-f19d9b80-b430-11eb-95d2-e1df0708d9d4.png)

**Comment by WilliamWangPeng** [comment]
> > What do you mean by "installing"?
> 
> building
> I find building errors in profiler/build/unix
> do you know how to solve this?
> 
> ![image](https://user-images.githubusercontent.com/51076736/118131303-f19d9b80-b430-11eb-95d2-e1df0708d9d4.png)

**Comment by wolfpld** [comment]
2.3.1.2 in the manual.
