### ISSUE TITLE
How to run the Tracy-release

### ISSUE THREAD

**Issue by WilliamWangPeng** [wolfpld/tracy#215]
Hi dear @wolfpld   
    Honor to write this issue to you, I have built the Tracy and want to know how to run the Tracy-release on linux?  

![image](https://user-images.githubusercontent.com/51076736/118134178-3545d480-b434-11eb-9fed-85f35a2e6008.png)

![image](https://user-images.githubusercontent.com/51076736/118134200-3c6ce280-b434-11eb-8557-825fb2a66a44.png)
 

thank you  
Very kind of you  
William

**Comment by wolfpld** [comment]
You can find all the information you need in the manual.
