### ISSUE TITLE
TRACY_NO_INVARIANT_CHECK issue on multiple systems

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#219]
We've got a number of systems where we are executing Tracy with various levels/age of HW. What is the implication of permanently setting TRACY_NO_INVARIANT_CHECK?

Error:
Tracy Profiler initialization failure: CPU doesn't support invariant TSC.
Define TRACY_NO_INVARIANT_CHECK=1 to ignore this error, if you know what you are doing.

**Comment by wolfpld** [comment]
Timer readings may be inconsistent between different cores, or the timer may be subject to CPU clock speed changes.

**Comment by robertblaketaylor** [comment]
Thank you for the quick feedback!
