### ISSUE TITLE
Add support for instrumentation of std::mutex locks with std::condition_variable

### ISSUE THREAD

**Issue by egorodet** [wolfpld/tracy#23]
Tracy provides a convenient way for instrumentation of `std::mutex` with `TracyLockable` wrapper and integration with `std::lock_guard` using `LockableBase`, but this is not enough to cover all use cases. A way for instrumentation of `std::mutex` locks using `std::condition_variable` is also required:
```cpp
// common thread variables
std::mutex              wait_mutex;
std::condition_variable wait_condition_var;
bool                    is_signalled = false;

// waiting thread
std::unique_lock<std::mutex> lock(wait_mutex);
wait_condition_var.wait(lock, [this]{ return is_signalled; });

// signalling thread
is_signalled = true;
wait_condition_var.notify_one();
```

**Comment by wolfpld** [comment]
You can use `LockableBase` with `std::unique_lock`, and then use `std::condition_variable_any`. Is that not enough?

**Comment by egorodet** [comment]
Yes, it works just fine with `std::conditional_variable_any`, thanks a lot for fast solution!

**Comment by cmaughan** [comment]
I tried this, but I found that Tracy doesn't seem to show the wait period caused by the condition.wait()

**Comment by wolfpld** [comment]
Waiting in condition variable is subject to internal implementation details of the standard library.

**Comment by cmaughan** [comment]
I wrapped a ZoneScoped around the wait.  Is that the best I can do?

**Comment by wolfpld** [comment]
Context switch data should indicate when the sleep period occurs.
