### ISSUE TITLE
Multi-line messages cause display issues

### ISSUE THREAD

**Issue by Xenonic** [wolfpld/tracy#231]
Hi Bartosz, I'm having an issue where multi-line messages cause jumps while scrolling, and some messages to not be shown entirely. This appears to happen with any message that contains a newline character.

![tracyMessages](https://user-images.githubusercontent.com/18013792/121962369-e5557880-cd25-11eb-8ca0-55659211c8a6.gif)

Here's the trace as well: [LongMessage.tracy.txt](https://github.com/wolfpld/tracy/files/6651355/LongMessage.tracy.txt)

**Comment by wolfpld** [comment]
Fixed in 39e317f3.
