### ISSUE TITLE
customize font size in GUI

### ISSUE THREAD

**Issue by dpelle** [wolfpld/tracy#232]
I do not see any way in the Tracy GUI to increase the font size.

Tracy font size is quite small in my setup and sometimes hard to read. 
I did not see any way to increase the font size from the menus.
I also tried things like `CTRL +` but that did not do anything.
Maybe there is a way which I missed.  If not, being able to customize
the font size in the GUI would be a useful features if that's not considered
feature creep.

**Comment by wolfpld** [comment]
Tracy should adapt to system DPI.
https://github.com/wolfpld/tracy/blob/5834a4be4413372e9ad8985753a1aaf5e0e81209/profiler/src/main.cpp#L281-L298
Is it not working for you?

**Comment by dpelle** [comment]
> Is it not working for you?

Hmmm, so if I change my DPI, I should be able to view the Tracy GUI more zoomed-in.
I'm not sure how this is done. I just tried doing something like this:
```
$ xfconf-query -c xsettings -p /Xft/DPI -s 130
```
I can see that it increase the font size in e.g. my terminal or in Firefox, but the Tracy GUI remains exactly the same.
So that did not work so far.

Is there another way?

I'm using Tracy 0.7.8 on Linux xubuntu-18.04.5.

**Comment by wolfpld** [comment]
You can manually override `dpiScale` value in the code.

I'd suggest to update to a distro that has up-to-date packages (Ubuntu 18.04 has glfw 3.2, which doesn't support retrieving DPI from system).

**Comment by dpelle** [comment]
{quote}You can manually override dpiScale value in the code.{quote}
Ah of course.  I've just make the following crude local change, which serves my purpose perfectly:

```
$ git diff
diff --git a/profiler/src/main.cpp b/profiler/src/main.cpp
index 8971497d..7e6d8eb6 100644
--- a/profiler/src/main.cpp
+++ b/profiler/src/main.cpp
@@ -296,6 +296,12 @@ int main( int argc, char** argv )
     }
 #  endif
 #endif
+    auto dpiScaleEnv = std::getenv("TRACY_DPI_SCALE");
+    if (dpiScaleEnv)
+    {
+      dpiScale = atof(dpiScaleEnv);
+      fprintf(stderr, "(debug) override dpiScale to =%f\n", dpiScaleEnv);
+    }
 
     // Setup ImGui binding
     IMGUI_CHECKVERSION();
```

By default, dpiScale was 1.0 overriding it to 1.5 with the following command works perfectly:
```
$ TRACY_DPI_SCALE=1.5 Tracy-release
```

{quote}I'd suggest to update to a distro that has up-to-date packages (Ubuntu 18.04 has glfw 3.2, which doesn't support retrieving DPI from system).{quote}

Yes, although that will wait for that, as I do not want to mess up with a working system at work.

In any case, this issue can be closed, unless you consider that there could be a configurable option by default in Tracy, via an environment variable as I did, or via menus in the GUI.

Thanks!

**Comment by wolfpld** [comment]
Added in 8f8a28db60.

**Comment by wolfpld** [comment]
BTW, the ability to change font size through the UI was added in 0.8. These changes are temporary and the default scaling will be used after restart.
