### ISSUE TITLE
The procedure entry point SymFromInlineContext could not be located in dynamic link library tracy.dll

### ISSUE THREAD

**Issue by skiddling** [wolfpld/tracy#233]
hi, i compile the tracy in win10, vs2015 ,release mode, everything is ok, but when i try to run the program with tracy, it shows the The procedure entry point **SymFromInlineContext** could not be located in dynamic link library tracy.dll, i use dumpbin to checked the exports api, there is no SymFromInlineContext in the dll,  please help me, thanks

**Comment by wolfpld** [comment]
Fixed in fde62b4e.
