### ISSUE TITLE
Adjustable DPI scale setting

### ISSUE THREAD

**Issue by jmrico01** [wolfpld/tracy#236]
Sometimes you'll want to share captured traces with other people, and sometimes that will happen through a screen-share. If I am screen-sharing any application, I immediately try to find a "zoom-in" or "scale up" setting. It would be useful to have this setting in Tracy - specifically something where you can dynamically adjust the DPI scale.

The workaround at the moment is to download a master build from the CI jobs and start `Tracy.exe` with environment variable `TRACY_DPI_SCALE` set to the desired scale. The release versions don't seem to ship with this ability, though in any case it would be nice to support it in a more ergonomic way.

**Comment by wolfpld** [comment]
Implemented in f9904c1f.

**Comment by jmrico01** [comment]
Amazing, thank you !!
