### ISSUE TITLE
Manual misses tbb as external library.

### ISSUE THREAD

**Issue by mcourteaux** [wolfpld/tracy#239]
I had to apt install libtbb-dev as well to make the server build successfully.

**Comment by wolfpld** [comment]
TBB is not a dependency for Tracy. It is a dependency of gcc (libstdc++, to be precise).

**Comment by mcourteaux** [comment]
Ah, I didn't know, but still, it would be useful to add this bit of information to the relevant section of the manual, IMO. :smile:

**Comment by Krzmbrzl** [comment]
I agree that it would probably be nice to mention it anyway, since it appears that it is not installed by default on at least some Linux distros
