### ISSUE TITLE
What does TracyGpuZone do?

### ISSUE THREAD

**Issue by mcleary** [wolfpld/tracy#24]
Hello, I am experimenting with the GPU tracing capabilities and I am trying to understand what GPU tracing capabilities does tracy offer. I couldn't find an example code using this feature. So, to see what is does I have the following Draw function in my sample application.

```c++
void Draw()
{
    ZoneScoped;
    TracyGpuZone("GPU Draw");
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    TheScene->Draw();
}
```

And right after I initialise my context I call `TracyGpuContext`.

In the profiler UI I see a zone with the name "GPU Draw". When I hover the mouse in it I get a GPU execution time. Which is great! I was just wondering if this is all that is meant to be collected and what would be some other use cases for the `TracyGpuZone` feature.

Thanks.

**Comment by wolfpld** [comment]
`TracyGpuZone` injects GPU timestamp reading into GPU command buffers, when it is created and destroyed. It measures the time that GPU spent on execution of the draw calls. You may add further `TracyGpuZone` markers inside your `TheScene->Draw()` call to see more fine grained information about things you are rendering.

**Comment by mcleary** [comment]
Excellent, thanks for the quick reply.
