### ISSUE TITLE
Android without root permission, the program will freeze when TRACY_ENABLE=1

### ISSUE THREAD

**Issue by JIA-ss** [wolfpld/tracy#240]
Tracy is okay to run in the c++ environment, but when I package it as an apk with unity, the phone will stop stuck..

 Can't I exe tracy on the android phone without root permission ?

**Comment by JIA-ss** [comment]
How can I make tracy run correctly on android phones without root permissions

**Comment by JIA-ss** [comment]
I have gotten the point, 

if tracyProfiler recieve the message from the OS, it will run the function ThreadFreezer, which will make the main thread sleep forever. QAQ, 

so It may be easier to locate the problem using assert here

static void ThreadFreezer( int /*signal*/ )
{
    for(;;) sleep( 1000 );
}

**Comment by wolfpld** [comment]
With the extra information from #244, I think this may be related to #245.
