### ISSUE TITLE
Add an "asynchronous zones" feature

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#241]
I currently have the usecase (that I have seen come up in one form or another on the discord and also in Issue #5) where I want to profile an application that uses coroutines. With coroutines, you will run into cases where child-zones are closed after their parent zones, which means they break the stack requirement of zones and currently are not possible.

There is a concept in Tracy though, that comes pretty close to this, and I think can be used as a hack: Discontinuous frames. I have not tried this, but I suspect you could abuse FrameMarkNamed and FrameEndNamed to work like a TracyCFrameMarkStart and TracyCFrameMarkEnd pair, that doesn't live on the stack.

I want to request a similar concept, that I would call "asynchronous zones" (or whatever, really): An Asynchronous Zone would behave like a discontinuous frame does now, in that the there is no parent-child relationship, so that there is no stack that must be respected. All Asynchronous zones, marked by a pair of TracyCAsyncZone(name, id) and TracyCAsyncZoneEnd(name, id) calls with matching names AND ids, are completely independent of each other. There must only ever be one async zone with the same name and id active at the same time. The id is usually easy to come by in a coroutine or general scheduling system, since there is always a context-pointer or job-id.

The profiler would display asynchronous zones in their own "swim lane", which would basically be halfway between how frames and how zones are displayed: 
- You have a horizontal segment, like how zones of a thread are currently displayed, but instead of having one zone-row per stack level, the zones are just placed in how ever many rows needed to show all asynchronous zones that were happening at the time.
- The way how vsync is currently displayed for 2 monitors would essentially be a swimlane where there are always exactly two asynchronous zones active, that start after a vblank and end at the next.

This would already allow for some not-totally-hacky-and-discouraged coroutine-profiling. I have 3 more suggestions with varying levels of complexity, that would make this a lot more powerful though:
- 1: Group each set of AsyncZones with the same ID into their own simlane. The ID for an async zone is basically the same thing as the thread id for a normal zone.
- 2: Add Functions TracyCPauseAsyncZones/TracyCResumeAsyncZones that take only this ID and mark any active async zone with the given ID as paused/resumed, in the same way that locks are displayed.
- 3: Enforce the stack-requirement of normal zones for async zones on a per ID basis, and display a normal zone-stack for each ID. With that we would go full circle to effectively just allow the user to specify the thread-id of a normal zone themselves.

As I'm writing this, I realize that I sort of mixed the concept of a user-specifiable-thread with that of a completely independent async event, but they seem to overlap quite a bit, so I think its not too bad of a conflation.

Async Zones are a concept that exists, for example, in the chrome trace event format and which I also implemented in an older profiler of mine and found it really useful. Even if you don't think the "extended suggestions" are reasonable/worth it, just generalizing the concept of discontinuous frames to async zones would already be a win for my usecase.

**Comment by simonvanbernem** [comment]
Sorry, I realized that this might have a lot of overlap with issue #149 after I opened it. Might be a duplicate.

**Comment by wolfpld** [comment]
Yes, I think it is pretty much a duplicate.

I'm not sure if I see the usability of having a bunch of unassorted zones thrown together into the mix. I have instead imagined a solution where the fibers/coroutines/whatever are properly structured (with parent-child relations) in virtual thread lanes.

**Comment by simonvanbernem** [comment]
Sounds reasonable. It definitely covers the vast majority of what one would use unstructured zones for anyway. I'll close this one.
