### ISSUE TITLE
Throwing C++ exceptions after tracy has unloaded can crash

### ISSUE THREAD

**Issue by jkriegshauser** [wolfpld/tracy#245]
Verified on Windows, probably on Linux too.

1. Compile with tracy contained in a DLL
2. Load the DLL and call `tracy::StartupProfiler()`
3. Call `tracy::ShutdownProfiler()` and unload the DLL
4. Throw an exception.

This is likely because `Profiler::SpawnWorkerThreads()` calls `AddVectoredExceptionHandler` but never removes it during shutdown. Since the registered function was contained in a DLL that is now unloaded, a crash occurs.

**Comment by wolfpld** [comment]
Should be fixed on master, but I don't have a way to verify this.

https://github.com/wolfpld/tracy/compare/5936e7c..9242245

**Comment by jkriegshauser** [comment]
Finally pulled this down today and it does the trick. Thanks!
