### ISSUE TITLE
Android, not seeing any events without root permission

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#250]
Is it expected to not see any events from the device if the application is not executed with the root permission? Running a binary directly on device and seeing the app show up in the profiler on the host. Moment I move to APK (debuggable) not seeing anything come through. Any other configuration requirements for using Tracy under an APK vs. a native binary?

**Comment by wolfpld** [comment]
Privilege escalation is not needed for the profiler to operate. Are you requesting `android.permission.INTERNET` in the `AndroidManifest.xml`?

**Comment by robertblaketaylor** [comment]
Yes, among others:

  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.INTERNET" />
  
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

I'm forwarding 8086 for the desktop to see it (like with the native app). Is there anything else missing to ensure it shows up in the profiler? I was going to take a look at the network traffic to see if its coming out at all over the network, if you have a suggestion on where to start also appreciated.

**Comment by wolfpld** [comment]
Why do you need to forward the port?
