### ISSUE TITLE
not able to compile using mingw 

### ISSUE THREAD

**Issue by hero2002** [wolfpld/tracy#256]
I am trying to use tracy with mingw and I get this errors
I am using 

> g++ (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0

```
in file included from C:\enough_words_c_tcod\src\tracy-0.7.7/TracyClient.cpp:22,
                 from C:\enough_words_c_tcod\src\main.cpp:2:
C:\enough_words_c_tcod\src\tracy-0.7.7/common/tracy_lz4.cpp:168: note: macro "expect" defined here
  168 | #  define expect(expr,value)    (__builtin_expect ((expr),(value)) )
      | 
C:\enough_words_c_tcod\src\tracy-0.7.7/common/tracy_lz4.cpp:168:52: error: expected identifier before '(' token
  168 | #  define expect(expr,value)    (__builtin_expect ((expr),(value)) )
      |                                                    ^
C:/enough_words_c_tcod/include/libtcod/lex.hpp:64:8: note: in expansion of macro 'expect'
   64 |   bool expect(int tokenType, const char* tokenValue);
      |        ^~~~~~
C:\enough_words_c_tcod\src\tracy-0.7.7/common/tracy_lz4.cpp:168:59: error: expected identifier before '(' token
  168 | #  define expect(expr,value)    (__builtin_expect ((expr),(value)) )
      |                                                           ^
C:/enough_words_c_tcod/include/libtcod/lex.hpp:64:8: note: in expansion of macro 'expect'
   64 |   bool expect(int tokenType, const char* tokenValue);
      |        ^~~~~~

Build finished with error(s).
The terminal process terminated with exit code: -1.
```

**Comment by wolfpld** [comment]
Why are you including source files from within other source files?

**Comment by hero2002** [comment]
> Why are you including source files from within other source files?

as I read from pdf that how I should include it
maybe I didn't understand it correctly, how I should do it?

**Comment by wolfpld** [comment]
Which exact wording in the manual you are referring to?

**Comment by hero2002** [comment]
> Which exact wording in the manual you are referring to?

> copy all files from the Tracy checkout directory to your project With the source code included in your project, add the tracy/TracyClient.cpp source file to the IDE
project

**Comment by wolfpld** [comment]
Each source file should be compiled to its own separate object. These objects are then linked together into an executable.

**Comment by hero2002** [comment]
> Each source file should be compiled to its own separate object. These objects are then linked together into an executable.

great, but I still don't know how to do this as I didn't find a make or cmake configuration in the source

**Comment by wolfpld** [comment]
Tracy is not intended to be a programming tutorial. You can see `test/Makefile` for an example of how you can build a simple program, but I don't know what else you'd expect to be here.

**Comment by hero2002** [comment]
> Tracy is not intended to be a programming tutorial. You can see `test/Makefile` for an example of how you can build a simple program, but I don't know what else you'd expect to be here.

that what I was looking for

**Comment by hero2002** [comment]
still the same problem using make

**Comment by hero2002** [comment]
> Tracy is not intended to be a programming tutorial. You can see `test/Makefile` for an example of how you can build a simple program, but I don't know what else you'd expect to be here.

also I am not that dump

**Comment by hero2002** [comment]
no solution until now so I might just close this
