### ISSUE TITLE
Problem with Tracy in a DLL and TRACY_NO_EXIT

### ISSUE THREAD

**Issue by mcleary** [wolfpld/tracy#26]
Hi, I am doing more tests with Tracy and this time I am trying to use a DLL as described in the Section 2.1.4 of the manual. For this setup I have a single thread application that calls into a library (DLL) that is supposed to be profiled with Tracy but I am getting an access violation in the Profiler destructor. Here are more details of my setup

1. DLL Called `TracyClient.dll` containing just `TracyClient.cpp`
2. A DLL that I want to profile with Tracy, called `TracyBackend.dll`
3. An application that links against `TracyBackend.dll`
4. The application runs with `TRACY_NO_EXIT`

This only happens when `TRACY_NO_EXIT` is defined. Is there a limitation here?

The following image shows the place of the crash.

![image](https://user-images.githubusercontent.com/1537712/82558678-19cc2480-9b66-11ea-8459-e4c9cfabffd5.png)

**Comment by wolfpld** [comment]
> This only happens when TRACY_NO_EXIT is defined. Is there a limitation here?

This is certainly possible. Linking with DLLs is unfortunately a bit of no man's land.

**Comment by mcleary** [comment]
I know that Windows has some weird shenanigans when shutting down DLLs. My guess is that internal threads of tracy are being destroyed without notice and memory is getting corrupted by the time the 'Profiler' destructor gets executed. If there is no easy fix for that I'll keep investigating with this in mind.

**Comment by mcleary** [comment]
Well, my hypothesis was somewhat correct. The `TRACY_NO_EXIT` mechanism operates in a thread. By the time the main function finishes, there are no threads anymore, so that's why it doesn't work. At least I have a patch to prevent the Profiler from crashing. I will submit is soon.

**Comment by mcleary** [comment]
I will close this issue for now as DLLs are a bit complicated but I am glad the application is not crashing anymore due to my patch.

**Comment by livinamuk** [comment]
How did the patch work? I'm having trouble with running Tracy inside my Maya plugin which is a dll.

**Comment by wbkangtc** [comment]
Sorry to necro this, but I noticed that on MSVC with multi_DLL, this is still the case?
I've built `Tracy::TracyClient` as shared lib(dll), and linked it to my executable with:
```
#define TRACY_ENABLE 1
#define TRACY_NO_EXIT 1
#define TRACY_IMPORTS 1
```
And it doesn't wait for connection and just exits.
Building `Tracy::TracyClient` as static and linking it works fine.

Currently on `5d542dc09f3d9378d005092a4ad446bd405f819a # 0.11.1.`
