### ISSUE TITLE
Chrome import: all instant events put to same thread

### ISSUE THREAD

**Issue by stgatilov** [wolfpld/tracy#267]
When I use import-chrome utility on my trace, all `i`nstant events are assigned to the same thread, although the json source has different tid on them:

```
{ "ts": 346.300, "pid": 0, "tid": 125, "ph": "B", "name": "zone", "args": { "_0": "T12 E21" } },
{ "ts": 346.500, "pid": 0, "tid": 125, "ph": "i", "name": "test\nT12 E21" },
{ "ts": 346.800, "pid": 0, "tid": 123, "ph": "B", "name": "zone", "args": { "_0": "T8 E73" } },
{ "ts": 347.000, "pid": 0, "tid": 123, "ph": "i", "name": "test\nT8 E73" },
{ "ts": 347.000, "pid": 0, "tid": 125, "ph": "E" },
{ "ts": 347.100, "pid": 0, "tid": 124, "ph": "B", "name": "zone", "args": { "_0": "T9 E41" } },
{ "ts": 347.300, "pid": 0, "tid": 124, "ph": "i", "name": "test\nT9 E41" },
{ "ts": 347.500, "pid": 0, "tid": 123, "ph": "E" },
```
![image](https://user-images.githubusercontent.com/13484213/134523618-27b5f879-5228-496b-8e16-003367450d72.png)

Here is full json trace: [temp.zip](https://github.com/wolfpld/tracy/files/7218351/temp.zip)

**P.S.** I'm currently implementing a basic timeline profiler similar to Tracy (but a lot simpler of course) for a project where full-blown Tracy client won't be welcome. I generate output in chrome:tracing format, so that I could reuse the excellent Tracy viewer to inspect traces.

**Comment by wolfpld** [comment]
Fixed in bcfc4a4f.
