### ISSUE TITLE
/data/tracy_systrace crashes on Android 11

### ISSUE THREAD

**Issue by bretalfieri** [wolfpld/tracy#270]
/data/tracy_systrace crashes with Segmentation fault on Android 11. This causes cpu context switch data not to appear in the GUI.

Workaround:
Comment out TracySysTrace.cpp:1635
execlp( "su", "su", "root", "sh", "-c", "/data/tracy_systrace", (char*)nullptr );

**Comment by bretalfieri** [comment]
Backtrack from GDB:

Program received signal SIGSEGV, Segmentation fault.
0xb7f53c30 in ?? ()
(gdb) where
#0  0xb7f53c30 in ?? ()
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by wolfpld** [comment]
This has been completely reimplemented.
