### ISSUE TITLE
Window docking broken on macOS

### ISSUE THREAD

**Issue by BuzzwordChief** [wolfpld/tracy#275]
Window docking zones seem misaligned:

https://user-images.githubusercontent.com/11695209/139754994-b2470fab-d22c-44fa-9a9b-d805252f89a6.mov

macOS 10.15.7 (Catalina)
Tested with master and 0.7.8 release (both broken)

**Comment by wolfpld** [comment]
MacOS has issues with scaling, which stem from inconsistent ImGui behavior across platforms.

See https://bitbucket.org/wolfpld/tracy/issues/42/cannot-scroll-down-capture-on-macos for more details.

**Comment by BuzzwordChief** [comment]
Bummer...
Regardless, thank you for this awesome tool!
