### ISSUE TITLE
InitFailure returns success when Tracy fails

### ISSUE THREAD

**Issue by eugeneko** [wolfpld/tracy#281]
It took me maybe a day to find why CI doesn't run tests.
The issue was that CI doesn't support HW timers, and it's okay, I'll just disable it.

BUT why would Tracy return _success_ code in InitFailure?
Because of this, nothing in CI detects any problems and continues just fine.

https://github.com/wolfpld/tracy/blob/887826a28ae47b63be44b55688b7c66a59057fc1/client/TracyProfiler.cpp#L322

**Comment by wolfpld** [comment]
Fixed in 987f70a9.
