### ISSUE TITLE
Suggested change to manual about build process (section 2.3.2)

### ISSUE THREAD

**Issue by aclysma** [wolfpld/tracy#282]
I helped someone recently who was trying to build tracy. They were following the manual but could not find makefiles in `build/unix`. They needed to look in `profiler/build/unix` - I mentioned that and they were able to build and run. (I had the exact same confusion about year ago when I first tried to build this project.)

Do you think some clarification in the manual would be helpful? Since there are a few directories with build/unix in them, maybe it would be helpful to mention that there several directories with build files ('capture', 'csvexport', 'profiler', etc.). I suspect most people are looking for `profiler/build/unix`.

(p.s. thanks for all the work on this project!)

**Comment by wolfpld** [comment]
The directory layout is described in 2.3, but I understand that the page of text about headache-inducing library management may make it easy to forget. I have added the following preamble to 2.3.2:

>As mentioned earlier, each utility is contained in its own directory, for example \texttt{profiler} or \texttt{capture}\footnote{Other utilities are contained in the \texttt{csvexport}, \texttt{import-chrome} and \texttt{update} directories.}. Where do you go within these directories depends on the operating system you are using.

It will be pushed to the repo shortly.
