### ISSUE TITLE
Unity - crash handler invoked from Mono GC

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#284]
Were observing the crash handler get invoked when Mono triggers its garbage collection via SIGPWR. It looks like there is no build flag to disable the crash handler or parts of the crash handler upstream. Commented out the sigaction in TracyProfiler.cpp as a short term workaround:

```
#ifdef __linux__
    struct sigaction threadFreezer = {};
    threadFreezer.sa_handler = ThreadFreezer;

    // sigaction( SIGPWR, &threadFreezer, nullptr );

    struct sigaction crashHandler = {};
    crashHandler.sa_sigaction = CrashHandler;
    crashHandler.sa_flags = SA_SIGINFO;
    sigaction( SIGILL, &crashHandler, nullptr );
    sigaction( SIGFPE, &crashHandler, nullptr );
    sigaction( SIGSEGV, &crashHandler, nullptr );
    sigaction( SIGPIPE, &crashHandler, nullptr );
    sigaction( SIGBUS, &crashHandler, nullptr );
#endif
```

What is the right way to resolve this & is this expected?

**Comment by wolfpld** [comment]
This is expected, as there is a very limited selection of signals to hook to. Conflicts will happen. You can workaround this with bbbd7888.

**Comment by robertblaketaylor** [comment]
Thanks! Is the expectation that we'd hook that to a different signal, ex. SIGABRT?

**Comment by wolfpld** [comment]
Yes, you can choose your own signal identifier this way. I wouldn't recommend using `SIGABRT`, as this signal is commonly in use and changing its handler would disturb the program execution in the same way as `SIGPWR` currently does. See `man 7 signal` for a list of available ones and choose one that you don't expect to be in use.

**Comment by robertblaketaylor** [comment]
Was looking at https://man7.org/linux/man-pages/man7/signal.7.html. Thanks!
