### ISSUE TITLE
Crash during mutex initialization if TRACY_ON_DEMAND is used

### ISSUE THREAD

**Issue by Sven-v-Beuningen** [wolfpld/tracy#285]
Hi,

first of all I'd like to thank you for this great tool. Keep Going!!

We're currently integrating tracy in our rendering engine. First of all everything went smooth, but after some testing I've seen that our memory usage is going to explode. To solve this we defined TRACY_ON_DEMAND, which should fulfill our needs very well.
Unfortunately I found out that defining TRACY_ON_DEMAND leads to crashes in mutex initialization around 6/10 runs. I can easily reproduce this, with this code.

```
#include <Tracy.hpp>
#include <mutex>

int main(int argc, char* argv[]
{
    TracyLockable(std::mutex, mutex);

    while (true);

    return 0;
}
```

Am I doing something wrong? We're using Visual Studio 2019 with /std:c++latest for this example. We defined TRACY_ENABLE and TRACY_ON_DEMAND.

Best Regards

Sven

**Comment by wolfpld** [comment]
I am unable to reproduce this. Do you have a call stack of the crash you are having?

**Comment by Sven-v-Beuningen** [comment]
Thank you for your reply. I have a stack trace from visual studio 2019;

```
 	ntdll.dll!00007ffeb9785225()	Unknown
>	main.exe!_Smtx_unlock_exclusive(void * * smtx) Line 38	C++
 	main.exe!std::shared_mutex::unlock() Line 50	C++
 	main.exe!tracy::Profiler::DeferItem(const tracy::QueueItem & item) Line 635	C++
 	main.exe!tracy::LockableCtx::LockableCtx(const tracy::SourceLocationData * srcloc) Line 35	C++
 	main.exe!tracy::Lockable<std::mutex>::Lockable<std::mutex>(const tracy::SourceLocationData * srcloc) Line 186	C++
 	main.exe!main(int argc, char * * argv) Line 8	C++
 	[External Code]	
```

Additional information: I have the issue in Release, Debug and RelWithDebInfo build.
Please let me know If you need more information.

Best Regards

Sven

**Comment by wolfpld** [comment]
Can you provide a minimal reproducible example, which contains not only the source code, but all the project files? It looks like some combination of settings you are using may be affecting this?

**Comment by Sven-v-Beuningen** [comment]
I just tried to create a simple example project and I think I found my error. I define TRACY_ON_DEMAND only for my project, but nor for the TracyClient library. It seems that TRACY_ON_DEMAND also does influence the TracyClient. So if I use or not use TRACY_ON_DEMAND for my project and the TracyClient, it seems fine
