### ISSUE TITLE
Poor scrolling behavior with many threads

### ISSUE THREAD

**Issue by adepke** [wolfpld/tracy#286]
I have a trace that contains a very large amount of threads, and attempting to zoom onto zones far down in the thread list causes threads up above to leave the viewing space, shifting everything extremely far up. [Here's a trace](https://github.com/wolfpld/tracy/files/7585103/LotsOfZones.tracy.txt) producing this behavior.

https://user-images.githubusercontent.com/18013792/142952480-0a502491-d5b6-4f0b-807f-f2fc64fe66c8.m

**Comment by wolfpld** [comment]
It is a known issue. Sorry, no easy fix for this right now (I tried).

**Comment by wolfpld** [comment]
Fixed by #519.
