### ISSUE TITLE
discard frames older than x

### ISSUE THREAD

**Issue by ohsix** [wolfpld/tracy#287]
hello,

just started evaluating tracy for something and noticed live readout in the profiler works pretty well, now i want to use it for stuff that records for a long time (read: 5-15 minutes) where only the last 200 frames or so matter

an option to discard frames older than $time or before $number would allow me to watch the profiler in real time without concern to the memory footprint

thanks!

**Comment by wolfpld** [comment]
There is no discarding old data in Tracy.

**Comment by ohsix** [comment]
yea, i've read the documentation* and looked through all the options (and closed github issues) to see if it was available or turned down for a specific technical reason before asking

it's not requesting a memory limit or memory control, just not keeping old frames. it would enable a bunch of use cases and casual uses for me. i can work around it but just clicking a button in the main view when it's live that throws away old frames while it is on would let me watch trends and events i'm not necessarily interested in recording, but may represent when i would want to start recording

*) 
![Screenshot from 2021-11-24 18-10-20](https://user-images.githubusercontent.com/3180944/143365609-cf7d93b5-2310-4e4b-b2ea-e78741ad3b7a.png)

**Comment by wolfpld** [comment]
Your use case is very reasonable, but it is not possible to do in Tracy. This is a design decision. First of all, memory allocations are not tracked internally, explicitly to avoid having to use an allocator when a new memory buffer is needed. This makes it impossible to release (or reuse) the memory used by old frames. Second, there is no reference counting for strings, etc., so even if the old frame data would be removed, the referenced source location data, its strings, or the messages issued would still be stored in memory. Then there are various other things that depend on the data set not being removed from, e.g. the histogram in find zone menu has special optimizations for not having to rescan everything anew when new zones are added.

> for a long time (read: 5-15 minutes) 

I wouldn't say this is long. Tracy was designed with such timespans in mind.
