### ISSUE TITLE
(Windows) Tracy can not resolve symbols from renamed dlls

### ISSUE THREAD

**Issue by Lectem** [wolfpld/tracy#293]
The project I'm working on has `vst3` modules loaded which are in fact simply `.dll`s with another extension. This seems to cause issues with the way tracy resolves symbols, which I find surprising since Visual Studio and Pix are resolving those correctly.

I'm assuming that somehow the `.pdb` is not loaded by DbgHelp even though the module does have the information.

Note that `dumpbin mymodule.vst3 /PDBPATH` does tell me it can find the pdb file `File Type: DLL PDB file found at 'D:\folder\mymodule.pdb'`.

Any pointers at what code would need to changed/fixed would be helpful.

**Comment by wolfpld** [comment]
Tracy uses the standard dbghelp.dll interface, i.e.:

```c++
SymInitialize( GetCurrentProcess(), nullptr, true );
SymSetOptions( SYMOPT_LOAD_LINES );
...
SymFromAddr( proc, ptr, nullptr, si );
```

There is no filtering done by Tracy, as it doesn't even know what dlls are loaded. This is completely handled on the dbghelp.dll side.

**Comment by Lectem** [comment]
Thanks, it helped me find the related code!
It seems the issue is that the module is loaded after tracy is initialized, so it has nothing to do with the fact it has been renamed.

I fixed it by adding `SymLoadModuleEx(proc, NULL, name, NULL, (DWORD64)info.lpBaseOfDll, info.SizeOfImage, NULL, 0)` to `GetModuleName` in `TracyCallstack.cpp` when a new module is discovered.

Would it be something worth opening a PR for ?

**Comment by wolfpld** [comment]
> Would it be something worth opening a PR for ?

Yes, please do.
