### ISSUE TITLE
Potential typo in CMakeLists.txt

### ISSUE THREAD

**Issue by Krzmbrzl** [wolfpld/tracy#298]
https://github.com/wolfpld/tracy/blob/a13b04669839e45a2ed5ed33abac787b71eb0414/CMakeLists.txt#L45

Note that here the option is prefixed with `TRACE_` whereas all other options seem to be prefixed with `TRACY_`. Is this intended or is this a typo?

**Comment by wolfpld** [comment]
Certainly looks like a typo. @lukasberbuer ?

**Comment by lukasberbuer** [comment]
Yes, it's a typo. Thanks for fixing it!

**Comment by Krzmbrzl** [comment]
No problem :)

PR at https://github.com/wolfpld/tracy/pull/302
