### ISSUE TITLE
Tracy does not connect to TestCpu example application

### ISSUE THREAD

**Issue by egorodet** [wolfpld/tracy#3]
I've built Tracy profiler and TestCpu app from examples `v0.6.3` for Windows x64 with VS2019 (see [binaries here](https://github.com/egorodet/Tracy/releases/download/v0.6.3/Tracy_Win64_v0.6.3.zip), note that TestCpu was modified to render 100 frames to work a little longer on my machine) and tried some testing with the folowing steps:
1. Start Tracy.exe
2. Start TestCpu.exe
3. Press `Connect` button in Tracy app with default address `127.0.0.1`=> message `Waiting for connection` is displayed forever.

I've tried this test even with disabled firewall and antivirus with same result. Network monitor does not show any ports open by TestCpu app. What I'm doing wrong? Could you also describe how Tracy initializes its connection wihtout any additional function calls just with `TestClient.cpp` added to the target application build?

**Comment by wolfpld** [comment]
I cannot reproduce this on my side, i.e. I can successfully profile with the binaries you provided. The steps you list are correct.

> Could you also describe how Tracy initializes its connection wihtout any additional function calls just with TestClient.cpp added to the target application build?

See 3.3 and 3.8 in http://team.pld-linux.org/~wolf/techdoc.pdf

**Comment by egorodet** [comment]
Thank you! Seems the connection problem on my machine was caused by antivirus (Kaspersky Internet Security and particularly by its firewall). Everything started working fine when I fully shut it down.
