### ISSUE TITLE
Allow show zone time in frames to use total time instead of self time

### ISSUE THREAD

**Issue by nico-abram** [wolfpld/tracy#30]
I briefly checked the manual and the UI and couldn't find this. I'm referring to this button: https://i.imgur.com/TUDlV72.png

I tried using the Self Time mark for the histogram but that wasn't it.

I think this could be useful for a zone that results in rare spikes in frames but which has very little self time, and for which the time is spread in many smaller zones (or which has different high latency zones in it in different frames)

**Comment by wolfpld** [comment]
Should be fixed.
