### ISSUE TITLE
Callstacks require version 6.2 of dbghelp.dll

### ISSUE THREAD

**Issue by stgatilov** [wolfpld/tracy#301]
Implementation of call stacks on Windows uses functions from dbghelp.dll. The following functions require at least version 6.2 of dbghelp.dll:
```
                          6E SymGetLineFromInlineContext
                          32 SymAddrIncludeInlineTrace
                          B1 SymQueryInlineTrace
                          5C SymFromInlineContext
```
However, fresh Windows 7 only has version 6.1 preinstalled. Hence, an application statically linked with Tracy client won't boot on such environment.

It has become a problem for us, because we want to ship the same release build that we use for development, and we don't install any redistributable packages (or similar stuff from Microsoft) on players' machines.

I wonder if there is a simple way to disable callstacks at compile time?
It seems that `#define TRACY_HAS_CALLSTACK 0` should do the trick, although we'll have to patch Tracy header for it.

**Comment by wolfpld** [comment]
For reference, dbghelp 6.2 was released 18 years ago (https://documentation.help/DbgHelp/dbghelp_versions.htm).

> It seems that `#define TRACY_HAS_CALLSTACK 0` should do the trick

You would need to have this macro undefined. You may run into some (easily fixable) issues if you do so.

**Comment by stgatilov** [comment]
Windows 7 was released later, but still has only version 6.1.
Since installing Debugging Tools for Windows on user's machine is hardly possible, I guess the choice for those who use dbghelp.dll is either to distribute a local copy of the dll or to use the one provided by OS.

I added `#undef TRACY_HAS_CALLSTACK` at the end of *TracyCallstack.h*, and everything seems to work.
The build is successful, the executable does not import the mentioned symbols, and Tracy profiler works properly too.
We can use this approach until Windows 7 usage dies out.

**Comment by Lectem** [comment]
I'm a bit surprised that you are having issues since the following symbols are loaded dynamically and shouldn't be in the import table even though we're linking against the system version of the library(thus 6.2) .
Looking at the `TracyClient.dll` I generate, those are the only symbols required. 
![image](https://user-images.githubusercontent.com/6024225/146733732-12e72965-85f8-4858-a8ad-e39bd2c73563.png)

Do you perhaps disable those options ? 
![image](https://user-images.githubusercontent.com/6024225/146733876-dfdf3715-6ae0-4432-aaf7-8c1fdebdeddd.png)

I think you should be using at least `/OPT:REF`, even just for performance and binary size.

**Comment by stgatilov** [comment]
> I'm a bit surprised that you are having issues since the following symbols are loaded dynamically and shouldn't be in the import table even though we're linking against the system version of the library(thus 6.2) . Looking at the `TracyClient.dll` I generate, those are the only symbols required. 
> I think you should be using at least `/OPT:REF`, even just for performance and binary size.

I see that method `Profiler::HandleServerQuery` uses `Profiler::SendCallstackFrame`, which uses `DecodeCallstackPtr`, which uses `SymQueryInlineTrace`. Tracking users of `SpawnWorkerThreads` ends at `StartupProfiler`, which is used under `TRACY_MANUAL_LIFETIME`. If you don't define `TRACY_MANUAL_LIFETIME` and don't use callstacks, then you can probably avoid this issue.

Anyway, we do use callstacks when we analyze memory leaks on developer machines. Undefining `TRACY_HAS_CALLSTACK` disables callstacks at compile time, which is a perfect solution, just a bit unofficial.

**Comment by Lectem** [comment]
> I see that method `Profiler::HandleServerQuery` uses `Profiler::SendCallstackFrame`, which uses `DecodeCallstackPtr`, which uses `SymQueryInlineTrace`.

It is indeed using it here (https://github.com/wolfpld/tracy/blob/master/client/TracyCallstack.cpp#L445) but note it is called `_SymQueryInlineTrace` and not `SymQueryInlineTrace`. 
The symbol is loaded dynamically (if available) here : https://github.com/wolfpld/tracy/blob/master/client/TracyCallstack.cpp#L107.

So there are not explicit references to the function in the import library, and thus the function should not be imported by your executable. Using `/OPT:REF` should be enough to deal with it. Are you perhaps using and old version of tracy, previous to this commit fde62b4e6e66bf0c2e31d257531f85a49a428fd4 which introduced this dynamic loading and `TRACY_NO_CALLSTACK_INLINES` ?

**Comment by stgatilov** [comment]
Yes, we are using version 0.7.8.

**Comment by wolfpld** [comment]
@stgatilov does the problem persist with 0.8.0?

**Comment by stgatilov** [comment]
I upgraded Tracy to 0.8.1 and built new binaries. 

The players which could not run previous builds on Win7 **can now do it**.
So yes, the issue is properly fixed.
