### ISSUE TITLE
Incremental build is not working.

### ISSUE THREAD

**Issue by mcourteaux** [wolfpld/tracy#305]
I had the problem that Tracy didn't compile anymore, as the `tracy_xxh3.h` header is gone from the `server/` folder.

However, it seemed that deleting the `obj/` folder and doing a full recompile fixed it. I checked the manual and I didn't find such an instruction. I'm not used to incremental builds not working.

**Comment by wolfpld** [comment]
CI says otherwise. You will have to be a little more specific.

**Comment by mcourteaux** [comment]
Heh. I elegantly refactored my initial issue :P

**Comment by wolfpld** [comment]
This is caused by stale dependencies (`.d` files). You can workaround with `make clean`.

**Comment by mcourteaux** [comment]
Yeah, I'm not used to manual Makefile systems. I always use CMake and there, that's not needed. If you think this is normal, we can close this. However, a warning in the manual would be cool :)
