### ISSUE TITLE
Can't compile with newer gcc

### ISSUE THREAD

**Issue by Makogan** [wolfpld/tracy#320]
I am trying to build tracy's capture tool by running `make release -j4` and I am getting this error:

`lto1: fatal error: bytecode stream in file ‘obj/release/o/o/o/../../../zstd/common/debug.o’ generated with LTO version 11.2 instead of the expected 9.4`

I a little confused as to why binaries are being generated with the wrong gcc version.

**Comment by wolfpld** [comment]
It seems like you might have forgotten to do `make clean` to clear objects created with the previous version of the compiler. Regardless, this is not a Tracy problem.
