### ISSUE TITLE
Exporting Plot data

### ISSUE THREAD

**Issue by tmayoff** [wolfpld/tracy#322]
Is there a way to export the plotted data to csv, or a different mechanism by which I can save custom data with tracy that would allow me to export it.

**Comment by wolfpld** [comment]
You could try expanding `csvexport` utility.

**Comment by TroyNeubauer** [comment]
Would you be interesting in reviewing a PR that implements this?
Being able to export plot data would be enormously useful for my use case.

I could implement something pretty quickly, just looks like adding a cli flag, calling `Worker::GetPlots()`, and adding some business logic in `csvexport.cpp`

**Comment by wolfpld** [comment]
Go ahead.
