### ISSUE TITLE
Statistics window flame graph view

### ISSUE THREAD

**Issue by zdenyhraz** [wolfpld/tracy#323]
I am new to Tracy and I already fell in love with it, great work! I am using it to profile some of my personal multithreaded scientific calculations. 

Is there a way to see a "flame graph" representation of a function? For example, my function is called from many threads many times during a capture, in a simple parallel for loop, like this:
![image](https://github.com/zdenyhraz/shenanigans/blob/master/data/readme/tracy.png?raw=true)

Right now, I can select one specific function call and see how long its children take to execute, and also the histogram of execution times. That is great, but can I also somehow see some overall average statistics of all the function calls of this function? Something like the "Statistics" box, which already sums up all the function calls, combined with the "Time distribution" box, but with functions stacked on top of each other graphically in form of a flame graph, to see which function is called by what. I think this would be a great feature - not to only inspect function calls individually, but also more generally.

Or possibly I can already get the same/similar function info in some other way which I did not yet realize?

**Comment by wolfpld** [comment]
A very rudimentary flame graph is now available on master.

**Comment by mrimvo** [comment]
Thank you for this great tool in general and especially the flame graph. Without zooming/scoping on the selected time frame, sadly it's currently quite limited and hard to make use of.

Also I noticed ImGui's patches won't apply anymore on the latest master, and for that reason won't compile.
