### ISSUE TITLE
Build Tracy on visual studio

### ISSUE THREAD

**Issue by nirgivon** [wolfpld/tracy#329]
Hi,
This project is absolutely AMAZING!

I am using a windows machine, and would very much like to run this project on Visual studio.

Do you have any instructions on how to bring the project to Visual Studio?

Thanks!

**Comment by glm-ypinczon** [comment]
hey there,
I was doing the same steps a few days ago, and found that everything is really well explained and easy to follow in the documentation (https://github.com/wolfpld/tracy/releases/latest/download/tracy.pdf), look for the part 2.3.1.1 
Best.

**Comment by nirgivon** [comment]
Thanks!
Works like a charm

**Comment by nirgivon** [comment]
Thanks!

Works like a charm :-)
