### ISSUE TITLE
Tracy captures pdb even if it doesn't use them

### ISSUE THREAD

**Issue by BrychDaneel** [wolfpld/tracy#331]
Hi, we use Tracy On Demand in our project. And we don't use ***S macroses (such as ZoneScopedS), because we have enough information even without them.
But Tracy still capture PDB files on application initialization (it holds file handles). We can't move/delete/override this files while application is running.
Sometimes it cause problems. Especially because somehow dbghelp capture PDB from original *.exe location. For example if we compile application on disk D: and then move binaries to disk E: for tests, application copy from disk E: locks pdb on disk D:.

Temporary we've undefined TRACY_HAS_CALLSTACK macros by modification in Tracy code.

But could there be more elegant solution for this? Can we call tracy::InitCallstack lazy? Or maybe just some macros that disables callstacks totaly?

**Comment by wolfpld** [comment]
With e2b0268d7 you can now define `TRACY_NO_CALLSTACK`.

**Comment by BrychDaneel** [comment]
Good, thank you. We will use it.
