### ISSUE TITLE
Tracy assertion failed when running the target program

### ISSUE THREAD

**Issue by graslany** [wolfpld/tracy#336]
Hello,

I'm trying to integrate Tracy into an existing application. Since I have no zones defined yet, I tried to get data from the automated stack trace sampler. If I read the manual correctly, this is done by adding Tracy.hpp to my sources, building my program, and running it as root (since the stack trace collection requires being root). Then I would select "Connect" on the Tracy server (which I also built) to get data from my instrumented program.

These steps worked mostly, however the program is crashing within its first second of execution. The console log contains this:

```
(... usual stuff from the program startup ...)
Program: /.../tracy/client/TracySysTrace.cpp:1281: void tracy::SysTraceWorker(void*): Assertion `sel >= 0 || activeNum == 0' failed.
Aborted (core dumped)
```

The application is a Qt-based graphical application, and it's UI is displayed for a fraction of a second, which lets me think that the failure does not happen right from the start. I have included Tracy.hpp in one of my source files, but I have not used any Tracy macro (such as ZoneScoped) yet.

Can you please share with me your ideas about the cause of this behaviour? The Tracy version is the current master (it reports itself as Tracy 0.7.15).

**Comment by wolfpld** [comment]
I am unable to reproduce this. However, please see the following conversation:

```
[21:13] Mach: I've run into the assert in SysTraceWorker here:
https://github.com/wolfpld/tracy/blob/master/client/TracySysTrace.cpp#L1281 (assert( sel >= 0 || activeNum == 0 );)
Any ideas what causes this? Wondering if it's a bug with the new perf_event_open implementation of parsing context switch events (nice change btw - this should be much more efficient than ftrace) 
[21:15] wolfpld: it is much more efficient
[21:26] Mach: Indeed. I've implemented this parsing before (though I was able to freeze the buffer, which made it easier), and it is quite efficient (though error prone to implement). Is there anything I could provide that may be helpful here? Values of sel or activeNum, kernel versions, anything else? 
[21:29] wolfpld: if you can repro, then it would be best if you could debug the issue
[21:30] wolfpld: the logic is rather simple, until there are ring buffers with content in them ('active'), one has to be selected for processing (sel != -1)
[21:32] wolfpld: hm, if if in 1257 is never entered, but you enter the if in 1270, you can get this to happen
[21:32] wolfpld: it would be interesting to see what kind of perf records you are getting there
```

If I can see what is happening there on an affected system, I should be able to fix this.

**Comment by graslany** [comment]
I am not working on the same machine today, and the one I am using currently does not produce the failure. I'll be able to give the first machine a new try by next week and I will try to attach a gdb to get some insights on the program state.

**Comment by wolfpld** [comment]
In a case reported in #369 the additional event is 2, which is `PERF_TYPE_TRACEPOINT`.

**Comment by wolfpld** [comment]
Or maybe `PERF_RECORD_LOST`, which seems more appropriate.

**Comment by wolfpld** [comment]
2240fd3b0cb112729c63293e1d0c2fdc6fbd76a2 fixes the original issue. d99024dd02944f0d5ec7b41b7ee30b97ce71aa84 further increases the processing thread priority. 5437185858c827b645636de44905c6905af8c442 reduces sleep time after buffers are processed.
