### ISSUE TITLE
Assert in TracyStringHelpers.hpp crashes the client

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#338]
I'm experiencing a crash right now because of this assert: https://github.com/wolfpld/tracy/blob/90d8762c33663e9e2612d270f4f096678a0bde47/client/TracyStringHelpers.hpp#L32
with various values for sz and src. The callstack looks like this on crash:

![grafik](https://user-images.githubusercontent.com/10748498/157126743-28dfad0c-ee30-4fde-9361-ef3fec0a2234.png)

This started appearing a couple of days ago after I implemented an unrelated debug allocator that reserves 10TiB of address space, so I suspect the change in run time memory layout might have surfaced this bug. It happens both on 0.7.8 and current master. I'm running tracy with `TRACY_ENABLE`, `TRACY_ON_DEMAND` and `TRACY_DELAYED_INIT` on Windows 10.

The crash happens reliably when I click connect in the profiler before my application starts. The crash doesn't happen if I wait a couple of seconds before connecting.

I can debug further into this and share results if you let me know what you need.

**Comment by wolfpld** [comment]
This is in a call to `CopyStringFast( si->Name, si->NameLen )`, where the `si` contents are provided by `SymFromAddr()`. It does not make much sense, as the function must set both values consistently.

Are you (or any of your libraries) doing anything dbghelp related? If so, a proper locking mechanism is needed. Lack of thereof would explain why the application crashes in certain conditions, but not in other.

**Comment by simonvanbernem** [comment]
I'm using Stackwalker to get callstacks, I guess that might use dbghelp.dll? Also having problems reproducing it now, after waking the laptop from sleep :/

I remember though that the main thread seemed to either be in msvc's debug malloc implementation (I have _CRTDBG_MAP_ALLOC defined, which adds additional info, maybe also callstacks?) or stackwalker when the crashes happen.

**Comment by simonvanbernem** [comment]
Just found this in Stackwalker:
```
// Because this class is in no case multi-threading-enabled (because of the limitations
// of dbghelp.dll) it is "safe" to use a static-variable
```

Soooooo I guess there is no way for tracy alone to fix this then? I'd have to implement a locking mechanism for stackwalker in combination with tracy.

**Comment by wolfpld** [comment]
> maybe you could provide a locking mechanism in tracy that makes it easy to hook into

3.11.1.2 in the manual.

**Comment by simonvanbernem** [comment]
Using the locking worked like a charm! I have one question though: In the implementation example for TRACY_DBGHELP_LOCK, the init function creates a mutex. Since tracy calls that function, I guess my application shouldn't call it, because then the first mutex might get overwritten by however calls last. To my understanding, that leads to a racecondition though, if using tracy on demand and delayed init (thereby having the possibility of a late call to the lock init function):

If my application is inside a dbghelp.dll call while tracy creates the mutex, then tracy can lock the mutex right away and end up inside dbghelp.dll aswell, and then bad things could happen. So I guess I should create the mutex manually before any call to tracy happens and then just have the init function be empty, so that tracy and my application are guaranteed to always agree on what the mutex is?

**Comment by wolfpld** [comment]
You can force initialization to be performed only once with proper use of atomics, e.g.: `RpInitDone` in https://github.com/wolfpld/tracy/blob/master/client/TracyAlloc.cpp. This way it does not matter where the mutex is initialized.

I believe similar functionality is also exposed through `InitOnceExecuteOnce()` / `pthread_once()` / `std::call_once()`.

**Comment by simonvanbernem** [comment]
I'll look into that. Thanks for all the help, I'm gonna close this issue now.

Btw, by looking into the way tracy collects callstacks, I'm now actually able to completely remove Stackwalker: I was gathering callstacks to track allocations and use that information when encountering an access violation to help debugging. Stackwalker only provides you a string, so it did the entire dbghelp stuff on every allocation, even though the string is only needed in the error case. I was able to move to saving only the pointers on allocation with CaptureStackBackTrace, and then do the conversion to string only when the error was hit, speeding up my debug allocations by 100x. Looking at TracyCallstack.cpp was super helpful!
