### ISSUE TITLE
Any easy steps to compile it on ubuntu?

### ISSUE THREAD

**Issue by AquariusPower** [wolfpld/tracy#34]
after extracting this zip
and also installing `libtbb-dev`
I did `cd profiler/build/unix/;make`
but no matter what version I use from 0.6 to 0.6.3 it always fails
as `tbb` was not even mentioned on the manual .pdf, and it let me compile more than before, now I feel lost...
has anyone compiled on ubuntu 18.04?

**Comment by wolfpld** [comment]
What is the exact problem you are having? I can't do anything without an error log.

**Comment by AquariusPower** [comment]
@wolfpld I am trying to track it, I found my tbb is 2017 and should be at least 2018, PPA has 2020 tbb I need to install it first. 
```
/usr/include/c++/9/pstl/parallel_backend_tbb.h:28:2: error: #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.
   28 | #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.
```
I will try to fix/compile til I find no more clues, then I post more log here, thx!

**Comment by wolfpld** [comment]
Well, the error is pretty self-explanatory. Both the STL implementation and TBB should be provided by your distribution and work together.

**Comment by AquariusPower** [comment]
Yup,
but I got this now (I am using tracy 0.6.3 sources):
```
g++ -c  -I../../../imgui -I../../libs/gl3w  -g3 -Wall -msse4.1  -std=c++17 -DDEBUG -DTRACY_FILESELECTOR -DTRACY_EXTENDED_FONT -DTRACY_ROOT_WINDOW -DIMGUI_IMPL_OPENGL_LOADER_GL3W ../../src/imgui_freetype.cpp -o obj/debug/o/o/o/../../src/imgui_freetype.o
../../src/imgui_freetype.cpp:28:10: fatal error: ft2build.h: No such file or directory
   28 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
```
despite I have installed `sudo apt install libfreetype6-dev` 
and the .h is present on the system at `/usr/include/freetype2/ft2build.h` (from `dpkg -L libfreetype6-dev` list and `ls` "-rw-r--r-- 1 root root 2383 Apr 13  2018 /usr/include/freetype2/ft2build.h")

I dont know if it is some wrong configuration on my OS,
or if the tracy Makefile config should have let that file be found but didn't?

**Comment by wolfpld** [comment]
You probably need to install `pkg-config`.

**Comment by AquariusPower** [comment]
> You probably need to install `pkg-config`.

I have it installed:
0.29.1-0ubuntu2

I found only a mention about it on the pdf, but not a command line showing how to use it.

**Comment by wolfpld** [comment]
You don't use it manually, it is used by the makefile.

```
INCLUDES := $(shell pkg-config --cflags glfw3 freetype2 capstone) -I../../../imgui -I../../libs/gl3w
```

This will add the required includes and libs.

```
% pkg-config --cflags freetype2
-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
```

This is missing in the `g++` invocation you have pasted above.

**Comment by AquariusPower** [comment]
sure, also it seems I should let `build.mk` be run in some way to let that file configure it for me, I will search how to use it.

**Comment by AquariusPower** [comment]
now it is just a my notebook hardware graphics driver problem that doesnt seem to support required OpenGL version (and may never as my hardware is too old) or something like that...
So, it compiled properly, thx! I will try to run it on my desktop.
