### ISSUE TITLE
Getting Tracy to show only requested information

### ISSUE THREAD

**Issue by jcelerier** [wolfpld/tracy#343]
Hi, 

I am trying to find all the options that would allow me to only visualize things for the zones I am interested in: 

- How to see only the thread I'm interested in ? 
- How to see only the content of the zones marked
e.g. if I have the following program:

foo.cpp
```
void run(double& x) {
   ZoneScoped;
   x = std::sin(x);
}
```

main.cpp
```
int main()
{
   double x = ...; 
   while(the app runs) 
   {
      run(x);
      FrameMark;
   }
}
```

I really don't want to see anything other that the main -> run callstack, for both sampling and instrumentation and not anything which may happen "around"

Is there a reference of what I can do to achieve that (without having to change things in the tracy GUI, only through the client)?

Thanks !

**Comment by hobyst** [comment]
It seems that this is a side effect of system calls detection getting fixed. I also came across this happening to me after upgrading to `v0.8` and after tinkering with the settings, disabling the automated data collection (explained in section 3.14 of the Tracy manual) using the `TRACY_NO_SYSTEM_TRACING` define on both Tracy and any code that links to it did the trick and now only the functions and scopes I specifically instrumented get registered into the traces.

In the project I'm working on implements Tracy using CMake so I was able to get around it with this:
```cmake
add_library(tracy STATIC tracy/TracyClient.cpp)
target_compile_definitions(tracy PUBLIC TRACY_NO_SYSTEM_TRACING)
```
If you prefer to define in source code you can do it so like with the rest of boolean Tracy macros:
```cpp
#define TRACY_NO_SYSTEM_TRACING
```
On a compiler level or Makefile you would need to add the define for all the source code of your project or add the define as an argument on every compiler code:
```makefile
CXXFLAGS += -DTRACY_NO_SYSTEM_TRACING
```

**Comment by wolfpld** [comment]
> If you prefer to define in source code you can do it so like with the rest of boolean Tracy macros:
> 
> ```c++
> #define TRACY_NO_SYSTEM_TRACING
> ```

These macros *must not* be defined on a per-file basis.
