### ISSUE TITLE
Exception thrown in rpmalloc_finalize when starting/stopping tracing multiple times during lifetime of the process

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#351]
If I make the following call sequence:

tracy::StartupProfiler();
ZoneScoped
tracy::ShutdownProfiler();
tracy::StartupProfiler();
ZoneScoped
tracy::ShutdownProfiler();

Am seeing a consistent crash in rpmalloc_finalize on the second shutdown:
```
TRACY_API void ShutdownProfiler()
{
    s_profilerData->~ProfilerData();
    tracy_free( s_profilerData );
    s_profilerData = nullptr;
    rpmalloc_finalize();
}
```

specifically [if ((heap->spans_reserved)](url) is pointing to what looks like a corrupted address:

```
//! Finalize the allocator
TRACY_API void
rpmalloc_finalize(void) {
	atomic_thread_fence_acquire();

	rpmalloc_thread_finalize();
	//rpmalloc_dump_statistics(stderr);

	//Free all thread caches
	for (size_t list_idx = 0; list_idx < HEAP_ARRAY_SIZE; ++list_idx) {
		heap_t* heap = (heap_t*)atomic_load_ptr(&_memory_heaps[list_idx]);
		while (heap) {
			if (heap->spans_reserved) { // <-- crash here, drops into CrashFilter
				span_t* span = _memory_map_spans(heap, heap->spans_reserved);
				_memory_unmap_span(span);
			}
```

Current defines (Windows 64bit env):
```
"-DTRACY_DELAYED_INIT",
"-DTRACY_ENABLE",
"-DTRACY_MANUAL_LIFETIME",
"-DTRACY_NO_FRAME_IMAGE",
"-DTRACY_ON_DEMAND",
```

Tracy is being built as its own dll.

Is it expected that Tracy cannot be startup/shutdown multiple times during the process lifetime?

**Comment by wolfpld** [comment]
> Is it expected that Tracy cannot be startup/shutdown multiple times during the process lifetime?

It is meant to be working, but I don't use or test this scenario.

**Comment by robertblaketaylor** [comment]
Testing out a few cases with the change you mention applied to rpmalloc_thread_initialize:

```
//! Initialize thread, assign heap
TRACY_API void
rpmalloc_thread_initialize(void) {
	if (!get_thread_heap_raw()) {
		heap_t* heap = _memory_allocate_heap();
		if (heap) {
			const int32_t heap_size = sizeof(heap_t);
			memset(heap, 0, heap_size);
			atomic_thread_fence_acquire();
#if ENABLE_STATISTICS
			atomic_incr32(&_memory_active_heaps);
#endif
			set_thread_heap(heap);
#if defined(_MSC_VER) && !defined(__clang__) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
			FlsSetValue(fls_key, heap);
#endif
		}
	}
}
```

Any concerns or thoughts?

**Comment by robertblaketaylor** [comment]
It looks like a bug in how rpmalloc is integrated when enabling manual lifetime. Highlights:
 - There is only one call to rpmalloc_initialize at the start of the process (even when in manual lifetime)
 - At rpmalloc_initialize a call is made to rpmalloc_initialize_config
 - The call to rpmalloc_initialize_config resets the pointers in the static _memory_heaps member to nullptr and the _memory_heap_id
  - Per thread initialization occurs and index 1 and 2 in the _memory_heaps contains the thread local data (in my case)
  - At the call to shutdown profiler, rpmalloc_finalize is called, which releases the per thread memory but doesn't reset the _memory_heaps or the _memory_heap_id
  - Now on the next startup, rpmalloc is in the uninitialized state, but no initialization occurs
  - The threads then pick up indexes 3 and 4 and the per thread heap ends up with the same addresses as the first pass
  - When shutting down now _memory_heaps contains a the same address twice (at index 1/3, and 2/4) where the contents of index 3/4 are no longer valid because they were purged in the loop in the previous iterations.

**Comment by robertblaketaylor** [comment]
Would you be willing to add this test case to your tests?

**Comment by wolfpld** [comment]
I do not have any automated tests suite, so this would not be practical.

Your changes look sound, but you should consult them with @avoroshilov, the original author of the manual lifetime code path.

Crash handler should be disabled during profiler destruction. Is this not working for you?

https://github.com/wolfpld/tracy/blob/3d28d1259b240f5094364b5ecda3c261f375443e/client/TracyProfiler.cpp#L1454

**Comment by robertblaketaylor** [comment]
It looks like it is not getting disabled in 0.7.8 however I pulled in 0.8.0 which looks to fix both the crash handler not getting disabled and rpmalloc management. The change to init the rpmalloc plumbing ensures the data is reset now between manual runs.
