### ISSUE TITLE
SIGSEV : Thread local heap is never re-initialized after shutdown

### ISSUE THREAD

**Issue by robertblaketaylor** [wolfpld/tracy#357]
Tracy 0.8.0 - RPThreadInitDone doesn't look to be getting set back to false after thread exit for the worker, compress, and symbol threads when using manual lifetime. Added small bit of code here to mark the thread init false when the thread heap is finalized:

// TracyThread.hpp
```
extern thread_local bool RpThreadInitDone;

class ThreadExitHandler
{
public:
    ~ThreadExitHandler()
    {
#ifdef TRACY_MANUAL_LIFETIME
        rpmalloc_thread_finalize();
        RpThreadInitDone = false;
#endif
    }
};
```

**Comment by wolfpld** [comment]
Please provide a PR.

**Comment by robertblaketaylor** [comment]
done: https://github.com/wolfpld/tracy/pull/359
