### ISSUE TITLE
Q: Small documentation misunderstanding.

### ISSUE THREAD

**Issue by Dandielo** [wolfpld/tracy#358]
Hey! First of all thanks for the great tool!

I've lately seen your support for fibers, and wanted to incorporate them into my project, so I took to the docs.
Where there is a specific line:
> To enable fiber support in the client code, you will need to add the TRACY_FIBERS define to your project.
You need to do this explicitly, as there is a small performance hit due to additional processing.

I've just done that, precompiled the library _(using conan as a package manager)_ and started some test, until I noticed that adding that specific define results in lots of instrumentation errors.

After some digging, I found that the compiled library might be slightly different when also using the `TRACY_FIBERS` define: [client/TracyProfiler.cpp(2741)](https://github.com/wolfpld/tracy/blob/ee4f4f491fad90109039a1fb43afc634292206f8/client/TracyProfiler.cpp#L2741)

If that's the case, would it make sense to explicitly add information that both the library and the client project need to be compiled with that define?

Cheers!

**Comment by wolfpld** [comment]
Added in a763991a.

**Comment by Dandielo** [comment]
Thanks!
