### ISSUE TITLE
Support for Start/Close of a Zone

### ISSUE THREAD

**Issue by ApfelkuchenHaus** [wolfpld/tracy#37]
Hi,

Looking at the Zone-API all I see is starting of zones and implicit closing at the end of a scope. I would like to have a bit more control of being able say `ZoneStartName(name)` and then a matching `ZoneEndName(name)`.

When profiling larger functions I find it ugly to wrap every subpart in scopes to use it with ZoneNamed and it often just plain is in the way.

**Comment by wolfpld** [comment]
Use the C API.
