### ISSUE TITLE
Importing chrome traces crashes

### ISSUE THREAD

**Issue by kvark** [wolfpld/tracy#372]
Just trying out the importer built from latest code on Linux, and it's not going far:
```bash
~/Code/tracy/import-chrome/build/unix/import-chrome-release something.json something.tracy
terminate called after throwing an instance of 'nlohmann::detail::type_error'
   what():  [json.exception.type_error.302] type must be number, but is string Aborted (core dumped)
```

**Comment by wolfpld** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by kvark** [comment]
@wolfpld can you be specific about what you would like to see in this bug?
I provided the invocation, the rough revision reference, and the output of the tool.
I can't provide the traces themselves, unfortunately.

**Comment by wolfpld** [comment]
The printed error is originating from an external parsing library and doesn't mean anything in particular which would be actionable. Without an example of failing input there's not much that can be done here. You do not need to provide a whole trace, a single failing line would be enough.

**Comment by kvark** [comment]
Reduced input causing this error:
```js
    [
        {
            "name": "thread_name",
            "ph": "M",
            "pid": "simd_A",
            "tid": 4493,
            "args":
            {
                "name": "simd"
            }
        }
    ]
```

**Comment by wolfpld** [comment]
Well, the `pid` value is obviously invalid, as it is a string, and not a number. See https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

> **pid**: The process ID for the process that output this event.

**Comment by kvark** [comment]
That makes sense. Thank you for your time looking into this!
