### ISSUE TITLE
Would a thread-agnostic manual lifetime management be possible

### ISSUE THREAD

**Issue by nagisa** [wolfpld/tracy#376]
I have been attempting to integrate `TRACY_MANUAL_LIFETIME`, and have hit a limitation in how the `___tracy_startup_profiler` and ___tracy_shutdown_profiler` functions operate.

Today the implementation of these functions will allocate and deallocate some profiler-specific data using a thread-local rpmalloc instance. As a result it can be quite easy to corrupt the state of these allocators by calling `___tracy_startup_profiler` in one thread and `___tracy_shutdown_profiler` in an another one. In such a situation the rpmalloc instance servicing the allocations and deallocations will be different and the allocator state will end up getting corrupted, leading to a SIGSEGV next time `___tracy_startup_profiler` is attempted again.

This quite naturally isn't a problem in the `!TRACY_MANUAL_LIFETIME` configuration as the initialization and deinitialization will happen before and after main, on the main thread. Working around this isn't terribly difficult in a multi-thread scenario either. One could run a dedicated thread entirely for the purpose of calling `___tracy_startup_profiler` and `___tracy_shutdown_profiler`, for example. But it definitely doesn't feel like the straightforward approach. And so I wonder if that's indeed an intended limitation. If nothing else we should probably have it documented in the manual.

**Comment by wolfpld** [comment]
It feels to me that the problem you describe is ill-defined. I do not understand why a program would want to concurrently be starting and shutting down the profiler. It feels as if the integration was not thought out well and your expectation is that the profiler will somehow magically solve this issue.

The valid solution here is to externally synchronize the startup and shutdown. This is not a Tracy issue.
