### ISSUE TITLE
Set the priority of the capture thread

### ISSUE THREAD

**Issue by rationalcoder** [wolfpld/tracy#386]
I'm trying to upgrade my version of Tracy that I had to customize to work for my old Linux 3.3 ARMv5 platform, and I'm trying to see if the changes I made to my local copy have been addressed in the official repository.

One thing I had to fix was configuring Tracy to only use IPv4, which I see has been added.
The other is the ability to set the priority of the capture thread. Is there a way to do this, yet? If not, I would like something like `tracy::SetCaptureThreadPriority(...)`.

**Comment by wolfpld** [comment]
Why do you need to set capture thread priority?

**Comment by rationalcoder** [comment]
This first part is an explanation that may or may not be relevant, depending on why you are asking this question. I have included it just in case.

In embedded projects that are latency sensitive, certain IO tasks, timer events, etc. are higher priority than others. For example, communication with a DSP has a real deadline, while logging can wait for a bit. One way of handling this is to have one queue that you pull all events off of, and you then prioritize the handling of the events. But what if you want to process high priority events before pulling low priority events off the queue at all? Worse yet, what if a high priority IO event becomes available while you are processing a low priority event?

You can solve some of these problems with interrupts or even CPU affinity, assuming you have multiple/enough cores, but a relatively easy and effective solution to the problem is to have thread-local event queues and thread priorities. If an IO event becomes available on a high priority thread, we can just have the OS swap that thread in and handle the event.

Regardless of your priority scheme, you want your profiler to play nice. For example, I think we currently set Tracy's priority lower than the DSP thread, but higher than everything else. If I remember correctly, before I made the priority change, the capture was slow, and the program would eventually just crash.

Of course, the ultimate, lowest-level API wouldn't even need to spawn threads at all, it would just call you back when it was time to dump data to a file or the network, and user code would call the library when data was ready from the network, but one step at a time.

And if you don't feel like doing this, it's not the end of the world. Adding it was trivial.

**Comment by wolfpld** [comment]
Can you show how you have implemented the thread priority setting function?

**Comment by rationalcoder** [comment]
The version I have is 0.6.3, and I just hacked it in, but what I did was this:
```
class Thread
{
public:
    Thread( void(*func)( void* ptr ), void* ptr )
        : m_func( func )
        , m_ptr( ptr )
    {
#if defined TRACY_THREAD_PRIORITY && defined TRACY_SCHED_POLICY
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        pthread_attr_setinheritsched(&attr, PTHREAD_EXPLICIT_SCHED);
        pthread_attr_setschedpolicy(&attr, TRACY_SCHED_POLICY);

        struct sched_param param = { TRACY_THREAD_PRIORITY };
        pthread_attr_setschedparam(&attr, &param);
        pthread_create( &m_thread, &attr, Launch, this );
#else
        pthread_create( &m_thread, nullptr, Launch, this );
#endif
    }

    ~Thread()
    {
        pthread_join( m_thread, nullptr );
    }

    pthread_t Handle() const { return m_thread; }

private:
    static void* Launch( void* ptr ) { ((Thread*)ptr)->m_func( ((Thread*)ptr)->m_ptr ); return nullptr; }
    void(*m_func)( void* ptr );
    void* m_ptr;
    pthread_t m_thread;
};
```

I didn't need to worry about making an API, so I just added some Linux-specific defines. Changing this to an API that doesn't require defines shouldn't be too hard. Maybe a `tracy::SetThreadPriority(int priority, int policy)` for Linux. You could have an API that exposes the whole `pthread_attr_t`, if you wanted to be a little more complete, although I doubt anyone would need anything other than the policy and priority in practice.

**Comment by wolfpld** [comment]
Having an Linux-only implementation is no go. Even worse would be exposing platform-specific structs like `pthread_attr_t`. Tracy is multi-platform. This aside, I was more interested in how you have (or would have) plumbed the code to actually issue these priority setting calls.

**Comment by rationalcoder** [comment]
I agree with you about the thread name. I just didn't know if that information was available. I would have to familiarize myself with Tracy's threading situation to come to a solid conclusion about some of this. For example, if Tracy uses TLS, which I imagine it does, we can support an API to get any relevant information from within the hook, and just pass the thread handle as a parameter.

I will get back to you if/when I get this done. For now, it's low priority since I can hack what I need into Tracy pretty easily, but if anyone else is reading this and wants this feature, comment below (or add it yourself).

**Comment by wolfpld** [comment]
All threads just call `SetThreadName()` shortly after spawning. This can be macroized to dispatch to thread naming func *or* thread naming func and prio setting hook.

**Comment by wolfpld** [comment]
Closing, as there is currently nothing to do here.

**Comment by rationalcoder** [comment]
Yeah. I started work on it (and got the thread priorities set to what I wanted them to be), but I noticed that I couldn't port later versions of Tracy to our platform anyway (it has something to do with changes in the threading situation, but I wasn't able to debug it). We are rolling our own instead. Maybe Tracy uses spinlocks or something (which don't work in general on single core systems with thread priorities)? Anyway, it's not the biggest deal.

**Comment by wolfpld** [comment]
> Maybe Tracy uses spinlocks or something (which don't work in general on single core systems with thread priorities)?

https://github.com/wolfpld/tracy/blob/c0035a492f2af2f6ceb435b2f824e1cc43e1e00f/public/client/TracyProfiler.cpp#L1927-L1930

You can try changing this to `s_symbolThread->~Thread();`, which will wait until the thread can be joined. This will, however, not work when the crash handler fires, as it freezes the symbol thread, making it impossible to join. Or you could perhaps try some other way of synchronization, maybe a semaphore, or a condition variable?
