### ISSUE TITLE
No file dialog under Linux with Tracy v0.8.1

### ISSUE THREAD

**Issue by Elias011980** [wolfpld/tracy#387]
Greetings,

How comes that we cannot any more get a file dialog under Linux, for distributions without xdg-desktop-portal ?

Could we please get back a GTK+ file dialog, or at least a compile option to use it like it was in former versions ?

**Comment by wolfpld** [comment]
No. KDE users do not want to see GTK dialogs.

**Comment by Elias011980** [comment]
Just make it an option !

There are not only KDE users around, and, again xdg-desktop-portal is NOT available in all distributions !

**Comment by wolfpld** [comment]
Thank you for your input. If you wish to push this futher, feel free to prepare a PR.

**Comment by Elias011980** [comment]
I am unfamiliar with pull requests, sorry...

Here is a patch I made and which allows to choose what file selector to use under Linux when compiling the profiler (sorry, github does not work properly with my browser, and refuse to attach a file):

diff -durN tracy/profiler/build/unix/build.mk tracy-patched/profiler/build/unix/build.mk
--- tracy/profiler/build/unix/build.mk	2022-04-21 19:28:07.000000000 +0200
+++ tracy-patched/profiler/build/unix/build.mk	2022-05-06 23:57:47.451211112 +0200
@@ -27,9 +27,9 @@
 		SRC3 += ../../../nfd/nfd_cocoa.m
 		LIBS +=  -framework CoreFoundation -framework AppKit
 	else
-		SRC += ../../../nfd/nfd_portal.cpp
-		INCLUDES += $(shell pkg-config --cflags dbus-1)
-		LIBS += $(shell pkg-config --libs dbus-1)
+		SRC += ../../../nfd/nfd_gtk.cpp
+		INCLUDES += $(shell pkg-config --cflags gtk+-3.0)
+		LIBS += $(shell pkg-config --libs gtk+-3.0)
 	endif
 endif
 
An alternative would be to use https://github.com/aiekick/ImGuiFileDialog which would provide an uniform file selector for all OSes, and reduce the number of dependencies...

**Comment by Elias011980** [comment]
Another attempt at quoting the patch:
```
diff -durN tracy/profiler/build/unix/build.mk tracy-patched/profiler/build/unix/build.mk
--- tracy/profiler/build/unix/build.mk	2022-04-21 19:28:07.000000000 +0200
+++ tracy-patched/profiler/build/unix/build.mk	2022-05-09 21:21:03.704918866 +0200
@@ -27,9 +27,15 @@
 		SRC3 += ../../../nfd/nfd_cocoa.m
 		LIBS +=  -framework CoreFoundation -framework AppKit
 	else
-		SRC += ../../../nfd/nfd_portal.cpp
-		INCLUDES += $(shell pkg-config --cflags dbus-1)
-		LIBS += $(shell pkg-config --libs dbus-1)
+		ifdef TRACY_GTK_FILESELECTOR
+			SRC += ../../../nfd/nfd_gtk.cpp
+			INCLUDES += $(shell pkg-config --cflags gtk+-3.0)
+			LIBS += $(shell pkg-config --libs gtk+-3.0)
+		else
+			SRC += ../../../nfd/nfd_portal.cpp
+			INCLUDES += $(shell pkg-config --cflags dbus-1)
+			LIBS += $(shell pkg-config --libs dbus-1)
+		endif
 	endif
 endif
 
```

**Comment by wolfpld** [comment]
Applied in 4347b5c9.
