### ISSUE TITLE
Why is TracySystem.cpp compiled even when profiling is disabled

### ISSUE THREAD

**Issue by W4RH4WK** [wolfpld/tracy#388]
After trying Tracy for the first time I came across commit e7c582b and was wondering why this change was introduced.

Without it, some build system setups might be simpler, as we only have to worry about setting (or not setting) `TRACY_ENABLE`. With the change, assuming we want to stick with the easy path of just using `TracyClient.cpp`, we have do conditionally include the source file depending on whether the platform is supported.

This is more of a question than a request for change.

**Comment by wolfpld** [comment]
Thread naming, which is useful outside of profiling, e.g. during debugging.
