### ISSUE TITLE
Networking and unreal?

### ISSUE THREAD

**Issue by juaxix** [wolfpld/tracy#391]
Hello, I wonder if there is a way to track the network ,similarly to what Unreal Engine do with their [networking insights](https://docs.unrealengine.com/4.27/en-US/TestingAndOptimization/PerformanceAndProfiling/UnrealInsights/NetworkingInsights/).
Also , how easy could be to inject the general STAT info from Unreal to tracy?
Thanks!

**Comment by wolfpld** [comment]
Networking would be generally non-trivial to profile mainly due to distance between generating some data and actually transmitting it over a network in whatever encapsulated or compressed form you can imagine.

**Comment by juaxix** [comment]
I mean, we could add traces from game clients and game server to an instance of tracy, with packets that those instances send and receive?

**Comment by wolfpld** [comment]
The problem is complex and I don't see a simple solution. If you do, please provide a PR.
