### ISSUE TITLE
Console application freezes when used with ZoneScoped

### ISSUE THREAD

**Issue by afalahat** [wolfpld/tracy#393]
I am new to Tracy and I have fallen in love with what it can do. I am learning it through the following simple example:

```
#include "Tracy.hpp"

int main() {

    ZoneScoped;

    int N = 15;
    for (long i = 0; i < N; i++)
        for (long j = 0; j < N; j++)
            for (long k = 0; k < N; k++)
            {
                //ZoneScopedN("InnerLOOP");
                printf("%d, %d, %d\n", i, j, k);
            }
    return 0;
}
```

The program freezes on on `i`, `j`, `k` = 6, 4, 10. If I comment out `ZoneScoped`, the Profiler GUI nicely shows the CPU usage in real-time and the program ends peacefully, which tells me Tracy setup is probably correctly done. I am using Tracy in Visual Studio 2019 along with the Tracy GUI tool. I'd appreciate any help as I really like the library.

**Comment by wolfpld** [comment]
Please provide a complete project, including the required build files, which is failing for you.

**Comment by afalahat** [comment]
Please kindly find the file at the following link. I have compressed the solution folder. Thank you very much,
[Project2.zip](https://github.com/wolfpld/tracy/files/8711650/Project2.zip)

**Comment by afalahat** [comment]
I have compressed the folder containing the solution folder in the link below. Thank you very much for your time and help.
[Project2.zip](https://github.com/wolfpld/tracy/files/8711716/Project2.zip)

**Comment by afalahat** [comment]
Please let me know if the zip file worked for you.

**Comment by wolfpld** [comment]
I have checked the project you have provided and everything is in order, as seen below.

![Clipboard01](https://user-images.githubusercontent.com/600573/169355216-e25d987c-53d4-4841-b0af-7de1e4e1ec42.png)

The only things that may be different here are:
- MSVC version (I use 2022), which should not matter.
- The profiler version. I have checked this on current master.
- Your system setup, or hardware, which may have unknown impact on things.

**Comment by afalahat** [comment]
Thank you for checking this for me.
If you were to check, what would it be the first thing if the system setup or hardware was different? I am using a standard Windows 10 Lenovo laptop with Intel Core i9 and 64GB memory. I tried to find the system configuration in the user's manual but did not find anything.

**Comment by wolfpld** [comment]
Nothing springs to mind. It should just be working.

**Comment by afalahat** [comment]
Sorry to keep posting here, I used 
```
vcpkg install --triplet x64-windows-static freetype glfw3 capstone
```

to install the dependencies on my Windows 10 machine, and they were successfully installed and integrated to my Visual Studio 2019.

**Comment by wolfpld** [comment]
Cannot reproduce.
