### ISSUE TITLE
Guidance to reduce impact of tracy profiling on application

### ISSUE THREAD

**Issue by tjtaill** [wolfpld/tracy#397]
Just wanted to say thanks for your really cool project not many instrumenting profilers that works on macos yours is the only one I am aware of and I looked at a couple. 

I am having an issue where tracy seems to impact based on the number of ZoneNamedNCS I create. Disabling them with the boolean active as shown in the manual doesn't seem to reduce their impact either. Reducing the stack depth helps a little but nearly as much as reducing the number of functions I create zones for.

Is there any guidance you can give to reduce the impact of these zones on my application seems to almost have my average performance metric iterations per second. I notice the resolution says 6 ns might be 10 ns realistic could I reduce that ? Would it even help ?

Troy

**Comment by wolfpld** [comment]
Are you compiling with optimization enabled?

**Comment by tjtaill** [comment]
Yes compiling in release -03
with flags

set(PROFILE_COMPILE_FLAGS -g;-fno-omit-frame-pointer;-fno-optimize-sibling-calls)
set(PROFILE_LINK_FLAG -rdynamic)

**Comment by tjtaill** [comment]
So I only put zones in my critical path and at the leaf nodes (deepest) functions this allows me to get better call stacks with fewer zones.

Now when I deactivate zones and reduce depth it does make a difference going from ~40 iterations per second to ~50. I will try to to look at the disassembly of the zone creations and see if I am doing something wrong. Thanks for replying.

**Comment by tjtaill** [comment]
Well thanks a lot I am going to close this issue now
