### ISSUE TITLE
Actively notify the user about slow symbol resolution when having inline frame resolution on windows enabled

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#399]
I used tracy for at least 2 years now and always experienced it as taking a long time to catch up with what my program was doing. When running with elevated priveleges and sampling enabled, this would become so bad that I literally had to sleep my main thread for minutes to have tracy catch up with symbol resolution, to be able to gather any useful data before the main thread terminated.

I recently figured out that this was because of slow inline frame resolution, as is mentioned in section 3.11.1.3 of the manual.

This technically is a user error (just read the manual...), but I believe that in this case it is really not obvious that the manual will have useful information, or that this even is something unusual (if you only know it that way), so it would be great if the profiler could bring peoples attention to this issue when it happens during profiling. That way, a lot of people who probably just think of tracy as being kinda janky and slow, but aren't bothered enough to comb through the manual, would have a better time with it.

It would certainly have helped me identifying this issue a lot sooner.

I suppose to add a notification icon (similar to the "Samling data and ghost zones may be displayed wrongly..."-icon in the the titlebar) that pops up when inline symbol resolution is a bottleneck (based on the info in the manual, this case should be decently easy to detect with a programmatic heuristic in the client) and gives further information when hovered on how to avoid this (using the TRACY_NO_CALLSTACK_INLINES define).

**Comment by wolfpld** [comment]
Implemented in edad2d7e and 0624c592.
