### ISSUE TITLE
Tracy profiler release build crashes on MacOS

### ISSUE THREAD

**Issue by egorodet** [wolfpld/tracy#4]
When I build `Tracy/profiler` on MacOS 10.15.4 with `make release` the result executable crashes on start `./Tracy-release`. While debug executable built with `make debug` starts normally. I compared debug and release compilation flags and root caused it down to flag `-fomit-frame-pointer`. When this flag is removed `Tracy-release` starts normally on MacOS.

**Comment by wolfpld** [comment]
Interesting. Fix pushed.
