### ISSUE TITLE
Call stacks are not collected on MacOS 12.4

### ISSUE THREAD

**Issue by atticus5** [wolfpld/tracy#406]
-- The C compiler identification is **AppleClang 13.1.6.13160021**

<img width="668" alt="Screenshot 2022-06-08 at 16 53 20" src="https://user-images.githubusercontent.com/28069262/172634575-d6b06717-b29f-4dc9-b1cb-7d39f10e95f0.png">

I'm also using `dsymutil` to extract the debug symbols.
The `lldb` debugger is able to retrieve call stack information.

The only way I managed to get it working was to add the following lines in my main function, before everything else:

        while (i < 30)
        {
                TracyCZoneS(Main, 3, TRACY_ENABLE)
                SDL_Delay(200);
                TracyCZoneEnd(Main);
                i++;
                TracyCFrameMark()
        }

For some reason this kicks the call stack collection:

<img width="597" alt="Screenshot 2022-06-08 at 17 04 02" src="https://user-images.githubusercontent.com/28069262/172636909-5a89e472-e43a-4999-831d-4d4b2c5f08e7.png">

**Comment by wolfpld** [comment]
The only way I can reproduce this is by having outdated `dsymutil` symbols. Otherwise can't repro.

**Comment by graducan** [comment]
Unfortunately, it's not the case on my side, I double checked. I will take some time in the next days to debug on tracy's source code.

**Comment by graducan** [comment]
I checked the stack from the memory tab on alloc btw

**Comment by wolfpld** [comment]
The example you have provided is not self-contained.

**Comment by AntoineConffx** [comment]
I can confirm I have the same issue as well, even with the Test app (without any modifications).
Memory allocations only show the symbol and not the function line in the stack trace. 

Also on 12.4

**Comment by helloellite** [comment]
Same issue. Finally I found the solution in tracy_user_manual.pdf: 
`On iOS you will have to add a New Run Script Phase to your XCode project, which shall execute the
following shell script:
cp -rf ${TARGET_BUILD_DIR}/${WRAPPER_NAME}.dSYM/* ${TARGET_BUILD_DIR}/${
UNLOCALIZED_RESOURCES_FOLDER_PATH}/${PRODUCT_NAME}.dSYM`
