### ISSUE TITLE
code unreachable warning on Windows, prevents build in strict mode

### ISSUE THREAD

**Issue by beqjanus** [wolfpld/tracy#407]
There check for Invariant TSC in TracyProfiler.cpp has no way to reach the return(False) when the ifdef (see below) is True
`
static bool CheckHardwareSupportsInvariantTSC()
{
    const char* noCheck = GetEnvVar( "TRACY_NO_INVARIANT_CHECK" );
    if( noCheck && noCheck[0] == '1' ) return true;

    uint32_t regs[4];
    CpuId( regs, 1 );
    if( !( regs[3] & ( 1 << 4 ) ) )
    {
#if !defined TRACY_TIMER_QPC && !defined TRACY_TIMER_FALLBACK
        InitFailure( "CPU doesn't support RDTSC instruction." );
#endif
        return false;
    }
    CpuId( regs, 0x80000007 );
    if( regs[3] & ( 1 << 8 ) ) return true;

    return false;
}
`

Simple fix (#else), I'll see if I can create a PR

**Comment by wolfpld** [comment]
Fixed by above.
