### ISSUE TITLE
Running install_vcpkg_dependencies.bat seems to no longer work

### ISSUE THREAD

**Issue by laurelkeys** [wolfpld/tracy#409]
Running `vcpkg\install_vcpkg_dependencies.bat`, as in the manual's "Local installation within the project directory", on a fresh clone of [tracy (0b2e276)](https://github.com/wolfpld/tracy/commit/0b2e276dd2d96b475b38c737a7fc29bc74eaad67) results in the following error:
```
Error: In manifest mode, `vcpkg install` does not support individual package arguments.
To install additional packages, edit vcpkg.json and then run `vcpkg install` without any package arguments.
See https://github.com/Microsoft/vcpkg/tree/master/docs/users/manifests.md for more information.
Using manifest file at C:\Users\laurel\dev\tmp\tracy\vcpkg.json.
```
After locally reverting the merge of https://github.com/wolfpld/tracy/pull/365 it worked flawlessly:
```
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows-static -> 1.0.9#2
  * bzip2[core]:x64-windows-static -> 1.0.8#2
    capstone[arm,arm64,core,x86]:x64-windows-static -> 5.0.0-rc2#1
    freetype[brotli,bzip2,core,png,zlib]:x64-windows-static -> 2.12.1
    glfw3[core]:x64-windows-static -> 3.3.7
  * libpng[core]:x64-windows-static -> 1.6.37#17
  * vcpkg-cmake[core]:x64-windows -> 2022-05-10#1
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * zlib[core]:x64-windows-static -> 1.2.12#1
...
```

**Comment by wolfpld** [comment]
@theblackunknown can you take a look?

**Comment by theblackunknown** [comment]
Sure, I'll take a look this week !

**Comment by theblackunknown** [comment]
I have opened #412 to investigate and resolve this issue.
#365 introduced vcpkg manifest mode, which required both to no list which dependencies to install a `VCPKG_ROOT` environment variable to exists in `vcpkg\install_vcpkg_dependencies.bat`.

Please have a look at the PR description and give it a test to confirm I have resolved this issue.

**Comment by laurelkeys** [comment]
> Please have a look at the PR description and give it a test to confirm I have resolved this issue.

I've just cloned and tested the PR branch and it worked correctly, ty!

One minor note on `vcpkg/install_vcpkg_dependencies.bat`: its first line (`@echo off`) was commented out. Not sure if this was intended or only used for testing.

**Comment by theblackunknown** [comment]
Good catch ! It is a leftover from testing, I'll submit a new commit to fix this when I'll be back on my computer.
