### ISSUE TITLE
Statistics Time Range not rendering when using a left-docked statistics window and resizing the main view

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#417]
It's kinda hard to describe, so I made a video of it:
https://user-images.githubusercontent.com/10748498/176272141-154028c2-9870-4a49-99cf-4470b1408955.mp4

Basically, the statistics time range is not rendered when the statistics window is docked to the left, and the timeline-window goes below a certain width. I've had a similar bug (wasn't able to repro) where in the same setup two limits that should fully cover the timeline-window did not cover the entire width, but a fraction of it, depending on how big the statistics window was.

If the statistics window isn't docked and I reduce the width of the Tracy Windows-window to the width that caused trouble before, this doesn't happen. So it seems to be an interaction with docking.

I am on Tracy v0.8.0, but haven't found any mention of a fix in the patch notes, so I guess this is still an existing bug in 0.8.2:

**Comment by wolfpld** [comment]
Fixed in dd6933fe.
