### ISSUE TITLE
Need a way to cleanly shutdown instantly when profiler is connected.

### ISSUE THREAD

**Issue by aardappel** [wolfpld/tracy#419]
I am passing `___tracy_source_location_data` structs to tracy that are valid for the entire duration my game is running, but are not valid anymore once the game starts its cleanup process (they are dynamically allocated by necessity). I thus need a way to tell the client to stop sending/accessing data and immediately stop.

`tracy::GetProfiler().RequestShutdown()` doesn't work because it is not instant, and ends up accessing structs that have already been deallocated.

`tracy::GetProfiler().~Profiler();` is a hack, but it could be expected to work if the destructor was written to work cleanly on an already destructed object, and it seems it is not.

Right now I just have to `abort()` if `tracy::GetProfiler().IsConnected()` is true, but would prefer a cleaner solution.

**Comment by wolfpld** [comment]
The clean solution is to leak memory. Anything you pass to the profiler has to abide by the contract. In this case the contract is that you no longer control the lifetime of what you have passed as a parameter.

**Comment by aardappel** [comment]
That solution went through my head, but leaking exactly all the strings it refers to is not simple, so was hoping for something better.

I know I am "breaking the contract", but requiring 100% static data is a bit inflexible. In my case this is part of a programming language where I can't statically know all symbols ahead of time, but at least I can allocate them at program start so that all `___tracy_source_location_data` instances can be allocated just once. I could have used the version that copies all the strings, but that is excessively inefficient and unnecessary.

It wouldn't hurt to have a function that kills all threads/connections/buffers synchronously? Or make the destructor work correctly when everything has already been set to null? That would expand tracy's use cases to "allocated at startup" data.

**Comment by wolfpld** [comment]
You say that calling `~Profiler()` would be a viable option for you, if it would work (which it won't, because that would be undefined behavior, 12.4.15). How is it different from calling `RequestShutdown()` and then waiting for `HasShutdownFinished()`?

**Comment by aardappel** [comment]
I tried:

```
            tracy::GetProfiler().RequestShutdown();
            while (!tracy::GetProfiler().HasShutdownFinished()) {
                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
```

Then when I quit the game, it is just stuck indefinitely. Disconnecting or quitting the profiler does not change that either. It's looping in:

```
    // Wait for symbols thread to terminate. Symbol resolution will continue in this thread.
#ifdef TRACY_HAS_CALLSTACK
    while( s_symbolThreadGone.load() == false ) { YieldThread(); }
#endif
```

**Comment by aardappel** [comment]
Any idea why the above doesn't work?

**Comment by wolfpld** [comment]
`s_symbolThreadGone` is probably set in a wrong place (after joining the thread in profiler dtor). May as well be done on exit from the symbol worker thread.

**Comment by aardappel** [comment]
That sounds good.. are you going to make that change?

**Comment by wolfpld** [comment]
0fc1c0f9
