### ISSUE TITLE
enable iOS call stack causes crash in tracy_rpmalloc.cpp

### ISSUE THREAD

**Issue by jordo** [wolfpld/tracy#42]
Trying to enable ios Call stack, but consistently getting EXC_BAD_ACCESS IN tracy_rpmalloc.cpp.

Followed everything in #25 and the callstack is only 2 frames.  Thoughts?

<img width="438" alt="Screen Shot 2020-06-08 at 9 34 20 PM" src="https://user-images.githubusercontent.com/323868/84103280-d2e88680-a9cf-11ea-8e74-568604cba7f8.png">

**Comment by wolfpld** [comment]
Looks like another instance of https://github.com/mjansson/rpmalloc/issues/165

**Comment by wolfpld** [comment]
Please verify if the problem still persists with commit 0744355a.

**Comment by jordo** [comment]
just confirming problem doesn't persist after 0744355
