### ISSUE TITLE
Github CI can't run client code (Windows)

### ISSUE THREAD

**Issue by aardappel** [wolfpld/tracy#420]
Trying to run an exe built with tracy client code linked in gets me:

```
Tracy Profiler initialization failure: CPU doesn't support invariant TSC.
Define TRACY_NO_INVARIANT_CHECK=1 to ignore this error, *if you know what you are doing*.
Alternatively you may rebuild the application with the TRACY_TIMER_QPC or TRACY_TIMER_FALLBACK define to use lower resolution timer.
```

I guess this is a VM issue?

Either way:

a) It is not obvious from that error you want an environment variable, not a #define.
b) Doing something like `echo "TRACY_NO_INVARIANT_CHECK=1" >> $env:GITHUB_ENV` doesn't seem to fix the problem, maybe there is a better way?
c) I am using `TRACY_ON_DEMAND`, if some of these init checks could be moved to after a connection is established, that could work too.

Not sure if I'm the first to run into this problem, but a lot of projects use GitHub CI, so working well with it seems useful.

**Comment by wolfpld** [comment]
> a) It is not obvious from that error you want an environment variable, not a #define.
> b) Doing something like `echo "TRACY_NO_INVARIANT_CHECK=1" >> $env:GITHUB_ENV` doesn't seem to fix the problem, maybe there is a better way?

The message is explicitly asking to take action only if you know what you are doing, and is giving you an alternative, if you don't.

> Not sure if I'm the first to run into this problem, but a lot of projects use GitHub CI, so working well with it seems useful.

I agree, but I do not control how GitHub VMs are configured.

**Comment by aardappel** [comment]
Ok, I guess I'll maintain a `return true;` fork on my end then.
