### ISSUE TITLE
'PERF_FLAG_FD_CLOEXEC' was not declared in this scope

### ISSUE THREAD

**Issue by fbunn** [wolfpld/tracy#423]
Hi there,

I've run into this error because PERF_FLAG_FD_CLOEXEC wasn't defined when trying to compile Tracy into a C++ under Ubuntu Linux.

Is this because of the Linux version I'm using?

uname -a 
===> Linux 1512a4c6cf06 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 

Any suggestions?

Here's the output from my Cmake/gcc compilation attempt...

In file included from /source/tracy/TracyClient.cpp:23:0:
/source/tracy/client/TracyProfiler.cpp: In function 'void ___tracy_startup_profiler()':
/source/tracy/client/TracyProfiler.cpp:4262:5: error: 'StartupProfiler' is not a member of 'tracy'
     tracy::StartupProfiler();
     ^
/source/tracy/client/TracyProfiler.cpp: In function 'void ___tracy_shutdown_profiler()':
/source/tracy/client/TracyProfiler.cpp:4267:5: error: 'ShutdownProfiler' is not a member of 'tracy'
     tracy::ShutdownProfiler();
     ^
In file included from /source/tracy/TracyClient.cpp:26:0:
/source/tracy/client/TracySysTrace.cpp: In function 'void tracy::ProbePreciseIp(perf_event_attr&, long long unsigned int, long long unsigned int, pid_t)':
/source/tracy/client/TracySysTrace.cpp:703:58: error: 'PERF_FLAG_FD_CLOEXEC' was not declared in this scope
         const int fd = perf_event_open( &pe, pid, 0, -1, PERF_FLAG_FD_CLOEXEC );

**Comment by wolfpld** [comment]
This is not related to the currently running kernel. You need to have proper headers available in your system.

`PERF_FLAG_FD_CLOEXEC (since Linux 3.14)`

3.14 was released in 2014. Please seek help with your system vendor.

**Comment by fbunn** [comment]
I forgot to mention something important:

My gcc compiler is running in Docker container.

When you say...  "You need to have proper headers available in your system."

What, specifically, needs to be installed for PERF_FLAG_FD_CLOEXEC  to be defined?

**Is it...**
a) pkg-config needs to be installed?  (apt-get install pkg-config)
b) Linux kernel headers need to be installed?  ( sudo apt install linux-headers-$(uname -r) )
c) Something else?

Thanks!!!!

**Comment by wolfpld** [comment]
You want linux-headers.
