### ISSUE TITLE
Move public header to isolated subfolder

### ISSUE THREAD

**Issue by jdumas** [wolfpld/tracy#425]
Hi. To compile the tracy client into an app, we need to include `Tracy.hpp`, which in turn pulls headers from `common/...` and `client/...`. This means that we need to add the repository root as a header include folder for the client app. But there are a bunch of files in the repo that pollute header include paths for the client app. For example I've had conflicts with `imgui/imgui.h` coming from the tracy repo and my own app.

Can I suggest that we move `client/`, `common/` and `Tracy.hpp` into an isolated `include/` folder that _only_ contains public headers necessary for building the client?

**Comment by wolfpld** [comment]
Fixed in 85102f7.

**Comment by jdumas** [comment]
Amazing! Thanks for adding the `tracy/` subfolder as well! I think you may also need to update this line in the CMake integration:
https://github.com/wolfpld/tracy/blob/d6a607b9f0202ae852a645552037c10c952b8eab/CMakeLists.txt#L10
to add the `public/` subfolder.

**Comment by wolfpld** [comment]
> CMake integration

This (and meson) were left to fix for the interested parties.
