### ISSUE TITLE
__cxa_demangle requires malloc'd memory

### ISSUE THREAD

**Issue by u3shit** [wolfpld/tracy#430]
According to https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a01696.html, __cxa_demangle requires a malloc'd memory, that will be realloc'd, if it's not large enough (and it returns the new address). However here:
https://github.com/wolfpld/tracy/blob/4d40a9cb53d39254065d03bf1680e957851ebc09/public/client/TracyCallstack.cpp#L866
tracy creates a stack buffer and passes this to `__tracy_demangle` below (which in turn calls `__cxa_demangle`), which will crash the application if the symbol name doesn't fit into the allocated storage. (Blame c++ templates, not me!)
Interestingly this only crashes for me when I use libc++abi, maybe gcc's implementation somehow detect this case or it just somehow creates more compact string representation.

For a quick test I tried to create a bigger buffer, but then it failed with `TracyProfiler.cpp:2973: void tracy::Profiler::SendSingleString(const char *, size_t): Assertion `len <= std::numeric_limits<uint16_t>::max()' failed.` but I guess there's little point in storing and displaying demangled names this long, so a simple truncation would suffice too. Too bad __cxa_demangle doesn't work that way.

**Comment by u3shit** [comment]
Here is it, in a file because I don't want to copy-paste a 73K file here:
[demangle.txt](https://github.com/wolfpld/tracy/files/9140309/demangle.txt)

**Comment by wolfpld** [comment]
Should be fixed with 7dc95bf.

**Comment by u3shit** [comment]
It crashes for me. I see two problems with the code:
* `tmp_len` receives the length of the demangled name, not the realloc'd area size. This means this function will realloc every time you try to demangle a function with a longer demangled name after a shorter one.
* if the buffer is relloc'd, you have to store the return value of `__cxa_demangle` back into `tmp_ptr`.

But... if demangle fails, `__cxa_demangle` returns nullptr. However if previously it realloc'd the buffer, your old buffer pointer will become a dangling pointer and it will leak the realloc'd buffer:
https://github.com/llvm/llvm-project/blob/main/libcxxabi/src/cxa_demangle.cpp
To be honest, this might be a bug in libcxxabi, gcc handles this differently:
https://github.com/gcc-mirror/gcc/blob/68871a008e686dbe56ff0b502f2864176a140716/libiberty/cp-demangle.c#L6649
here no matter what you do, it allocates a buffer internally, and just copies it back to your buffer if it fits... But at least it won't leak your buffer and return bullshit buffer sizes.
It's a mess.

**Comment by wolfpld** [comment]
> * `tmp_len` receives the length of the demangled name, not the realloc'd area size.

What a fantastic API! It basically then requires to make an allocation for each demangling attempt. FFS.

Some time ago I have even considered including this function to be a part of Tracy, with some needed improvements. It is not practical to do, however, as the mangling format is in flux, which you can see in the history of the files you have linked, with the additions of modules, lambdas, etc.

Realistically I think I will revert to the original solution, but with a bigger buffer (1 MB should be enough, I think?) and truncation to the data transfer window (64KB).

**Comment by u3shit** [comment]
> `tmp_len` receives the length of the demangled name, not the realloc'd area size.

Actually, after a second look it looks like only libcxxabi does this, the gcc's implementation puts the buffer size there. Not that it helps, especially with android devices where libcxxabi is the default these days.

Yes, unfortunately these days almost any new c++ feature need a new mangling, so they're in a constant change.
A random idea, maybe you could check the mangled name length and if it's larger than some threshold skip the demangling? Unfortunately the length of then mangled and demangled names can vary a lot (especially with backreferences), so it's not perfect, but still could help dealing with some unusually long symbol names without requiring infinite memory for the demangle buffer.

**Comment by wolfpld** [comment]
Either way, the API is hardly usable. At least Vulkan did it right.

The threshold might be a good idea. If it's large enough there should be no impact for function names <64KB.

**Comment by wolfpld** [comment]
Try with a75846dd.

**Comment by u3shit** [comment]
It doesn't crash for me now. However I think the limit in a75846d should be much lower (it's 1MB now, such long mangled name will definitely have a larger demangled name that will still cause reallocations and crashes, and it won't fit into a 64k buffer anyway.)

**Comment by wolfpld** [comment]
Yes, but there is no way to calculate the exact required size, so whatever value would be used would be just guesswork.
