### ISSUE TITLE
MacOS and demangling

### ISSUE THREAD

**Issue by AntoineConffx** [wolfpld/tracy#433]
Hi there,

I've been working on a project where tracy is integrated and we're making it work on macos / iOS. 
There were a few steps that I had to do a bit differently compared to the instructions in the pdf and I have a suggestion that would've saved me quite a bit of debugging if you're open to it.   

### Instructions for setup  
1. Instead of a post build copy script, I use the following build settings   
`DEBUG_INFORMATION_FORMAT = dwarf-with-dsym  
DWARF_DSYM_FOLDER_PATH = $(CONFIGURATION_BUILD_DIR)/$(EXECUTABLE_FOLDER_PATH)  
DWARF_DSYM_FILE_NAME = $(PRODUCT_NAME).dSYM  `

Not setting dwarf-with-dsym means that you have to manually call dsymutil on <AppName>.app/Contents/MacOS/AppName.   The dsym needs to be next the actual binary.   

### Suggestions for ___tracy_demangle function  
So at the moment if a function is not prepended by a _Z then demangle will fail and will return nullptr. Instead I changed it locally to return the actual mangled function name if any of the steps for demangling fails.   
This allows us to have all the function in the call stacks, even if they're mangled. Otherwise I was just looking at a bunch of address thinking that my debug symbols were just missing.   

Local code changes for tracy_demangle:  
  ```

extern "C" const char* ___tracy_demangle( const char* mangled )    
{    
    if( !mangled || mangled[0] != '_' ) return mangled;      
    if( strlen( mangled ) > ___tracy_demangle_buffer_len ) return mangled;      
    int status = -1;      
    size_t len = ___tracy_demangle_buffer_len;      
    const char* toRet = abi::__cxa_demangle( mangled, ___tracy_demangle_buffer, &len, &status );      
    return ((status == 0) ? toRet : mangled);  
}  

```
---> Based on latest master as I wanted to make use of your latest improvements :)

**Comment by wolfpld** [comment]
> Not setting dwarf-with-dsym means that you have to manually call dsymutil on .app/Contents/MacOS/AppName. The dsym needs to be next the actual binary.

Make a PR.

> So at the moment if a function is not prepended by a _Z then demangle will fail and will return nullptr. Instead I changed it locally to return the actual mangled function name if any of the steps for demangling fails.
> This allows us to have all the function in the call stacks, even if they're mangled. Otherwise I was just looking at a bunch of address thinking that my debug symbols were just missing.

I do not understand what would be the point of doing so. All calls to `___tracy_demangle` are using the following pattern:

```c++
const char* demangled = ___tracy_demangle( function );
if( demangled ) function = demangled;
```

So your change is basically a no-op?

**Comment by AntoineConffx** [comment]
For the first thing of dwarf-with-dsym this is meant for client applications and not building actual tracy, so not sure what the PR would be :)  This could be updated instructions for the docs I suppose ?  

For the demangled changes, I'll double check why that resolved it for me and whether or not it might have been something else. 

Thanks for the quick response.

**Comment by wolfpld** [comment]
> This could be updated instructions for the docs I suppose ?

Yes. There are some guidelines there.
