### ISSUE TITLE
Support for dynamic zone names for GPU markers

### ISSUE THREAD

**Issue by Shimmen** [wolfpld/tracy#443]
The `ZoneName(text, size)` function for setting a dynamic string as the name of a zone is very helpful in cases where the name is not a string literal. However, this feature is not available for any of the GPU implementations.

With my current architecture, I only have access to `std::string`s for marker names so it would require some re-architecting of my rendering code to make it work, which isn't something I want to do just to be able to get correctly named debug markers. I don't think that this scenario is too uncommon so adding this could potentially benefit many.

I would be happy to make an attempt to add an implementation for Vulkan, but I can't really go further than that right now. I would also be curious if there are any reasons why it's not added or if it's just a matter of not-yet-added.

Thanks!

**Comment by wolfpld** [comment]
> With my current architecture, I only have access to std::strings for marker names so it would require some re-architecting of my rendering code to make it work, which isn't something I want to do just to be able to get correctly named debug markers. I don't think that this scenario is too uncommon so adding this could potentially benefit many.

You can use transient zones, which store the passed name, so you can use a custom and different std::string for each one. To accomodate this, each zone will produce a new allocation to save the name.

> I would be happy to make an attempt to add an implementation for Vulkan, but I can't really go further than that right now.

The network messages are the same for each gfx API, so this won't be an issue.

> I would also be curious if there are any reasons why it's not added or if it's just a matter of not-yet-added.

It is common for the GPU drivers to produce unreliable timestamp readings. This alone makes push for GPU-related features feel like a wasted effort.

**Comment by Shimmen** [comment]
> You can use transient zones, which store the passed name, so you can use a custom and different std::string for each one. To accomodate this, each zone will produce a new allocation to save the name.

Oh I apologize, I'm not sure how I missed this! This entirely solves my issue, the allocation is not a problem for me here.

> It is common for the GPU drivers to produce unreliable timestamp readings. This alone makes push for GPU-related features feel like a wasted effort.

I am aware, but I think it's still useful to be able to see something in the timeline and especially how it lines up with the CPU work, which isn't so visible in other tools. (In my case though these timings I'm getting have always been very close to what I'm seeing on Nvidia Nsight's "GPU Trace" too, so it definitely can work nicely if you're lucky.)

Thank you for the quick response. As far as I'm concerned you can close this issue as the transient zone fixes this for me.
