### ISSUE TITLE
memory leak of MemData

### ISSUE THREAD

**Issue by helloellite** [wolfpld/tracy#445]
After discard the connection and return to the welcome page, I found the memory usage didn't fallback to the origin.
With the help of debug tools I also found the leak is from Worker.m_data.memory->data, which is a Vector\<MemEvent\>. It seems that destructor of Worker.m_data.memory hasn't been called when Worker destroy. Maybe we should add something like 
`    for (auto& [_, v] : m_data.memNameMap)
        v->~MemData();
`
in Woker's destructor?

**Comment by wolfpld** [comment]
Fixed in d5a46f97.
