### ISSUE TITLE
Detect version of Tracy used

### ISSUE THREAD

**Issue by stgatilov** [wolfpld/tracy#449]
Now that we did a first update of Tracy in our game, there comes a problem that people need to use Tracy Viewer of exactly the same version as the one which the game was built with.

Is there any kind of TRACY_VERSION macro or an API functions that returns the version of library?

**P.S.** I searched for "version" in public headers, have not found anything like that.

**Comment by wolfpld** [comment]
The client and server must have matching network protocol, which is specified in `public/common/TracyProtocol.hpp`. To map protocol versions to releases you can use the table in `server/TracyProtoHistory.cpp`. This is the most reliable way to determine what is actually needed.

The version information is contained in `server/TracyVersion.hpp`.

How would you like to use this information on the client side?

**Comment by stgatilov** [comment]
Ok, I missed it because we don't use server part in the game.
We simply download an executable of TracyViewer from GitHub releases page.

I would say do one of:

1. Move TracyVersion.hpp to common, then I'll use these constants directly.
2. Move TracyProtoHistory to common, then I'll take protocolVersion and find compatible versions.

In principle, I can also adjust the third-party system of the game to automatically generate a header containing version of Tracy.
I just thought that perhaps having this in the library could help other people too?

**Comment by wolfpld** [comment]
be392a76f moves `TracyVersion.hpp` to `common`, which is accessible by clients.

**Comment by stgatilov** [comment]
Yes, that's good for me.
Thank tou!
