### ISSUE TITLE
profiler tool when built as release crashes immediately with a seg fault

### ISSUE THREAD

**Issue by indirectlylit** [wolfpld/tracy#455]
Hi, thank you for providing Tracy! I am just getting started using the tool, but am loving it so far.

This issue is not blocking me, but I thought it might be of interest. Happy to provide more info if helpful.

## Observed behavior

For me, the `profiler` tool when built as `release` crashes immediately with a seg fault:

```
➜  unix git:(a8511d35) ./Tracy-release 
[1]    5572 segmentation fault (core dumped)  ./Tracy-release
```

However when built and run as debug (`./Tracy-debug`) it successfully runs, sees the running instrumented client, and collects data.

## Expected behavior

Running `./Tracy-release` will launch the application

## Context

* Tracy version: 0.8.2
* aarch64
* Ubuntu 18.04.6 LTS
* gcc 7.5.0

**Comment by wolfpld** [comment]
There's not much to be done here without a crash stacktrace.

**Comment by wolfpld** [comment]
What you did should suffice. Rebuild fixing the issue suggests the problem was elsewhere (e.g. stale files from previous builds, etc.)
