### ISSUE TITLE
Crash when loading a trace with only one callstack

### ISSUE THREAD

**Issue by JRBurn777** [wolfpld/tracy#458]
I had an odd situation where the tracy capture only had one unique callstack.

This lead to the following issue when loading the saved trace within "Worker::Worker( FileRead& f, EventType::Type eventMask, bool bgTasks )".

```
    m_data.callstackPayload.push_back( nullptr );
    <jrb-snip>
    m_data.callstackPayload.reserve( sz ); // <jrb> sz == 1, already sized to '1' with "nullptr"
    for( uint64_t i=0; i<sz; i++ )
    {
        <jrb-snip>
        m_data.callstackPayload.push_back_no_space_check( arr ); // <jrb> pushed off the end of allocated vector
```
Debug builds of the profiler confirmed the issue by tripping the following assert within "push_back_no_space_check()".
`        assert( m_size < Capacity() );`

I was able to resolve the issue by resizing to include any preexisting entries as well:
`    m_data.callstackPayload.reserve( m_data.callstackPayload.size() + sz );`

**Comment by JRBurn777** [comment]
It was significant by being a simple power-of-two.
I believe any power-of-two count would cause this issue.

For example, if "sz==2", the internals of TracyVector would round to the nearest power-of-two (which is still '2') and resize to that.
The vector then has 1 element (nullptr at [0]) and a capacity of 2.
When pushing two more elements (sz==2), the first fits (at [1]), then the last push is off the end.

The same would happen for "sz=256". For that, vec.size() would be 1, vec.Capacity() would be 256, and all would fit but the last.

**Comment by wolfpld** [comment]
Should be fixed in 8b75a3fa.

**Comment by JRBurn777** [comment]
Verified that fix works for me as well.

I like the memory efficiency of converting to "reserve_exact()".

Future patches could propagate that conversion to other "TracyVector::reserve" calls in "Worker::Worker( FileRead& f, EventType::Type eventMask, bool bgTasks )", like "m_data.plots.Data().reserve( sz )".

**Comment by JRBurn777** [comment]
Closing issue. Thanks for the quick response.
