### ISSUE TITLE
Question: Is there a way to customize the sampling rate for call stacks?

### ISSUE THREAD

**Issue by nico-abram** [wolfpld/tracy#46]
Did not find anything about it in the manual in chapters 3.13.4 or 5.2.3.3 (A search for " rate" did not yield anything either)

Is there some technical limitation for this on windows, did I just miss it, or is it a nice-to-have possible future feature?

If I'm reading this right (Which I'm likely not to be) https://github.com/wolfpld/tracy/blob/aa7851d1d7d50d098d5829b1fdecc0b3f72ca193/client/TracySysTrace.cpp#L214-L217 it's a hardcoded rate at the moment

**Comment by wolfpld** [comment]
8 kHz is the max sampling rate supported on Windows. What would be the use case to lower it?

**Comment by nico-abram** [comment]
Oh, I did not know it was the maximum. I was thinking of *increasing* it. I'll close this then

**Comment by fsfod** [comment]
You could maybe try using ProfileTotalCycles for the source in TRACE_PROFILE_INTERVAL to get more fine grained sample period.
