### ISSUE TITLE
Proper usage for TracyCZoneCtx ?

### ISSUE THREAD

**Issue by jwdevel** [wolfpld/tracy#461]
I have read the documentation, but I am having trouble getting `TracyCZoneCtx` to work.
I feel I might not understand something basic.

My use case: I have a zone that I would like to span across several frames.
Inside a class, there is some "begin" function that will be called, and later, an "end" function. I want to measure the time between these two functions.

This is essentially how it looks:

```
class MyClass {

    MyClass()
        : m_tracyContext()
    {}

    TracyCZoneCtx m_tracyContext;

    void begin() {
        TracyCZoneN(zone, "MyZone", true);
        m_tracyContext = zone;
    }

    void end() {
        TracyCZoneEnd(m_tracyContext);
    }

}
```

So, on frame 1 we might call `begin()` and on frame 100 call `end()`, and I'd like to see a single big zone in Tracy spanning those frames.

But instead, what I get is:

    Profiling session terminated due to improper instrumentation.
    Reason: Invalid order of zone begin and end events

I added logging to the begin/end functions, and confirmed that they are always called in the proper order — first `begin()`, then `end()`. Further, I confirmed that they are always paired properly.

Is this wrong usage of the C API?
If so, what is the right way to do it?

Aside: I am using 0.7.7, which I realize is a bit out-of-date.

**Comment by wolfpld** [comment]
The usage pattern is correct. The problems are caused by what you are not showing here. You probably just want #426.

**Comment by jwdevel** [comment]
I wonder: could the problem be that there is an enclosing zone, which ends before this inner zone ends?

That is, perhaps it is a requirement that this big frame-spanning zone be a top-level one, not nested inside another?

The actual code has something like this:

```
start() {
    ZoneScoped();  // <- perhaps this is the problem?

    // ... other code

    myclass.begin(); // see original MyClass code
}
end() {

    // ... other code

    myclass.end(); // see original MyClass code
}

//
// Some toplevel code might be like:
//

// frame 1:
start();

// frame 2
// frame 3
// ...
// frame 100:

stop();
```

And if that's the case (which makes some sense to me), then is there a way, using the C api, to say "ignore the current zone stack"?

Aside: if this is the issue, I suggest the error message is a little misleading, since it only mentions the bottom-level zone name and thus makes it seem like that's the culprit, when really it is due to a higher-scope zone ending. But I understand if that's annoying to detect (:

**Comment by wolfpld** [comment]
> I wonder: could the problem be that there is an enclosing zone, which ends before this inner zone ends?

This is exactly the problem.

> And if that's the case (which makes some sense to me), then is there a way, using the C api, to say "ignore the current zone stack"?

No.

**Comment by jwdevel** [comment]
Fair enough (:
