### ISSUE TITLE
Request : Please provide some links to other language bindings.

### ISSUE THREAD

**Issue by xGnoSiSx** [wolfpld/tracy#462]
I wasn't able to find any, and more specifically I'm looking for Java.

Thank you for this great tool!

**Comment by wolfpld** [comment]
Yes, I agree, a list of links to language bindings would be helpful. However, who is to create such a list? Maybe you? Please submit a PR with changes. Thanks.

**Comment by xGnoSiSx** [comment]
I tried to find resources to that effect but came up empty, hence why I opened this request.

**Comment by o-oconnell** [comment]
Haha. Thank you for such an awesome tool. @xGnoSiSx @caspiano, did you find any bindings for java? I'm not sure it would work with the java stack-trace-retrieving APIs that are available.
