### ISSUE TITLE
GCC warning about 'maybe-uninitialized'

### ISSUE THREAD

**Issue by JRBurn777** [wolfpld/tracy#470]
Minor issue when building with warning-as-errors and with TRACY_ON_DEMAND defined.

GCC flagged use of m_connectionId within TracyScoped.hpp with a warning that it may be uninitialized.

With how m_active is used, the uninitialized state of m_connectionId shouldn't matter, but I silenced the warning locally by initializing it to '0' anyways.

In TracyScoped.hpp
```
#ifdef TRACY_ON_DEMAND
    uint64_t m_connectionId = 0;
#endif
```

**Comment by wolfpld** [comment]
Hi, please make a bug report against gcc and their broken static analyser. Better yet, use clang. There is nothing to fix in Tracy here.
