### ISSUE TITLE
Inform user that file dialog is broken

### ISSUE THREAD

**Issue by adamws** [wolfpld/tracy#474]
On some systems, default `nfd_portal` file dialog may not work (https://github.com/wolfpld/tracy/issues/387). Clicking button has no effect, can we get some error message in such scenario? When running `nativefiledialog-extended`'s tests I get:

```
Error: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

Something similar (error popup perhaps) would be nice to have.

**Comment by wolfpld** [comment]
Fixed in 4abb3b5e.
