### ISSUE TITLE
Attribute samples to the instruction before.

### ISSUE THREAD

**Issue by mcourteaux** [wolfpld/tracy#475]
As x86 CPUs actually have their instruction pointer (%rip) to point to the next instruction, all samples are always counterintuitively displayed in Tracy. Let's find a `divss` instruction for example:
![image](https://user-images.githubusercontent.com/845012/193816791-09ee9ed2-d3d7-4395-8e16-20dbc4f8288d.png)

This behavior is consistent for me, everywhere I inspect sampled instructions. I know that simply attributing it to the previous sample is an oversimplification (especially in case of jumps), but might still be intuitive to support doing this as a toggle in the interface.

This has also repercussions on how the samples are attributed to the source code. The mapping between instructions and lines of source is good, but as the attribution of a sample and an instruction is off-by-one, a lot of simple procedural code is hard to interpret results too (when looking in the Source frame).

![image](https://user-images.githubusercontent.com/845012/193818240-e58db667-2842-4153-b358-1af2dd150437.png)
In the picture above, the actual instruction that took long was the `addss` right  above it, which was part of the inlined `squaredNorm()` call at line 1017. Maybe not the most convincing example here, but you get the idea.

**Comment by wolfpld** [comment]
The data is displayed as provided by the operating system. Attributing the cost to a proper instruction is not as simple as just going back one instruction in program memory. If it would be, the operating system would just apply the fix itself.

You may get more accurate results if you switch the displayed cost value from sample count to cycles.

**Comment by wolfpld** [comment]
Here's sample count data for some code:

![obraz](https://user-images.githubusercontent.com/600573/196300519-7ce7119d-1328-4618-a00d-422629452160.png)

And here's the same instructions, but with the hardware cycle count instead:

![obraz](https://user-images.githubusercontent.com/600573/196300663-09953282-d99b-45f5-99d1-cd6a49fec2ee.png)

Unless you can provide a 100% reliable way of determining which samples should be relocated, there's nothing to do here.

**Comment by mcourteaux** [comment]
Wait what? How did you make the second screenshot? Second screenshot looks good! That looks way more true to what the hardware actually spends time on. Hardware cycle count? Where is this option?

**Comment by mcourteaux** [comment]
Aha, okay. On my machine that doesn't influence the results all that much. I guess that's dependent on the CPU design (I have a Ryzen Zen+ CPU).

Sample count:
![image](https://user-images.githubusercontent.com/845012/196654725-d1e61589-4ef3-47b1-8302-eed6d0aff5af.png)

Cycles:
![image](https://user-images.githubusercontent.com/845012/196654818-551b3df2-a4bd-40d5-a23a-749d135fb8b8.png)
