### ISSUE TITLE
Window not redrawn if not focused

### ISSUE THREAD

**Issue by aolo2** [wolfpld/tracy#478]
As far as I understood, there was a recent change from a "game loop" style force redrawing to only redrawing if state got "dirty". 

As of current HEAD keeping the Tracy window open in the background while having another smaller window open in the foreground leaves black trails when the front window is moved.

I guess something like X11 Expose event should mark the state as dirty and cause a redraw. I'm not sure if glfw has a way of getting these events though.

I'll attach a screenshot a bit later.

**Comment by wolfpld** [comment]
Check de319065.

**Comment by aolo2** [comment]
Yep, that's fixed. I never had a chance with the screenshot, did I?
