### ISSUE TITLE
Tracy hangs on exit when launched from command line

### ISSUE THREAD

**Issue by jmrico01** [wolfpld/tracy#479]
I downloaded Tracy 0.8.2 and extracted the executables into a directory `C:\Users\<user>\Documents\Tracy-0.8.2`. I open the Windows command prompt and run `"C:\Users\<user>\Documents\Tracy-0.8.2\Tracy.exe"`. The program runs correctly and everything works. However, when I click the red X to exit, it hangs and doesn't close - I have to forcefully end the process. This also happens if I open the command prompt into `C:\Users\<user>\Documents\Tracy-0.8.2` and run `Tracy.exe` from there.

**EDIT:** Actually, I tried a few times and waited a bit longer, and the process eventually closes. Might just be that it's stuck on some very slow operation, which might be harder to debug. Will try on my other PC later today.

### Machine info
- **Processor:** 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
- **Installed RAM:** 32.0 GB (31.7 GB usable)
- **System type:** 64-bit operating system, x64-based processor
- **Windows Edition:** Windows 10 Enterprise
- **Version:** 21H1
- **OS build:** 19043.2006

**Comment by wolfpld** [comment]
This is not something I can reproduce. A viable way to find what it is would be to make a debug build, then pause the execution of the application during the wait that you see on exit. The debugger will tell what the application is waiting for.
