### ISSUE TITLE
Segmentation fault in SendString

### ISSUE THREAD

**Issue by andrewrk** [wolfpld/tracy#482]
To reproduce the problem, run a Tracy-debug v0.9 and press Connect. Next do these commands:

```
git clone https://github.com/ziglang/zig/
mkdir zig/build
cd zig/build
cmake ..
make install
stage3/bin/zig build -p stage4-tracy -Dskip-install-lib-files -Dtracy=$HOME/Downloads/tracy -Denable-llvm
stage4-tracy/bin/zig build  -Dskip-install-lib-files
thread 722182 panic: Segmentation fault at address 0x2
???:?:?: 0x7fde9fe30699 in ??? (???)
/home/andy/Downloads/tracy/public/client/TracyProfiler.cpp:3340:9: 0x557a6e8 in HandleServerQuery (/home/andy/Downloads/tracy/public/TracyClient.cpp)
        SendString( ptr, (const char*)ptr, QueueType::StringData );
        ^
/home/andy/Downloads/tracy/public/client/TracyProfiler.cpp:1865:30: 0x55781e4 in Worker (/home/andy/Downloads/tracy/public/TracyClient.cpp)
                connActive = HandleServerQuery();
                             ^
/home/andy/Downloads/tracy/public/common/../client/TracyProfiler.hpp:754:63: 0x55b5464 in LaunchWorker (/home/andy/Downloads/tracy/public/TracyClient.cpp)
    static void LaunchWorker( void* ptr ) { ((Profiler*)ptr)->Worker(); }
                                                              ^
/home/andy/Downloads/tracy/public/common/../client/TracyThread.hpp:80:40: 0x55b69ac in Launch (/home/andy/Downloads/tracy/public/TracyClient.cpp)
    static void* Launch( void* ptr ) { ((Thread*)ptr)->m_func( ((Thread*)ptr)->m_ptr ); return nullptr; }
                                       ^
???:?:?: 0x7fde9fd63ff1 in ??? (???)

```

[tracy API bindings used are here](https://github.com/ziglang/zig/blob/0b72965dbf545aa64eb9d9e33defc36af4e2e42c/src/tracy.zig)

**Comment by andrewrk** [comment]
Also debug info is not showing up:

![image](https://user-images.githubusercontent.com/106511/198171415-2c1a3e66-68de-4a4d-9136-4329a09d4856.png)

**Comment by wolfpld** [comment]
The query that is crashing your client may come from the following server-side functions:

![obraz](https://user-images.githubusercontent.com/600573/198247189-b99da2ed-dfaa-48fa-b169-5511b89cf95b.png)

The most likely one is source location handling, which the lack of zone names ("debug info") back ups. But it does not change much, if it isn't.

The way this works is that the client prepares a `QueueSourceLocation` message, which is filled with appropriate data, namely the zone name, its source file, etc. These text strings have unique identifiers, which are then used for id -> string mapping server-side. When the server sees an identifier for the first time, it makes a query to the client to retrieve the matching string, substituting a "???" string for the time being.

The unique identifier is of course the string pointer on client side. There are some words in the manual on how strings passed to Tracy have to be immutable and that they need to be preserved in memory for the whole lifetime of the program. The server does not make any alterations to these string pointers, it just sends back what it received from the client. There is one special case, to not query nullptr strings.

That you are seeing segfault at 0x2 in `SendString` would suggest that this is the `ptr` value that was received from the server, and consequently, this is the value that was somehow generated for the source location on the client. This is most likely an error in way the instrumentation was done.

**Comment by kubkon** [comment]
Thanks for the info @wolfpld, it's been useful in analysing this further. I hooked up Zig's tracy bindings into Zig's standalone linker https://github.com/kubkon/zld (branch with tracy integration: https://github.com/kubkon/zld/tree/tracy-integration) and it crashes in the same place when the linker is built with the default self-hosted compiler (aka stage2), but it works fine without any issues when built using old bootstrap compiler (aka stage1), so this would match with your assertion that the bug is somewhere on Zig side. I will investigate further on the Zig side. Thanks for your help!

**Comment by wolfpld** [comment]
Closing, as it does not seem to be an issue in Tracy. Please reopen with more information, if you think it is not a valid resolution.
