### ISSUE TITLE
Persistent Target FPS

### ISSUE THREAD

**Issue by ilmai** [wolfpld/tracy#486]
I'm working on audio code where the default Target FPS of 60 is way off. With a buffer size of 64 samples at 48000kHz for example, the target FPS is 750. As it is, the Target FPS setting isn't remembered between runs and I need to change it every time, which quickly gets annoying. Would it be possible to make the setting persistent, or allow setting a default?

A good alternative would be a way to set Target FPS programmatically from the code being traced.

**Comment by wolfpld** [comment]
> Would it be possible to make the setting persistent, or allow setting a default?

It is not possible at the moment.

**Comment by wolfpld** [comment]
Added in bd2f903c.
