### ISSUE TITLE
semi-colon after macro causes build problem with Tracy-0.9.0

### ISSUE THREAD

**Issue by DominiquePelle-TomTom** [wolfpld/tracy#493]
Tracy 0.9.0 release notes say:

> Tracy macros now require to be terminated with a semicolon.

Well, that's actually not entirely true.

I see that for the `TracyLockable(...)` macro:
* the semi-colon is indeed needed when building with `-DTRACY_ENABLE` (consistent with release notes)
* but the semi-colon breaks build without `-DTRACY_ENABLE` (bug!)

In my code, I have this:
```
mutable TracyLockable(std::mutex, category_mutex_);
```
It builds fine with `-DTRACY_ENABLE`, but it fails to build in regular build i.e. without `-DTRACY_ENABLE`.
It gives a warning (actually an error in my case because I build with `-Werror`):
```
base_search_engine_nds.hpp:745:46: error: extra ';' inside a class [-Werror,-Wextra-semi]
  TracyLockable(std::mutex, thread_id_mutex_);
                                             ^
1 error generated.
```
And If I remove the trailing semi-colon, then it's the opposite i.e.
it builds fine without `-DTRACY_ENABLE` but fails to build with `-DTRACY_ENABLE`:

```
poi_search_common.hpp:446:53: error: expected ';' at end of declaration list
  mutable TracyLockable(std::mutex, category_mutex_)
                                                    ^
                                                    ;
```
So now with Tracy-0.9.0, neither work:
* a trailing semi-colon breaks regular build (without `-DTRACY_ENABLE`)
* no trailing semi-colon breaks Tracy build (`-DTRACY_ENABLE`)

This patch should fix it (at least it fixes it for me, but I don't use all the Tracy macros,
so maybe I overlook other issues):
```
$ git diff
diff --git a/public/tracy/Tracy.hpp b/public/tracy/Tracy.hpp
index cd7e085d..b7266e26 100644
--- a/public/tracy/Tracy.hpp
+++ b/public/tracy/Tracy.hpp
@@ -37,14 +37,14 @@

 #define FrameImage(x,y,z,w,a)

-#define TracyLockable( type, varname ) type varname;
-#define TracyLockableN( type, varname, desc ) type varname;
-#define TracySharedLockable( type, varname ) type varname;
-#define TracySharedLockableN( type, varname, desc ) type varname;
+#define TracyLockable( type, varname ) type varname
+#define TracyLockableN( type, varname, desc ) type varname
+#define TracySharedLockable( type, varname ) type varname
+#define TracySharedLockableN( type, varname, desc ) type varname
 #define LockableBase( type ) type
 #define SharedLockableBase( type ) type
-#define LockMark(x) (void)x;
-#define LockableName(x,y,z);
+#define LockMark(x) (void)x
+#define LockableName(x,y,z)

 #define TracyPlot(x,y)
 #define TracyPlotConfig(x,y,z,w,a)
```

Ideally, an API breaking change should also have been avoided by introducing a new
macro and deprecating the old one, so upgrading to the newer Tracy would have
been easier.

**Comment by wolfpld** [comment]
Fixed in 89a55a22.
