### ISSUE TITLE
Support interruptable zones

### ISSUE THREAD

**Issue by neobrain** [wolfpld/tracy#5]
Sometimes it's desirable to temporarily interrupt recording of execution time in a zone.

My use case is a scheduler that (among other things) handles control over to worker coroutines. With Tracy's current zone model, the scheduler zone would be a parent of all worker thread zones, but in my concrete use case I would prefer the worker thread zones to appear on the same level as the scheduler zone.

The scheduler code looks vaguely like this:
```cpp
void Scheduler() {
    TracyCZone(SchedulerZone, true);
    while (true) {
        // ...
        // do some work
        // ...

        // invoke next worker
        // Proposed: TracyCZoneInterrupt(SchedulerZone)
        co_await worker_coroutine();
        // Proposed: TracyCZoneResume(SchedulerZone)
    }
}
```
With the current model, the scheduler zone would simply cover 100% of the program's execution time. With support for zone interruption, the profiler could properly display how much time is truly spent in the scheduler itself.

Tracy's internal API seems to already support this but there are no macros that expose this functionality: `TracyCZoneInterrupt` is equivalent to `TracyCZoneEnd`, and TracyCZoneResume is equivalent to `___tracy_emit_zone_begin` (i.e. TracyCZone but without allocating a new context).

**Comment by wolfpld** [comment]
When thinking about API you also need to consider what happens on the server, as there's an implicit state to follow. What you are proposing would require considerable changes in a way zones are stored, which would explode memory usage (e.g. what would happen when you have 500 million zones and add just one byte to zone data structure?). This would be a cost for everyone, to support what seems to be an edge case.

I'd suggest that you simply create a separate zone for each scheduling task, with a parent zone for whole scheduler. This way you can look at the total cost of scheduling tasks either in a list of child zones, or in time distribution list.
