### ISSUE TITLE
Building wasm version, capstone missing

### ISSUE THREAD

**Issue by boomyjee** [wolfpld/tracy#500]
wasm Makefile is referring to
$(HOME)/.emscripten_cache/sysroot/include/capstone
$(HOME)/.emscripten_cache/sysroot/lib/libcapstone.a

how should capstone get into this folder?

**Comment by Kampfkarren** [comment]
I got this working by downloading capstone's next branch, then compiling with `emmake make` + install, then I needed to change a part of the build step to point to where it had installed, since it wasn't in the emscripten cache folder. Hope this helps.

**Comment by ScottTodd** [comment]
I was also able to get this working. Here's what I needed:

1) Clone https://github.com/capstone-engine/capstone and checkout the `next` branch
2) Add `target_compile_options(capstone PUBLIC "-pthread")` to capstone/CMakeLists.txt
    * This fixes `wasm-ld: error: --shared-memory is disallowed by cs.c.o because it was not compiled with 'atomics' or 'bulk-memory' features.` when later building Tracy
3) Configure/build/install capstone: `emcmake cmake -G Ninja -B build/ && cmake --build build/ --target install`
    * This created `${EMSDK}/upstream/emscripten/cache/sysroot/include/capstone/*.h` and `${EMSDK}/upstream/emscripten/cache/sysroot/lib/libcapstone.a`
    * For some reason the `sh.h` header wasn't installed, so I copied that from `capstone/include/capstone/sh.h` to the include dir
4) Edit the capstone paths here to point to my `${EMSDK}` path: https://github.com/wolfpld/tracy/blob/b0174f2f3a53ec8ff376a625eafb64483e619e70/profiler/build/wasm/build.mk#L7-L8
5) Optionally remove `--preload-file embed.tracy` from the same file
6) Build with Tracy `make` (from `tracy/profiler/build/wasm/`)
7) Run the webserver with `python3 httpd.py` and open at `localhost:8000`

**Comment by wolfpld** [comment]
You are not allowed to make TCP connections from within the browser, by design.

**Comment by asymingt** [comment]
That makes sense from a security standpoint. I apologize if this is a very basic question, but then does then mean that a WASM-delivered UI (like https://tracy.nereid.pl) only supports loading traces from file; there is no option to have it bind to a running system?

It looks to me that perhaps the only way to get this working would be to transcode the telemetry to a websocket, and modify the WASM to decode the data from a websocket rather than use raw TCP connections: https://github.com/wolfpld/tracy/issues/477

**Comment by wolfpld** [comment]
Basically, yes.

**Comment by wolfpld** [comment]
This is no longer an issue with the new CMake build system.
