### ISSUE TITLE
Make capstone optional

### ISSUE THREAD

**Issue by Kampfkarren** [wolfpld/tracy#502]
Kind of same issue as #500, where I've done a lot of work installing capstone, putting it in the proper libraries, but I still get mysterious linker errors.

I would just like the ability to not use capstone at all. I am using a tracy wrapper that doesn't support source view to begin with. I've been stubbing out methods and it mostly works, would be nice to have an opt in define to not use capstone.

**Comment by wolfpld** [comment]
Do what you have to do, but it ain't Tracy.

**Comment by Kampfkarren** [comment]
Fair, I was mostly just frustrated. I ended up figuring out how to make this work, I'll write up something for the other folk later.
