### ISSUE TITLE
Assertion failed in Socket::Connect

### ISSUE THREAD

**Issue by vrischmann** [wolfpld/tracy#51]
Hello,

tracy crashes when a client attempts to connect:
```
Tracy-debug: ../../../common/TracySocket.cpp:116: bool tracy::Socket::Connect(const char*, int): Assertion `c == -1' failed.
fish: “./Tracy-debug” terminated by signal SIGABRT (Abort)
```

What I'm doing:
* launching tracy
* launching my client app
* in tracy, clicking either on Connect or on the discovered client

I'm running fedora 32 and using 25c72455660b6790614d85131208d375b2680300

**Comment by wolfpld** [comment]
This shouldn't happen.

> Generally,  connection-based  protocol  sockets  may successfully connect() only once

Can you track what happens in calls to `Connect()`? The flow of code is as follows:

1. `m_ptr` is null. Address info is retrieved, a socket is created and a connection is initiated.
2. Connection is unlikely to be established right away, so transient data is preserved in struct members and the function reports connection failure.
3. On subsequent calls to `Connect()` `m_ptr` holds initial connection data, which is reused to call `connect()` again. These calls should fail (hence the assert) and the `errno` value can be used to determine true connection status.

**Comment by vrischmann** [comment]
Ok so I applied the following diff:
```diff
diff --git a/common/TracySocket.cpp b/common/TracySocket.cpp
index 65874d43..543a1ec8 100644
--- a/common/TracySocket.cpp
+++ b/common/TracySocket.cpp
@@ -110,9 +110,16 @@ bool Socket::Connect( const char* addr, int port )
 {
     assert( !IsValid() );

+    printf("m_ptr: %d\n", m_ptr == NULL ? 0 :1);
+
     if( m_ptr )
     {
         const auto c = connect( m_connSock, m_ptr->ai_addr, m_ptr->ai_addrlen );
+
+        printf("c: %d\n", c);
+        printf("errno: %d\n", errno);
+        perror("connect");
+
         assert( c == -1 );
 #if defined _WIN32 || defined __CYGWIN__
         const auto err = WSAGetLastError();
```

and here is what I got:
```
m_ptr: 0
m_ptr: 1
c: 0
errno: 115
connect: Operation now in progress
Tracy-debug: ../../../common/TracySocket.cpp:123: bool tracy::Socket::Connect(const char*, int): Assertion `c == -1' failed.
fish: “./Tracy-debug” terminated by signal SIGABRT (Abort)
```

**Comment by wolfpld** [comment]
Does f7727f3aa4 work for you?

**Comment by vrischmann** [comment]
Yep, it works fine now. Thanks !
