### ISSUE TITLE
Wrong window size on MacOS

### ISSUE THREAD

**Issue by cBournhonesque** [wolfpld/tracy#513]
Hi,
I just tried using tracy on mac os 13.1 
The application looks great, unfortunately it doesn't resize to my window size. Half of the UI is 'clipped on the right', and I couldn't find a way to make it take the entire window.

This is what I see: (this is my entire screen)
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8112632/213880167-4b195b1a-b150-41b7-a3f3-69841435f281.png">

**Comment by wolfpld** [comment]
See https://bitbucket.org/wolfpld/tracy/issues/42/cannot-scroll-down-capture-on-macos

**Comment by topolarity** [comment]
As a workaround as you can set the environment variable `TRACY_DPI_SCALE=1.0`

Fonts will be blurry and the scrollbar is still missing, but the scaling of the window elements will be improved.

**Comment by maleadt** [comment]
> Fonts will be blurry and the scrollbar is still missing, but the scaling of the window elements will be improved.

With the following patch, I get crisp fonts without having to set `TRACY_DPI_SCALE`:

```patch
diff --git a/profiler/src/main.cpp b/profiler/src/main.cpp
index f967353f..7ef00984 100644
--- a/profiler/src/main.cpp
+++ b/profiler/src/main.cpp
@@ -136,6 +136,11 @@ static void SetupDPIScale( float scale, ImFont*& cb_fixedWidth, ImFont*& cb_bigF
 {
     LoadFonts( scale, cb_fixedWidth, cb_bigFont, cb_smallFont );

+    // macOS HiDPI hack
+    ImGuiIO& io = ImGui::GetIO();
+    io.FontGlobalScale = 1.0f / dpiScale;
+    scale = 1.0f;

     auto& style = ImGui::GetStyle();
     style = ImGuiStyle();
     ImGui::StyleColorsDark();
```
