### ISSUE TITLE
Aggregate statistics for a set of zones

### ISSUE THREAD

**Issue by miki-shapr** [wolfpld/tracy#526]
Hey, new here so sorry if this has been asked previously (looked around but didn't find similar issues 👀)

First of all, Tracy is an awesome tool that's been very useful for us! Thank you! 🚀

Now onto the question: we have a subsystem whose certain methods (not all) are profiled and we are trying to get an aggregate view of said subsystem using the server.

Currently we rely on prefixing each zone in the subsystem with the same string, but on the server this only lets us filter the list of zones, but does not give us an summarized view of the subsystem's statistics.

Is it possible to create aggregate views over a set of zones? If not, is there a better way to do what we are trying to achieve?

Thanks in advance!

**Comment by wolfpld** [comment]
There is no such option.

As a user, how would you like to see the user interface for this to work?

**Comment by miki-shapr** [comment]
We managed to get around this by (re)creating the same subsystem-level zone before each local zone. Thanks for the reply!

**Comment by topolarity** [comment]
I've run into a similar use-case myself, and I don't believe it's totally solved by the workaround suggested above.

Basically, if each Zone were given a name "`<subsystem>.<specific name>`", what I want to do is to be able to see the "self" time spent in all `"<subsystem>.*"` functions, excluding the time spent in other subsystems. This can be helpful to see the time spent between subsystems that interact, and then to drill down on the time spent between the more granular zones.

The above workaround sort of works, but there's no good way to separate out the time spent in one sub-system versus another if they are nested. The best workaround I've found so far is to use Fibers instead.

It would be nice to be able to associate zones with a "detail level" and allowing filtering in the UI/stats based on that level, but that sounds like a fairly intrusive change.
