### ISSUE TITLE
Bad thread ID?

### ISSUE THREAD

**Issue by jacereda** [wolfpld/tracy#527]
Is this code correct? I would expect something similar to the code in the constructor (a call to `GetThreadHandle` when not using fibers).

https://github.com/wolfpld/tracy/blob/fad09a452a74af5ab738bb0693402067d76ab33a/public/tracy/TracyOpenGL.hpp#L311

**Comment by wolfpld** [comment]
What is the problem that you are having?

**Comment by jacereda** [comment]
I'm trying to instrument an OpenGL application that has several threads and some of those threads create OpenGL contexts.

The main context (topmost in the screenshot) seems to work fine, but other contexts seem to collapse lots of GL calls in what appears to be a single very small zone. Sometimes that small zone is just huge. The attached screenshot shows both cases (WorkInterface0 is huge, WorkInterface1 has a small area containing lots of GL calls). The popup window shows absurd data for the zones.

I've tried with the `rdtsc`  and `clock_gettime`, same result.

If you need more information just let me know. 

![Screenshot from 2023-02-16 16-52-00](https://user-images.githubusercontent.com/4195919/219419711-6387181e-1fe1-4aa5-86dd-0aec5d110c21.png)

**Comment by wolfpld** [comment]
Well, yeah, GPU drivers are shit. See #227 for more details in a similar case.

**Comment by jacereda** [comment]
Turns out that wasn't the problem. The contexts were calling `TracyGpuContext` prior to `glXMakeCurrent`, so the time queries creation was failing (all IDs were 0). 

I'd suggest adding an `assert(m_query[0]);` after `glGenQueries` to avoid issues due to silly mistakes.

The reason the first context was fine is that the context created for sharing resources was established as current for the first thread.

Thanks for your support.
