### ISSUE TITLE
[RFC] Adjust the `___tracy_alloc_*` functions to take pointer-size pairs for source/function

### ISSUE THREAD

**Issue by nagisa** [wolfpld/tracy#53]
In section 3.1 of the manual the following snippet can be found:

> ## 3.1 Handling text strings
> When dealing with Tracy macros, you will encounter two ways of providing string data to the profiler. In both cases you should pass const char* pointers, but there are differences in expected life-time of the pointed data.
> 1. When a macro only accepts a pointer (for example: TracyMessageL(text)), the provided string data must be accessible at any time in program execution (this also includes the time after exiting the main function). The string also cannot be changed. This basically means that the only option is to use a string literal (e.g.: TracyMessageL("Hello")).
> 2. If there’s a string pointer with a size parameter (for example: TracyMessage(text, size)), the profiler will allocate an internal temporary buffer to store the data. The pointed-to data is not used afterwards. You should be aware that allocating and copying memory involved in this operation has a small time cost.

While this paragraph is only relevant to macros, I think there is something to be said about extending this concept to at least some of the functions as well.

For instance the signatures for the `___tracy_alloc_srcloc_*` functions are currently these:

```
TRACY_API uint64_t ___tracy_alloc_srcloc( uint32_t line, const char* source, const char* function );
TRACY_API uint64_t ___tracy_alloc_srcloc_name( uint32_t line, const char* source, const char* function, const char* name, size_t nameSz );
````

Note that `name` has an associated size parameter, however `source` and `function` do not. This, in addition to being inconsistent, can also necessitate additional allocations for the API users who don’t have null-terminated strings handy.

If this change were implemented, the users who do deal in 0-terminated strings would end up having to `strlen` them at a call location. However the implementation of this function [`strlen`s the arguments internally _anyway_](https://github.com/wolfpld/tracy/blob/25c72455660b6790614d85131208d375b2680300/client/TracyProfiler.hpp#L486-L487), so the cost of allocating a location would not change for those users, while it would improve, ever so slightly, for those who have the lengths handy.

**Comment by wolfpld** [comment]
The current API is a direct result of how Lua handles these strings.

```c++
    lua_Debug dbg;
    lua_getstack( L, 1, &dbg );
    lua_getinfo( L, "Snl", &dbg );
    size_t nsz;
    const auto name = lua_tolstring( L, 1, &nsz );
    const auto srcloc = Profiler::AllocSourceLocation( dbg.currentline, dbg.source, dbg.name ? dbg.name : dbg.short_src, name, nsz );
```

The change you propose is sound.

**Comment by nagisa** [comment]
:+1: will construct a PR to implement this soon.
