### ISSUE TITLE
Segfault when viewing sampling Data

### ISSUE THREAD

**Issue by Qwendu** [wolfpld/tracy#531]
Versions: 0.9.0, 0.9.1

Tracy Segfaults when viewing sampling data.

Steps to reproduce:
1. Open attached Trace file
2. Statistics > Sampling:
2.1 Show All
2.2 filter for renderMeshBuffer
3. Enable Child Calls
4. In the Assembly view, scroll down to the hotspots
5. Hover over the sampling data/instructions

(Link to .tracy file, github does not let me attach it): https://github.com/Qwendu/PublicFileUploads.git

(Edit: pressed enter to early)

**Comment by Qwendu** [comment]
Attatching a debugger results in:
![image](https://user-images.githubusercontent.com/79834723/222082399-347b801c-3318-425d-93e3-fd29cbfbc925.png)

As I couldnt get Tracy to build, I sadly do not have debug information.

**Comment by wolfpld** [comment]
I can reproduce and the likely cause is that there are no samples in the symbol itself. I will look at this later.

**Comment by wolfpld** [comment]
Fixed by b89bfd44.
