### ISSUE TITLE
Tracy Zone Info and Find Info Screens do not show up

### ISSUE THREAD

**Issue by Christian-Prather** [wolfpld/tracy#533]
Hello, 
I am running Tracy on Ubuntu 22.04 and have had a problem occur recently. When I first ran the program a few days ago I was able to click on the zone and have zone info pop up, in addition find zone would pop up whenever the top button was hit. However after docking some views around both now do not show up. If I hit the find zones button it goes green but nothing pops up. 
Is there a way to reset the view of Tracy back to default so I can use it again. As it sits right now without those two windows it is of little use to me? Any advice is very appreciated. 

I have also attempted to fully rebuild and re clone my repo.

**Comment by wolfpld** [comment]
Remove `imgui.ini` from the configuration directory.

**Comment by Christian-Prather** [comment]
@wolfpld Thank you for such a fast response! Unfortunately I dont seem to see an imgui.ini file anywhere on my system. I apologize for the simplicity of this question but what configuration directory are you referencing?

**Comment by wolfpld** [comment]
Most probably `~/.config/tracy`.

**Comment by Christian-Prather** [comment]
Yes! You're amazing!!! Thank you so much! You've really built something special here!
