### ISSUE TITLE
`TRACY_ON_DEMAND` mode includes time before capture in statistics

### ISSUE THREAD

**Issue by krolli** [wolfpld/tracy#535]
When client library is built with `TRACY_ON_DEMAND` mode enabled and capture starts some (long) time after the process startup, significant portion of timeline in server application is covered by "Missed frames" frame. While that on its own is not a problem, it appears that "Statistics" table includes this time period when calculating precentage of total time. It is possible to work around this by limiting time range used for calculation, but it seems quite confusing at first and I am not certain there is any benefit to this percentage which includes time without useful data.

This is an image of zoomed out 1 second long capture made 50 seconds after startup. Notice how the percentage in "Total time" column shows 1.21%.
![whole-timeline](https://user-images.githubusercontent.com/6864891/222456342-c1343215-513e-4e1a-9f1c-711075dc86aa.png)

Same capture and statistics view, but limiting range to all but 3 initial frames ("Tracy initialization", "Missed frames" and incomplete first frame). Percentage in "Total time" column now shows 66.36%.
![limited-timeline-range](https://user-images.githubusercontent.com/6864891/222456376-98f61f5d-e8d3-4f04-bc9b-0a4f5ad521fa.png)

I checked whether this is some error in our integration code or in client library, but it appears to be on server application side. Percentage calculation in Statistics view (`tracy::View::DrawStatistics`) is using time of last data as total duration, assuming that data starts at 0.

Would it be possible to adjust this percentage calculation to include also time of first relevant data point by default (so that user doesn't have to limit the range to exclude missed frames)? I tried to address it myself, but it doesn't seem to be tracked currently (or maybe I just didn't find it). It's also possible that there are more places which incorrectly use total time instead of just capture time in their calculations, though I only of this one so far.

**Comment by wolfpld** [comment]
Fixed in ed79c4f2. At this point the profiled application has to be emitting `FrameMark`s to properly identify the time when the capture has started. This is applied retroactively to existing traces.

**Comment by wolfpld** [comment]
After 2434514a (and friends) no frame emitting is needed to detect on demand mode.

**Comment by krolli** [comment]
Thanks. It works as expected now. I would consider the issue fixed if it's ok with you.
