### ISSUE TITLE
GPU zones not displayed on the timeline

### ISSUE THREAD

**Issue by farnoy** [wolfpld/tracy#538]
After recent changes to my app & tracy version upgrades, I lost the ability to see GPU zones in my captured traces. I'm using a Rust binding to the C API and configuring + calibrating my Vulkan app to output these zones.

The weird thing is that although GPU zones are not rendered, they are captured, have statistics available (that look right) and even get placed correctly in time because the "Limit range" feature of the Statistics window filters them as expected.

Attaching a screenshot to visualize the issue, as well as the captured trace.

![image](https://user-images.githubusercontent.com/345808/224425803-9dd2bbe3-7ecd-4067-993d-4f72b27d7bfd.png)
[repro.zip](https://github.com/wolfpld/tracy/files/10945990/repro.zip)

Please advise on debugging such issues going forward - while messing with my app, I was able to crash Tracy during capture, how could I identify what happened? Similarly, are there tools to dump/inspect the `.tracy` file as text, to check if GPU zones are being recorded way outside of the capture timeline (I don't think this is the case here, since the Statistics can narrow it down well).

**Comment by wolfpld** [comment]
You see nothing because you are hitting a fast-exit path used to skip rendering until first GPU timings arrive.

```c++
    for( auto& td : gpu.threadData )
    {
        auto& tl = td.second.timeline;
        assert( !tl.empty() );
        if( tl.is_magic() )
        {
            auto& tlm = *(Vector<GpuEvent>*)&tl;
            if( tlm.front().GpuStart() >= 0 )
            {
```

Inspection of the `tlm` vector shows that GPU time is not recorded for the first two GPU zones, but it's present in all the subsequent ones.

![Clipboard03](https://user-images.githubusercontent.com/600573/224436214-40ac188e-8e69-4218-8be4-abc6bcc9254f.png)

18446744073709486262 to hex = FFFFFFFFFFFF00B6

GPU time uses only the high 48 bits, so this decodes to -1 signed, the value used to indicate that time value has not yet been received.

This doesn't make much sense. I would advise doing a full rebuild of your application to check if this may be caused by some stale files. Otherwise doing a bisection search between a known good and bad code (i.e. `git bisect`) will quickly lead you to the change in Tracy that broke things for you.

**Comment by wolfpld** [comment]
For more context, the entries shown above are recorded when you submit markers CPU-side, i.e.:

```c++
        const auto queryId = ctx->NextQueryId();
        vkCmdWriteTimestamp( cmdbuf, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, ctx->m_query, queryId );

        auto item = Profiler::QueueSerial();
        MemWrite( &item->hdr.type, QueueType::GpuZoneBeginSerial );
        MemWrite( &item->gpuZoneBegin.cpuTime, Profiler::GetTime() );
        MemWrite( &item->gpuZoneBegin.srcloc, (uint64_t)srcloc );
        MemWrite( &item->gpuZoneBegin.thread, GetThreadHandle() );
        MemWrite( &item->gpuZoneBegin.queryId, uint16_t( queryId ) );
        MemWrite( &item->gpuZoneBegin.context, ctx->GetId() );
        Profiler::QueueSerialFinish();
```

The GPU time for already existing entries is sent at a later time, during the collection step. Matching is performed via `queryId`:

```c++
        if( vkGetQueryPoolResults( m_device, m_query, m_tail, cnt, sizeof( int64_t ) * m_queryCount, m_res, sizeof( int64_t ), VK_QUERY_RESULT_64_BIT ) == VK_NOT_READY )
        {
            m_oldCnt = cnt;
            return;
        }

        for( unsigned int idx=0; idx<cnt; idx++ )
        {
            auto item = Profiler::QueueSerial();
            MemWrite( &item->hdr.type, QueueType::GpuTime );
            MemWrite( &item->gpuTime.gpuTime, m_res[idx] );
            MemWrite( &item->gpuTime.queryId, uint16_t( m_tail + idx ) );
            MemWrite( &item->gpuTime.context, m_context );
            Profiler::QueueSerialFinish();
        }
```

**Comment by farnoy** [comment]
Thank you! With your description, I was able to identify the problem with my app - it was not submitting timing data during renderer changes, notably for the very first frame at startup. It's working as expected again.

I'll defer to you if you want to close this issue now. I suppose it would be great to get a warning if Tracy opens a trace with this problem (any/first GPU zones that don't have timing data).

**Comment by wolfpld** [comment]
I don't think warning when loading a trace would be too useful. There's nothing you can do about it at this point.
