### ISSUE TITLE
[import-chrome] how to approach importing metrics?

### ISSUE THREAD

**Issue by ethercrow** [wolfpld/tracy#54]
I'd like to add a couple of global metrics like heap size and CPU load in my chrome-tracing files. Is there an appropriate API I should use in `import-chrome.cpp` to import those?

**Comment by wolfpld** [comment]
No API other than what is available. How are these metrics structured? Are they appropriate for plotting (i.e. are time and value pairs)?

**Comment by ethercrow** [comment]
The section `Counter Events` in the spec looks appropriate https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.msg3086636uqhttps://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.msg3086636uq

A counter event has a timestamp and one or more `(metric name, metric value)` pairs.

**Comment by wolfpld** [comment]
Extended the API to accept plot data.
