### ISSUE TITLE
"Empty statement" warnings when Tracy is disabled

### ISSUE THREAD

**Issue by OttoHatt** [wolfpld/tracy#549]
Disabling Tracy (i.e. not defining `TRACY_ENABLE`)  defines all profiling macros in `Tracy.hpp` as empty. This produces warnings in [IDEs like CLion](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4405559160850--Empty-statement-warnings-for-disabled-macros). It looks like a fix would be to define all macros as `void()`?

**Comment by wolfpld** [comment]
Current behavior is the intended behavior. Macros are supposed to expand into nothing. The problem is with CLion.
