### ISSUE TITLE
Profiler aborts with `Error 65543: GLX: Failed to create context: BadValue (integer parameter out of range for operation`)

### ISSUE THREAD

**Issue by alice-i-cecile** [wolfpld/tracy#553]
I built Tracy's profiler on PopOS using the method described in #552. This is building the latest `master`: https://github.com/wolfpld/tracy/commit/4c0e6fe3cae0f96b1718bea2d1a40c458e506ed6 

Upon running it, I receive the following panic message:

```
alice@pop-os:~/Documents/tracy/profiler/build/unix$ ./Tracy-release
Error 65543: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
terminate called without an active exception
Aborted (core dumped)
```

**Comment by wolfpld** [comment]
Looks like 3D acceleration is not working for some reason?

**Comment by alice-i-cecile** [comment]
Makes sense. Checking out the `v0.9.1` tag and rebuilding doesn't resolve it. 

Retrying without the LEGACY flag reveals that `freetype` appears to be missing.

```
../../../imgui/misc/freetype/imgui_freetype.cpp:39:10: fatal error: ft2build.h: No such file or directory
   39 | #include <ft2build.h>
```

Installing that as `libfreetype-dev` doesn't work, as it's already installed. Scrolling up, it's complaining about `xkbcommon` as well:

```
Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon' found
```

Installing that as `libxkbcommon-dev`, the warning about `xkbcommon` being missing is gone and compilation completes.

Of course, this then fails with 

```
Cannot establish wayland display connection!
terminate called without an active exception
Aborted (core dumped)
```

because I didn't build in LEGACY mode.

**Comment by alice-i-cecile** [comment]
I applied an OS update and cleaned out some more hard drive space. This no longer crashes (when using the legacy client) 🙃
