### ISSUE TITLE
Link failure as `TracyCSetThreadName` calls `___tracy_set_thread_name` even when `!defined(TRACY_ENABLE)`

### ISSUE THREAD

**Issue by gavinbeatty** [wolfpld/tracy#556]
## Problem

Calling `TracyCSetThreadName` in a build that does *not* define `TRACY_ENABLE`, and that does *not* link TracyClient.cpp results in a link failure due to missing symbol, `___tracy_set_thread_name`.

## Expected behavior

Expected the `TracyCSetThreadName` macro to be defined to do nothing in this case, and hence, link succeeds (with no thread name setting code in the output).

It should not be necessary to link/compile TracyClient.cpp in non-profiling builds.

## Workaround: redefine macro (preferred)

```
#include <tracy/TracyC.h>
/* Fix issue where TracyCSetThreadName is not stubbed when !defined(TRACY_ENABLE) */
#ifndef TRACY_ENABLE
# undef TracyCSetThreadName
# define TracyCSetThreadName(n)
#endif
```

## Workaround: define symbol

Include a stub `___tracy_set_thread_name` symbol in your project.

## Workaround: compile and link TracyClient.cpp

Should not need a C++ compiler to make a release/debug build a C project that only uses C++ code for profiling.

## Proposed fix

TracyC.h has the following before any `#ifdef` type checks;

```
TRACY_API void ___tracy_set_thread_name( const char* name );

#define TracyCSetThreadName( name ) ___tracy_set_thread_name( name );
```

These should be moved to inside the `#else` branch of `#ifndef TRACY_ENABLE`, and the following added to the `#ifndef TRACY_ENABLE` branch itself:

```
#define TracyCSetThreadName(n)
```

**Comment by wolfpld** [comment]
> It should not be necessary to link/compile TracyClient.cpp in non-profiling builds.

This is a false assumption. Thread naming functionality is expected to work regardless if you are profiling or not. Otherwise you end up having to handle naming in various ways, which leads to pain.

Closing, as you have listed several workarounds, which will work fine for your needs.

**Comment by gavinbeatty** [comment]
As long as it's not complicated to include TracyC.h without TracyClient.cpp, I'm satisfied. It's very simple right now, so I'm content with that.

My 2c are that I don't want to introduce a dependency on a profiling library for anything other than profiling.
