### ISSUE TITLE
TracyC.h errors with 'initializer is not a constant'

### ISSUE THREAD

**Issue by yuplucas** [wolfpld/tracy#564]
Toolchain: Visual Studio 22 v17.4.1
Tracy version:  `c79154c87b7d23bf465d973e6c62cc7549825b45`

## Problem

I am trying to set up Tracy on the [Blender](blender.org) code base and I get an error when trying to compile with the TracyC.h header.

Inside  a function, I try to create a new zone like so:

```c
static void preview_startjob(void *data, bool *stop, bool *do_update, float *progress) {
 ...
  TracyCZoneN(preview_job_ctx, "Preview job", true);
...
}
```

When I attempt to compile, I get an error saying the initializer is not a constant.

```
compile error C2099: initializer is not a constant
```` 

AFAIU the error happens because the `TracyCZoneN` macro attempts to initialize a static struct inline:

```c
#  define TracyCZoneN( ctx, name, active ) static const struct ___tracy_source_location_data TracyConcat(__tracy_source_location,TracyLine) = { name, __func__,  TracyFile, (uint32_t)TracyLine, 0 }; TracyCZoneCtx ctx = ___tracy_emit_zone_begin( &TracyConcat(__tracy_source_location,TracyLine), active );
```

Specifically, the problem happens when the `___tracy_source_location_data` struct is being initialized.

## Expected behavior

I expected the TracyC macro to compile just fine. All of the items in the initializer are static, so I expected that to not be an issue.

## Workaround

I defined the location data as a global and then manually emitted the zone begin event:

```c
static const struct ___tracy_source_location_data zone1= { NULL, NULL /* got rid of the __func__ macro */,  TracyFile, (uint32_t)TracyLine, color }; 

static void preview_startjob(void *data, bool *stop, bool *do_update, float *progress) {
 ...
  TracyCZoneCtx preview_job_ctx = ___tracy_emit_zone_begin( &zone1, true);
...
}
```

## Question

Is there a specific C version targeted by Tracy?

The manual mentions C++ 11 support to compile the library, but I couldn't find anything specific to the C version.

**Comment by wolfpld** [comment]
Disable edit-and-continue (which is not conformant to the standard).
