### ISSUE TITLE
Intermediate windows file not ignored.

### ISSUE THREAD

**Issue by ambientenergy102** [wolfpld/tracy#565]
Hi, would you please ignore *.obj files in the base directory of this repository?  It would help keep the repository clean when building on windows.

**Comment by wolfpld** [comment]
Why would there be objs in the root?

**Comment by ambientenergy102** [comment]
Sorry, my comment wasn't clear.  I was asking for globally *.obj files to be ignored for the entire repo, as on windows when you build there are two object files generated in the tracy folder.  Adding the ignore to the .gitignore in the root of the repository would ignore those temporary object files wherever they may be generated in the project as part of a build.
