### ISSUE TITLE
Tracy-release : invalid version for global wl_seat (17): have 5, wanted 7

### ISSUE THREAD

**Issue by ArielGMachado** [wolfpld/tracy#567]
OS: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
X-Manager: Wayland

```
profiler/build/unix$ ./Tracy-release 
wl_registry@2: error 0: invalid version for global wl_seat (17): have 5, wanted 7
Cannot initialize EGL!
terminate called without an active exception
Aborted (core dumped)
```

Get wayland info:
```
weston-info | grep wl_seat

interface: 'wl_seat', version: 5, name: 17
```

This line:
https://github.com/wolfpld/tracy/blob/2759f96c0eece3643eea10a79bce49b560a3da54/profiler/src/BackendWayland.cpp#L522

Downgrading this  hardcoded version from 7 to 5 worked to me.

**Comment by wolfpld** [comment]
Fixed in c57b8994.
