### ISSUE TITLE
Tracy Server fails to start presumably because ResolvService::Worker() blocks on a condition variable indefinitely

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#574]
When starting Tracy.exe (tested 0.8 release, and 0.9.1 release and locally built) the started tracy application appears in the taskbar, but no window appears. When hovering the icon in the taskbar, the small window preview shows it as fully white, but all other windows go transparent, so the window doesn't seem to be in the visible part of the screen, if it exists. This stays like this indefinitely (I waited 7 minutes). The profiler does not start.

This only happens on my ThinkPad E15 Gen 3 with latest Windows 10 updates, not on my Desktop (same OS version). Restarting the computer does not fix it. I don't exactly know when this behaviour started (I didn't use the laptop for a while). It worked fine a couple of months ago, with the exact same executable, so presumably some change on my system caused this, not a tracy update.

When debugging this, `ResolvService::Worker()` (btw - typo?) catched my eye, as it is stuck on `m_cv.wait`. The only other interesting thread loops in `Backend::Run()`, which seems to be intentional. I attached a [minidump](https://github.com/wolfpld/tracy/files/11781729/Tracy.zip) from Visual Studio.

**Comment by wolfpld** [comment]
Try removing `%APPDATA%/tracy/window.position`.

> (btw - typo?)

No. https://en.wikipedia.org/wiki/Resolv.conf

**Comment by simonvanbernem** [comment]
That did it! Was the UI just reeeaaally offscreen then? I feel stupid now :D

**Comment by wolfpld** [comment]
I'm not sure what's the reason for this bug to happen, I have not experienced it. But it keeps popping up here and then.

**Comment by simonvanbernem** [comment]
This laptop was connected to a 2-monitor setup with 4k and 1440p before, and when this happened, it just had its own internal 1080p monitor to display things. Maybe the saved window position does not account for that?
