### ISSUE TITLE
.NET bindings

### ISSUE THREAD

**Issue by clibequilibrium** [wolfpld/tracy#587]
In case if anybody needs C# bindings for Tracy

https://github.com/clibequilibrium/Tracy-CSharp 

Still experimental but hopefully can help somebody

**Comment by wolfpld** [comment]
Making a PR to update the manual will be perhaps a better way to document things.

**Comment by clibequilibrium** [comment]
> Making a PR to update the manual will be perhaps a better way to document things.

Thanks! Will do

**Comment by clibequilibrium** [comment]
https://github.com/wolfpld/tracy/pull/590
