### ISSUE TITLE
The messages window slows down tracy significantly when trace contains many messages

### ISSUE THREAD

**Issue by nagisa** [wolfpld/tracy#59]
I have a trace that contains 1.8M messages (according to tracy's message window). With this many messages any operations involving the message window are very slow. Opening the window takes seconds, closing it also takes seconds. While the message window is open, the main trace view is not responsive either, however when it is closed, there's no perceptible performance impact on Tracy.

Interestingly the main trace view does not suffer from this problem and is able to display an arrow for each message and the message contents when the arrow is hovered over without much effort.

Let me know if you need more information and if so, what.

**Comment by wolfpld** [comment]
This is due to text wrapping and filtering.

**Comment by wolfpld** [comment]
Fixed in 420bdd58.
