### ISSUE TITLE
C++ 17 requirement for VS is unnecessary

### ISSUE THREAD

**Issue by cliffowen** [wolfpld/tracy#6]
TracyWorker makes use of initializer lists in structures which inherit from other structures. This isn't supported in Visual Studio until C++ 17, and apparently only on VS 2019. VS 2017 doesn't seem to support it properly. This requirement feels a bit arbitrary because if I replace with a simple constructor for the code, it builds and executes properly as C++ 11 on VS 2017.

Example error:
TracyWorker.cpp(284,35): error C2440: 'initializing': cannot convert from 'initializer list' to 'tracy::SourceLocation'

There's only 3 errors total so it should be relatively easy to switch back.

**Comment by wolfpld** [comment]
Care to elaborate?

**Comment by cliffowen** [comment]
Sorry,  you were too quick. I miss-hit enter before I could enter a proper description, and you asked while I was typing. :)

**Comment by wolfpld** [comment]
What is the exact issue here? Why should targetting c++11 be valuable?

**Comment by cliffowen** [comment]
1. Requiring C++ 17 for a single language feature feels arbitrary. Making the change to support more options is very trivial... I know, 'cause I made the change.

2. Like you, I'm working on an open source project which targets C++ 11 and is multi-platform. I see little reason to force users into such a narrow toolchain when they have their own reasons for doing what they do. These may include using a library that happens to only build with VS 2017 or perhaps they spent a bunch of money on Resharper for VS 2017 and don't have budget to upgrade right now... or their management says no, or their build engineers say it's too much work, or they're simply in the middle of a product cycle and don't wish to change tools mid-cycle because it introduces risk.

3. Trust. C++ 11 has been in use for many years and has a high adoption rate. C++ 14, shorter time and shorter adoption rate, C++ 17 least of all. Even with VS 2017 C++ 17 support, it is incomplete. Forcing the move forward to latest and greatest and people will simply be reluctant to rush forward... per my #2. I am reluctant to force my users to move forward for a single library if they are reluctant to push this requirement forward in their project.

4. I can continue to change Tracy to fit my needs, but at some point it has to give... I either lock into a specific build, I simply never upgrade, or I don't use it at all and continue to use the in-house solution that I'm trying to replace. I would much rather have a touch more flexibility and ask for the simple change.

5. Your own documentation for 0.6.3 actually states C++ 11 and this is 0.6.x. At a minimum, the docs are out of date but to be honest if the docs said C++ 17, I never would have downloaded it (per #2)

6. Do you have a reason to argue that C++ 11 is not valuable? I hadn't heard yet why the change was made... what is there to accomplish with this as a requirement, specifically with using the initializer?

Alternatively, if you are willing, I can provide a PR which adds the constructor that solves the problem.

**Comment by wolfpld** [comment]
>Requiring C++ 17 for a single language feature feels arbitrary. Making the change to support more options is very trivial... I know, 'cause I made the change.

It is not as trivial as you may think. Currently you have also disabled support for parallel sorting algorithms and for efficient number to string conversions. These things have impact on execution speed.

> Like you, I'm working on an open source project which targets C++ 11 and is multi-platform. I see little reason to force users into such a narrow toolchain when they have their own reasons for doing what they do. These may include using a library that happens to only build with VS 2017 or perhaps they spent a bunch of money on Resharper for VS 2017 and don't have budget to upgrade right now... or their management says no, or their build engineers say it's too much work, or they're simply in the middle of a product cycle and don't wish to change tools mid-cycle because it introduces risk.

The only changes required to build Tracy server on MSVC 2017 are changing the platform tools to 141 and selecting the SDK version, as 2017 doesn't support the "most recent" option introduced in 2019.

> Your own documentation for 0.6.3 actually states C++ 11 and this is 0.6.x. At a minimum, the docs are out of date but to be honest if the docs said C++ 17, I never would have downloaded it (per #2)

Yes, the client part is strictly c++11. The server part is not, as it is a separate application. Specifying language version for the server has no purpose.

**Comment by cliffowen** [comment]
>The server part is not, as it is a separate application. Specifying language version for the server has no purpose.

I can see your point there, however, we are not interested in the server part as a separate application. We have our own application framework which happens to also use Dear ImGui which is what brought us to Tracy as we need something that can integrate into what we already have.

This is a standalone editor, profiler and build system. It may be acceptable to have this requirement only on the editor, it'll take a bit to consider the ramifications if adopted as a requirement.. especially if the client remains C++ 11 compatible. That part is truly critical at the moment.

> The only changes required to build Tracy server on MSVC 2017 are changing the platform tools to 141 and selecting the SDK version.

This is what I expected but it does not seem to be the case. I have the latest SDK, the 141 tools and selected C++ 17 which is why I stated "VS 2017 doesn't seem to support it properly". Supposedly this was resolved last summer but I'm not seeing it successfully compile with any number of tool combinations. Only moving the same project to vs2019 and the 142 tools (and C++ 17) actually compiled... the issue at hand being aggregate structure initialization doesn't work with initializer lists with this particular build of VS 2017 and before mentioned tools.

However, I still argue it's a trivial fix because it's solvable with the addition of a constructor. I find it perfectly acceptable to have disabled support for features (due to missing language features) and this is unrelated to the issue I filed, which is that it doesn't compile in 2017, only in 2019. Disabled support for features is a choice the user is free to make in their regular pros/cons decision process. Failing to compile removes that ability to make the choice.

**Comment by wolfpld** [comment]
> This is what I expected but it does not seem to be the case. I have the latest SDK, the 141 tools and selected C++ 17 which is why I stated "VS 2017 doesn't seem to support it properly". Supposedly this was resolved last summer but I'm not seeing it successfully compile with any number of tool combinations. Only moving the same project to vs2019 and the 142 tools (and C++ 17) actually compiled...

I have verified that it works today, using the latest MSVC 2017 Express.

> However, I still argue it's a trivial fix because it's solvable with the addition of a constructor.

Show me the diff (preferably as a PR).

> I find it perfectly acceptable to have disabled support for features (due to missing language features)

Yeah, this is how the things currently are anyway. Imagine the fun of implementing a new feature only to find that it doesn't compile on gcc/clang, just because their std lib didn't bother to implement everything as in the spec.
