### ISSUE TITLE
build in a Windows environment

### ISSUE THREAD

**Issue by Berger0409** [wolfpld/tracy#627]
When I install vcpkg and prepare to compile, I report an error:
C:\Users\bobby\source\repos\tracy\profiler\build\win32\LINK : fatal error LNK1104: Unable to open file“brotlicommon-static.lib”
how can i get this lib?

**Comment by tobbez** [comment]
It appears you can work around this by renaming:

- `brotlicommon.lib` to `brotlicommon-static.lib` and,
-  `brotlidec.lib` to `brotlidec-static.lib`

in:

- `vcpkg_installed\x64-windows-static\lib` for release builds
- `vcpkg_installed\x64-windows-static\debug\lib` for debug builds

The paths above assume you used `vcpkg\install_vcpkg_dependencies.bat` (and not `vcpkg integrate install`).

**Comment by Berger0409** [comment]
Not long after I graduated, this is my first time asking questions in the open source community, thank you for your help, my problem has been solved!

**Comment by wolfpld** [comment]
Fixed in 434a27b8.
