### ISSUE TITLE
In the Windows environment, the client connection server cannot be connected

### ISSUE THREAD

**Issue by Berger0409** [wolfpld/tracy#634]
I have successfully compiled Tracy's version of Windows，But when I connect to the server with client，I did debugging in the code and found that the client kept repeatedly calling the connect function in the TracySocket.cpp file。and I see on the server side that the port I opened for Tracy keeps being in the listen state，Of course, sometimes the connection is successful, but sometimes it takes a few seconds, sometimes it takes tens of minutes

**Comment by wolfpld** [comment]
These kind of issues are always caused by misbehaving firewalls, antivirus programs, etc.
