### ISSUE TITLE
secure parameter is missing from MemFree and MemAlloc calls

### ISSUE THREAD

**Issue by szilardo** [wolfpld/tracy#64]
MemFree and MemAlloc calls are missing the last parameter:

https://github.com/wolfpld/tracy/blob/4881f7aa548f689ae742b399d1cafaa25be6b22b/client/TracyProfiler.hpp#L418
https://github.com/wolfpld/tracy/blob/4881f7aa548f689ae742b399d1cafaa25be6b22b/client/TracyProfiler.hpp#L396

**Comment by wolfpld** [comment]
Fixed in 4179e850.
