### ISSUE TITLE
cpu data item show "?" on "tracy mainwindow"

### ISSUE THREAD

**Issue by RyanPangZheng** [wolfpld/tracy#640]
ENV:
   version 0.10.0  https://github.com/wolfpld/tracy/releases/tag/v0.10
   client run on target: aarch64
Issue:
  show "?" on cpu data item on the plot
![img_v2_a9c4ff0f-efbd-46e8-9bd6-74dd9ad665fg](https://github.com/wolfpld/tracy/assets/23069505/afb7cc36-54d8-469c-94a4-4524b6fe433c)

Expect:
    1. show "cpu context or thread name or something"
    2. show thread swiching
![img_v2_e95f1c94-a758-4e99-b480-46930513c5fg](https://github.com/wolfpld/tracy/assets/23069505/d8573fae-0205-44f7-9d2f-d0657f84cf66)

Method i use below:
            ZoneScoped;
            char mytid[6];
            sprintf(mytid, "%d", tid_.load());
            tracy::SetThreadName(mytid);
            FrameMarkStart (mytid ); 
            TracyFiberEnter( name().c_str() );
            TracyCZoneC(zone, 0xff0000, true)
            TracyCZoneEnd( zone );
            TracyFiberLeave;
            FrameMarkEnd ( mytid );

Need some help.
And client run on x86_64 ubuntu 20.04 never show "cpu data plot on main window"

**Comment by wolfpld** [comment]
Some processes may already be dead, in which case there's no way to know what they were. Or your kernel may not allow introspection of foreign processes. See the Android troubleshooting section of the manual for instructions on how to remove some of these security features.
