### ISSUE TITLE
Can't seem to enable sampling

### ISSUE THREAD

**Issue by Causeless** [wolfpld/tracy#658]
Hey, I'm having an issue where sampling seems extremely temperamental and doesn't seem to work. When it does work, it's great - and it's works extremely well in tandem with instrumentation zones, for script profiling etc.

However most of the time I just can't get it to work. I've tried scouring every setting but can't figure out what's going on.
I'm running Windows 11 Pro, running the target application using "Run as Administrator", with full .pdb debug information next to the .exe. I am compiling with the TracyClient.cpp and have the TRACY_ENABLED and TRACY_ON_DEMAND preprocessor definitions.

In the past I've realized that I've messed up due to, for example, not running as admin, but now I can't really figure out why it's not working this time. It'd be great if we had a "enable/disable sampling" or sampling frequency switch directly in the interface, as well as it giving a descriptive error message if you try to enable sampling when it's not possible, but right now it's a bit of a black box.

That aside, in the past I've had great success using Very Sleepy, which is a pretty simple sampling profiler (that is unfortunately Windows-specific). Very sleepy has variable sampling rates as well as working even without running the target application as admin, so I wonder if it'd be possible to at least have some sampling support for non-admin applications, albeit at a potentially very large performance overhead.

**Comment by wolfpld** [comment]
The kernel logger session that Tracy uses is not particularly well suited for use by multiple applications. You basically have to pull the rug out from under any other application that might want to use it, and other applications might do the same for your application.

Very Sleepy is open source, so any methods used there can be ported to work in Tracy.

**Comment by Causeless** [comment]
Is there any way to see what applications are doing this, or to give Tracy priority?

**Comment by wolfpld** [comment]
Unlikely. Maybe you would be able to monitor if the kernel session is closed on Tracy side, to make sure that this is surely the issue.

**Comment by Causeless** [comment]
Oh, I figured it out. I had several instances of Tracy running as a ghetto way of comparing the results (I know there's inbuild functionality too!), which was interfering with it.
