### ISSUE TITLE
Can tracy support QNX system?

### ISSUE THREAD

**Issue by Wuqiqi123** [wolfpld/tracy#679]
Or If I want to support qnx, which part of source code should I modify.

**Comment by wolfpld** [comment]
See #649.

**Comment by Wuqiqi123** [comment]
I test tracy master branch in QNX system but seems has some problems.
![Peek 2023-12-11 10-42](https://github.com/wolfpld/tracy/assets/37368540/eda7c8b1-4a47-44c5-9c05-47ef29c65fd7)
