### ISSUE TITLE
Control improvements for GPU traces

### ISSUE THREAD

**Issue by vblanco20-1** [wolfpld/tracy#68]
When working on my vulkan engine, i had some troubles with the ergonomy of the tracy Vulkan traces. The main issue i got is that encoding the samples can be very finnicky, with the samples having to be encoded after a command buffer has begun, and before a command buffer ends. The default scope-based sampling can bring big issues to it.

Another issue is that in many engines, people write a command encoder of sorts, which saves abstracted GPU commands, and then the actual GPU execution is done deferred later. This is completely incompatible with the current way the vulkan traces work.

For the "need more control" part, what ive done is a copy of tracy::VkCtxScope that does not use RAII for injecting the queries, but instead uses  Start(VkCommandBuffer cmd), and End() functions.  This allows to encode vulkan zones across queue submits.
Its used like this. (pseudocode)
```cpp

VkCommandBuffer cmd = allocate_buffer();

TracyVkNamedManualZone(profilercontext, graphZone, cmd, "Framegraph", true);

vkBeginCommandBuffer(cmd, &beginInfo);


for(auto& pass : passes){
   graphZone.Begin(cmd); //begin the zone
   pass->encode_commands(cmd);
    graphZone.End(); //finish the zone before we submit

    submit_command(cmd);
    cmd = allocate_buffer(); //allocate another command 
}
```

For the encoding part, what ive done is to define a TracySourceLocation() macro that saves only the source location. It can then be used as this.

```cpp
TracySourceLocation(sourceLoc, "Some pass", tracy::Color::Grey);

encoder->begin_trace(&sourceLoc);
```

The idea is that later down the line, when the commands are decoded, you can do this with it.

```cpp
void Decode_BeginTrace(CommandDecodeState* state, CMD_BeginTrace* cmd)
{
	
       // grab the source location we encoded before
	const tracy::SourceLocationData* sourceloc =cmd->profilerSourceLocation;

	if (state->tracyScope == nullptr) {
		//allocate a new ManualScope and start it
		state->tracyScope = new tracy::VkCtxManualScope(profilerContext, sourceloc, state->cmd, true);
		state->tracyScope->Start(state->cmd);
	}
	else {
               //finish a ManualScope and then reset its source_location
		state->tracyScope->End();
		state->tracyScope->SetSourceLocation(sourceloc);
                state->tracyScope->Start(state->cmd);
	}
}
```

These changes are very minimal, and i can PR them if they sound useful.

**Comment by wolfpld** [comment]
I'd rather it be somewhat closer to the C API in design.

**Comment by vblanco20-1** [comment]
In that case, what about something of this sort.

```cpp
VkCommandBuffer cmd = allocate_buffer();

TracyVkNamedManualZone(profilercontext, graphZone, cmd, "Framegraph", true);

vkBeginCommandBuffer(cmd, &beginInfo);

for(auto& pass : passes){
   TracyVkBeginZone(graphZone, cmd) //begin the zone
   pass->encode_commands(cmd);
    TracyVkEndZone(graphZone); //finish the zone before we submit

    submit_command(cmd);
    cmd = allocate_buffer(); //allocate another command 
}
```
For the separated source-location way, maybe better just keep it as a manual way, calling the functions without the macros.

Mostly similar to the C api, but with the difference that there is a "definition" for the zone, not just the begin/end with the begin defining the zone.

**Comment by wolfpld** [comment]
I don't understand the purpose of `TracyVkNamedManualZone`.

**Comment by vblanco20-1** [comment]
This is taken from a snippet from a frame-graph i have. But simplified. The loop has some high complexity, and normal scope-based zones wouldnt work on it. 

The reason to define the manual zone separately, and not immediately begin the zone there, is so you can then use it in a manual way, doing the begin and end zone yourself. This allows more complex uses of the zones. It would also allow storing the zone state in some structure and run it over multiple function calls.

A code snippet that kinda shows why you might need it is here
```cpp
VkCommandBuffer cmd = allocate_buffer();

TracyVkNamedManualZone(profilercontext, graphZone, cmd, "Framegraph", true);

vkBeginCommandBuffer(cmd, &beginInfo);
 TracyVkBeginZone(graphZone, cmd) //begin the zone

for(auto& pass : passes){  

   pass->encode_commands(cmd); //encode the commands for this pass

if(pass->performSubmit){
    TracyVkEndZone(graphZone); //finish the zone before we submit
   vkEndCommandBuffer(cmd);
    submit_command(cmd);
    cmd = allocate_buffer(); //allocate another command 
    vkBeginCommandBuffer(cmd, &beginInfo);
    TracyVkBeginZone(graphZone, cmd) //restart the zone
   }
}

```
