### ISSUE TITLE
Info icons in the top bar are hard to hover due to layout changes during recording

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#693]
When recording a trace, I sometimes want to hover over these icons on the right side to read their tooltips: 
![grafik](https://github.com/wolfpld/tracy/assets/10748498/39f3cb1c-1891-46ab-9a5f-ed06e34cf7cf)
I imagine this is especially important to new users.

When recording the trace, this is often not that easy, because they jitter back and forth due to text on their lefthand side changing in length depending on the what is being recorded, which means they might jump out from under the cursor. I believe the length of the view span text is especially unstable since with the default selection of 3 frames, this depends entirely on the frame timing.

It would be better if the icons weren't jumping around slightly so one could hover them without hassle.

**Comment by simonvanbernem** [comment]
This also happens when loading a trace from memory. After it is loaded, there is tooltip saying how long loading took, but the profiler memory usage that is in the top bar still grows. The tooltips jumps around until the memory usage settles.

**Comment by wolfpld** [comment]
6199b2f8 should fix this.
