### ISSUE TITLE
Can you change the data collection side to socket-clinet?

### ISSUE THREAD

**Issue by aidexie** [wolfpld/tracy#694]
Now in tracy's network structure, the page socket that displays the data is the client, and the socket that collects the data is the server. Not sure if I understand correctly, looking at the code it is this one.
Now I need to collect the data on android and pass it via usb to the pc(server) for display. These android machines are not local machines but cloud machines. It can only run through android-client, pc-server mode. And can't run through the android-server, pc-client model.
Now is there any way to change the tracy implementation to adapt it。

**Comment by wolfpld** [comment]
The network setup won't be changed.
