### ISSUE TITLE
ImGuiColorTextEditor inside tracy namespace introduces bloat

### ISSUE THREAD

**Issue by cliffowen** [wolfpld/tracy#7]
We are using ImGuiColorTextEditor inside our project, and so is Tracy profiler. However, Tracy has included it inside the tracy namespace (profiler). This leads to it being required twice... inside and outside the namespace so that we may use it or tracy may use it.

You can see these changes to the ImGuiColorTextEditor project in the texteditor.h and texteditor.cpp.

Requesting this 3rd party lib be outside the tracy namespace so it may be included once... To include only the standard ImGuiColorTextEditor introduces a linker error that tracy cannot find it. You would still be able to ship the version you provide, but you would not conflict with folks using a competing equivalent library.

**Comment by wolfpld** [comment]
ImGuiColorTextEditor is no longer used on master.
