### ISSUE TITLE
Application hangs when connecting to profiler, only when GPU events have been submitted

### ISSUE THREAD

**Issue by yodasoda1219** [wolfpld/tracy#709]
I am writing a graphics framework in C#, using [these Tracy bindings](https://github.com/clibequilibrium/Tracy-CSharp/), linked in the Tracy README. When my application (the neural net project entitled `MachineLearning`) connects to the profiler, and GPU zones have been submitted, the client application mysteriously freezes.

Steps to reproduce:
- Run on Ubuntu 22.04.3 LTS
- Clone [this](https://github.com/yodasoda1219/code-playground) repository at commit `3833acd`
- Build the project on the Debug configuration
- Run `dotnet Playground/MachineLearning/bin/Debug/net7.0/MachineLearning.dll`
- Hit "Start" on the Training window
- Connect to the Tracy GUI (using v0.10)

The application should freeze in `Core/CodePlayground.Graphics/Vulkan/VulkanProfiler.cs` on line 90. (Function `TracyEmitGpuZoneBeginSerial`)

**Comment by yodasoda1219** [comment]
Reproduced on Windows - though not on the D3D11 example program. Weird.

**Comment by yodasoda1219** [comment]
Not an issue with the Vulkan context implementation - I just tested the Vulkan backend with a C++ project, and I 1:1 translated the Vulkan context code into my C# codebase. Will continue testing.

**Comment by yodasoda1219** [comment]
I have verified that replacing the Tracy build used by my C# project via P/Invoke does not fix the issue. I believe this is a problem with the C API.

**Comment by yodasoda1219** [comment]
In fact, debugging native code shows that this is an access violation in `tracy::Profiler::SendString` calling `strlen` on an unallocated string. I have verified that I do not pass such a pointer to Tracy (logging all memory allocated by my profiler interface and cross-referencing with pointers provided by the debugger). I do not have insight into how the Tracy client library operates, and so I'm not sure where such a pointer would be passed.

**Comment by wolfpld** [comment]
What is the call stack leading to `SendString`?

**Comment by yodasoda1219** [comment]
On the "Tracy Profiler" thread:
![image](https://github.com/wolfpld/tracy/assets/25918459/970c94e1-dfa7-4571-9a35-5ac7e6f933ae)

**Comment by wolfpld** [comment]
There are certain requirements for the lifetime of data passed to the profiler (detailed in the manual). Your description suggests that the bindings you are using do not meet these requirements. I would suggest creating an issue in that repository, as this does not seem to be a Tracy issue.

**Comment by yodasoda1219** [comment]
Got it. Thanks.

**Comment by yodasoda1219** [comment]
Problem solved. This was an issue with me calling `___tracy_emit_gpu_zone_begin_serial` instead of `___tracy_emit_gpu_zone_begin_alloc_serial`. My bad.
