### ISSUE TITLE
Unexpected behavior with administrator permissions and ON_DEMAND enabled

### ISSUE THREAD

**Issue by jilker** [wolfpld/tracy#713]
When running an application with the ON_DEMAND macro enabled in Tracy 0.10 on Ubuntu 20.04, the expected behavior is that Tracy should not record any information until the server is connected to the client. However, when the application is run with administrator permissions, the allocated memory starts to grow even before connecting any server.

Are there any specific macros that can be used to disable this memory sampling issue? I have already tried using NO_SAMPLING and NO_SYSTEM_TRACING in combination with ON_DEMAND, but it hasn't resolved the problem.
Environment:

Tracy Version: 0.10
Operating System: Ubuntu 20.04

**Comment by wolfpld** [comment]
Can't repro and there are protections for this since 0.8: f058ad01f.
