### ISSUE TITLE
Wayland error when built with LEGACY=1 option 

### ISSUE THREAD

**Issue by dafteran4** [wolfpld/tracy#725]
Hi, I built tracy profiler by:

```
cd profiler/build/unix
make LEGACY=1 -j8
```
However, I am getting the following error when running `./Tracy-release` in X session:
```
Error 65544: Wayland: Failed to connect to display
terminate called without an active exception
```
I also tried exporting `LEGACY=1`, but that didn't work as well. Is there some other way I should be doing this? Thanks.

**Comment by wolfpld** [comment]
The legacy version uses the glfw library. It comes in X and Wayland variants, you may have the wrong one installed.

**Comment by dafteran4** [comment]
Indeed, that seems to be the problem. It works now. Thank you for your help.
