### ISSUE TITLE
Undeclared identifier when compiling TracyD3D11.hpp with TRACY_ON_DEMAND

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#753]
TracyD3D11.hpp:360 is referencing "is_active", but the correct variable is called "active".

**Comment by wolfpld** [comment]
Fixed in 83305115.

**Comment by simonvanbernem** [comment]
Just saw that this was a duplicate of https://github.com/wolfpld/tracy/issues/670 also.
