### ISSUE TITLE
Diverging macros TracyOpenCL.hpp 

### ISSUE THREAD

**Issue by kubouch** [wolfpld/tracy#76]
The number of parameters in some of the macros in `TracyOpenCL.hpp` with and without `TRACY_ENABLE` is different and some macros are even missing when compiled without Tracy enabled (e.g., TracyCLZoneSetEvent). This leads to build errors.

I can file a PR on this when I have some time. Seems like a trivial fix.

**Comment by wolfpld** [comment]
Please do.
