### ISSUE TITLE
Error during Tracy profile make

### ISSUE THREAD

**Issue by VimalWill** [wolfpld/tracy#763]
Hi, 
     I'm able to capture but when i'm trying to build the profiler (server) for ubuntu, the make files 

`[  0%] Built target TracyGetOpt
[  1%] Built target TracyNfd
[ 13%] Built target TracyZstd
[ 43%] Built target capstone
[ 48%] Built target TracyServer
[ 63%] Built target freetype
[ 66%] Built target TracyImGui
make[2]: *** No rule to make target '//usr/share/wayland-protocols/staging/cursor-shape/cursor-shape-v1.xml', needed by 'wayland-cursor-shape-client-protocol.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:263: CMakeFiles/tracy-profiler.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
`
I went into the "/tracy/profiler/" and try to do a cmake and make with make LEGACY=1 -j16 but it failed with above error and my 

system details:
kernel: 6.2.0-39-generic
Ubuntu 22.04.3 LTS

kindly help me with this regards 
thanks 
Vimal W

**Comment by wolfpld** [comment]
Delete the build dir when you change options to make sure LEGACY is enabled.

**Comment by wolfpld** [comment]
(It's a CMake option now, not a parameter to pass to make.)

**Comment by VimalWill** [comment]
sure I will try that
