### ISSUE TITLE
Tracy-Release unix build Fails with capstone API reference Linker failure

### ISSUE THREAD

**Issue by dineshqmu** [wolfpld/tracy#769]
I am newbie for the tracy software!!!

I am building the tracy server for the linux environment (ubuntu 20.04).
I installed all the dependency as per the tracy profiler user manual (pkg-config, glfw, freetype, capstone, dbus, libxkbcommon, wayland, libglvnd)

However, when i build for x11 with LEGACY=1, I got hit with  error while linker reference to capstone API "cs_regs_access".

I am lost and not sure which part i am missing. either version conflict of capstone. 

Any help is much appreciated.
![Capture](https://github.com/wolfpld/tracy/assets/164481584/c79c6282-d991-40c2-a261-36769d488721)

Thanks a lot 👍

**Comment by wolfpld** [comment]
Try master.

**Comment by dineshqmu** [comment]
In the tracy/profiler path, "build" folder was missing in the master branch.

**Comment by dineshqmu** [comment]
The issue was due to the multiple instances of the capstone installed and conflicts during compilation.

I had removed the apt-get installation of capstone and installed only manually compiled capstone and referred the path in environment variable.

This got resolved and worked for me.

Thanks a lot.
