### ISSUE TITLE
Manual out of date for building on Windows

### ISSUE THREAD

**Issue by St3veSmith** [wolfpld/tracy#778]
Attempting to update to latest 0.10, and I'm unable to build the profiler client on windows. vcpkg\install_vcpkg_dependencies.bat no longer exists in the repo, and there's no obvious replacement. Previously generated .sln and vcxproj files are no longer valid.

Downloading the packaged release 0.10 does not work, either, since the protocol has been updated in the repo since then and connection fails.

Ideally manual would be updated with latest instructions for building the profiler client locally on windows systems using visual studio. If that's no longer supported, then alternative build options should be documented.

**Comment by wolfpld** [comment]
As a workaround, you can click the green checkmark next to the commit description, then view the details of a build you are interested in (such as "build / build (windows-latest)"), then select Summary on the left, and the build artifacts can be downloaded at the bottom of the page.

**Comment by wolfpld** [comment]
TBH, I'm not sure what you are asking for here. The manual has been updated with CMake build instructions more than a month ago, in 3d70a6143. Is there something that's not clear to you? Maybe you were reading an old version of the manual? You can always get the latest one from the build artifacts, just like the executables.

**Comment by St3veSmith** [comment]
I might have been using an out of date manual. Apologies for the noise here. Definitely close this out. 

FWIW,Tracy is absolutely phenomenal and I've used it for years in multiple organizations (and personal use). Really can't say enough good things about it.
