### ISSUE TITLE
Feature request: GPU Semaphore/Fence events

### ISSUE THREAD

**Issue by Pursche** [wolfpld/tracy#78]
Hi, I was debugging a weird and somewhat rare ”hickup” in my Tracy profiled Vulkan renderer which I ultimately tracked down to a mistake in handling one of my VkSemaphores.

During the process of debugging this I could not help but think how useful it would be to have GPU semaphore and fence events (signal and wait) marked on the Tracy timeline, perhaps even with some kind of visual hint linking together waits and signals on the same semaphore.

For VkFence it might even be possible to link the GPU timeline event with the CPU timeline event.

I have no idea if this is even possible, but I floated the idea in Discord and was asked to make an issue for this feature request.

**Comment by wolfpld** [comment]
Fences can be only queried for whether they were signalled already, or not. There is no timestamp to retrieve. Semaphores are used for synchronization on GPU (not on CPU). You may be better served with a GPU-specific profiler like NVIDIA Nsight.
