### ISSUE TITLE
TRACY_ON_DEMAND consumes memory infinitely

### ISSUE THREAD

**Issue by FedyuninV** [wolfpld/tracy#789]
Hi, @wolfpld!

I'm developing an app which:
1. stays online for a long time (kind of a service)
2. when needed, can be profiled with Tracy on the fly

`TRACY_ON_DEMAND` was a lifesaver for me but when process lives for a long time the `tracy::Profiler::m_deferredQueue` grows infinitely and consumes too much memory. Do you have any ideas how to limit this queue? E.g. some smart clean-up which removes the oldest events and guarantees that remaining ones won't cause `Discontinuous frame begin/end mismatch.`.

Right now it's a private field without any mechanism to get access to it or clean it up via Tracy.

P.S. Thanks for the cool tool!

**Comment by wolfpld** [comment]
The deferred queue should, by design, hold a small number of items needed to properly set up the initial state of things created in the past that newly arriving messages can reference. What kind of things do you see being put there in excess? You can check this by breaking in `tracy::Profiler::DeferIteem()`.

**Comment by kekangshu99** [comment]
Maybe you can try to start Tracy manually using TRACY_MANUAL_LIFETIME, then shut down Tracy and relaunch it after a while?

**Comment by FedyuninV** [comment]
These 4 commits together allow us to not use `DeferItem` and avoid this infinite growth
- ad39a01de1376e0f7d8a5bd82dd0af94ee4fd5e7
- 216a4b7663db330c76210b2dccff6788a5d951c3
- afe5c8dfbed060ff0bfe584af028175df6fc4a03
- d3da7dcecdd631ee9cfa05d175ef96cd9f92e377
