### ISSUE TITLE
Reading file throw std::bad alloc

### ISSUE THREAD

**Issue by Yellow-King21** [wolfpld/tracy#803]
Hello,

I have encountered a problem when saving a file from Trace and then attempting to view it afterward. The issue occurs in `TracyUserData.cpp` at line 45. Upon debugging, I discovered that the statement `const auto sz = ftell(f);` sets `sz` to `9223372036854775807`. The file I tried to open is `287.8 MB`, but I also tried with a file that is only `49.8 kB`. I save the file from the profiler (GUI).

For your reference, I am using:

- Operating System: Ubuntu 22.04.4 LTS
- Kernel: Linux 6.5.0-28-generic
- Architecture: x86-64
- Window Manager: X
- Tracy version: 0.10.0

Best regards,
Marek

**Comment by wolfpld** [comment]
The value returned by ftell is `INT64_MAX`, which is in the valid range. An error would be indicated by `-1`, which is not the case here. Can you provide more information about the file, such as the on-disk size, or the filesystem you are using? Note that the problem is not with the trace you have saved, but with an auxiliary data file that has its path constructed in `OpenFile()`.

**Comment by Yellow-King21** [comment]
Thank you for your response. 
I looked into it and found that Tracy opens a directory (so the value is valid but doesn't make sense) and opens `<home_path>/.config/tracy/user/`, but the correct path should be `<home_path>/Documents/big_trace.tracy`. I followed your suggestion, and the filesystem is `/dev/mapper/vgubuntu-root ext4`, and the on-disk size is `275M big_trace.tracy`. Could you provide some more information how could I trace this bug and also how do I compile debug version with gdb symbols because I tried `cmake -DLEGACY=ON -DCMAKE_C_FLAGS="-O0 -g3 -ggdb" -DCMAKE_CXX_FLAGS="-O0 -g3 -ggdb" ..` but there is always optimized values. Thank you.

**Comment by wolfpld** [comment]
`-DCMAKE_BUILD_TYPE=Debug`

**Comment by Yellow-King21** [comment]
I recompile it and in DEBUG version it stop working at assert `TracyStorage.cpp:120 GetSavePath`, I look at the pointer but is empty. At RELEASE version it give me `<home_path>/.config/tracy/user/` as I mentioned early.  I also found that PATH is correct when function at main.cpp:885.

**Comment by wolfpld** [comment]
207e065f should fix this for you.

**Comment by Yellow-King21** [comment]
I have a question: I tried to use Tracy with sudo, but there is no sampling data. Is this the same issue as described in [issue #442](https://github.com/wolfpld/tracy/issues/442)?

Thank you for your answer

![image](https://github.com/wolfpld/tracy/assets/34798184/c3d6f649-2a53-4865-b501-1d9ca9a7b9dc)
