### ISSUE TITLE
Searchin' Tracy Profiler compatible with current Client source

### ISSUE THREAD

**Issue by FK-68** [wolfpld/tracy#816]
The current source (client) do not match the current App (server)

Operating system: Windows 10, 64 bit
Compiler: Visual Studio 2022
Language: C++20

See screen shot:
![grafik](https://github.com/wolfpld/tracy/assets/173287621/d3a8448f-0399-4850-b120-deaa58600c23)

And I also don't found a solution to built the Server GUI application.

In fact, I don't even know if the sources contain the code for the server side.

Files I downloaded:
Server GUI-side (download 4505 KB 7Zip file)
![grafik](https://github.com/wolfpld/tracy/assets/173287621/af832546-14c1-4ffe-9467-3e70da45f7dd)

Source for Client (download 6076 KB WinZIP file)
![grafik](https://github.com/wolfpld/tracy/assets/173287621/13c4be3b-4f90-44c9-9a1e-4bf79e0f5b29)

**Comment by wolfpld** [comment]
Everything you are asking about is explained in the documentation.

**Comment by FK-68** [comment]
Compiled Tracy Profiler 0.10.0 from the sources:
I got still the message:
![grafik](https://github.com/wolfpld/tracy/assets/173287621/7dc9bacd-21df-46bf-97fe-d5370ef7cd62)

tracy-0.10.zip  is from 2023-10-16 11:59
Tracy-master.zip  is from 2024-06-12 14:54
