### ISSUE TITLE
Problems with profiler data loss on remote server

### ISSUE THREAD

**Issue by tneval** [wolfpld/tracy#845]
As a background, I have done extensive profiling of an application successfully with Tracy. This profiling has been performed with local setup.

Now, I switched to remote server which does not have GUI. So, I'm using X11 forwarding for outputting the profiler view. 

The problem is I'm getting occasional warnings that connection was lost and not all data could be retrieved:

![Screenshot from 2024-07-25 11-26-15](https://github.com/user-attachments/assets/2c11f332-543b-4277-93e0-1557962d379e)

Sometimes this warning does not show up, but some of the annotations show ??? indicating data loss:

![Screenshot from 2024-07-25 11-25-59](https://github.com/user-attachments/assets/e73959d1-b12e-4d71-9062-277037d92976)

Any ideas what could be causing this?

Thanks

**Comment by tneval** [comment]
Actually, nevermind. Somehow it started working properly.

**Comment by wolfpld** [comment]
I would recommend connecting to the remote client from a locally running profiler instead of using X11 forwarding.
