### ISSUE TITLE
Possibility of setting TRACY_SAMPLING_HZ through an environment variable?

### ISSUE THREAD

**Issue by FelixBrendel** [wolfpld/tracy#851]
Hello, thank you for the great project! 

I am trying to use tracy in an linux environment where the allowed sampling frequency seems to change. Since the tracy client had to be built as a library for this use case, for now I have to recompile tracy every time I want to change the TRACY_SAMPLING_HZ since it is only a compile time macro. looking through ﻿TracySysTrace.cpp it seems there would be nothing in the way for reading TRACY_SAMPLING_HZ as an environment variable, similar to the other flags like TRACY_NO_SAMPLING? Granted, they are only booleans. What would you think about this idea?

Felix

**Comment by wolfpld** [comment]
Added in fb18a81d.
