### ISSUE TITLE
Cannot launch Tracy profiler using VSCode on Ubuntu running under WSL (Windows)

### ISSUE THREAD

**Issue by phaedon** [wolfpld/tracy#852]
Hi,
I was able, very briefly yesterday, to configure/build/launch the profiler app, but then it stopped working with no apparent change to anything on my end.  I have of course tried the classic solutions -- restart my machine, clear the cmake caches and reconfigure / rebuild. 

The initial change I made to get it to run was to set the legacy flag:
`option(LEGACY "Instead of Wayland, use the legacy X11 backend on Linux" ON)
`

However, now when I try to run I get the following run-time error:
```
Error 65544: Wayland: Window position setting not supported
Error 65544: Wayland: Setting window icon not supported
xdg_surface@29: error 3: xdg_surface must not have a buffer at creation
Error 65544: Wayland: Focusing a window requires user interaction
```

If I enable Wayland by disabling the LEGACY flag (as per the default in the main branch of the repo), then I get a build-time error:
```
[build] Starting build
[proc] Executing command: /home/fjsinis/cmake-3.29.3-linux-x86_64/bin/cmake --build /home/fjsinis/github/tracy/profiler/build --config Debug --target all --
[build] [1/2   0% :: 0.003] Re-checking globbed directories...
[build] ninja: error: '/usr/share/wayland-protocols/staging/cursor-shape/cursor-shape-v1.xml', needed by 'wayland-cursor-shape-client-protocol.h', missing and no known rule to make it
[proc] The command: /home/fjsinis/cmake-3.29.3-linux-x86_64/bin/cmake --build /home/fjsinis/github/tracy/profiler/build --config Debug --target all -- exited with code: 1
[driver] Build completed: 00:00:00.104
[build] Build finished with exit code 1
```

Other GUI applications (i.e. `google-chrome`) run just fine under my WSL setup, and these are a few of the relevant environment vars:
```
(base) fjsinis@fjsinis:~/github/tracy$ echo $WAYLAND_DISPLAY
wayland-0
(base) fjsinis@fjsinis:~/github/tracy$ echo $XDG_SESSION_TYPE

(base) fjsinis@fjsinis:~/github/tracy$ echo $DISPLAY
:0
```

Please advise! I got the client integration working, so this is my final step to be able to see the profiling in action.

**Comment by wolfpld** [comment]
Why don't you use Windows version of the profiler?

**Comment by phaedon** [comment]
> Why don't you use Windows version of the profiler?

If I run the profiler in Windows, will it detect client programs / processes running in Ubuntu (under WSL)?  If so that might be the best solution!

**Comment by wolfpld** [comment]
This depends on the network configuration. Broadcasts are limited to the subnet unless forwarding is configured. However, this is not necessary, you can just enter your WSL IP address (`ip a`) and the connection will be made.

**Comment by phaedon** [comment]
Oh, that's a much nicer solution, particularly since the Windows binary is prebuilt in the github releases. Worked without any issue, thank you!

**Comment by gedalia** [comment]
I hit the same issue trying to compile wayland from a 22.04 ubuntu box. I wound up copying in the files from a newer version of the library at https://launchpad.net/ubuntu/+source/wayland-protocols/1.36-1
unfortunately I hit:
tracy/profiler/src/BackendWayland.cpp:703:1: error: ‘const wl_surface_listener’ has no non-static data member named ‘preferred_buffer_scale’ which appears to be from wayland-scanner 1.21, suffice it to say, it's not as easy to cross compile .11 as it was .10

**Comment by wolfpld** [comment]
> ‘preferred_buffer_scale’ which appears to be from wayland-scanner 1.21, suffice it to say, it's not as easy to cross compile .11 as it was .10

No, it's not. This is obsolete wayland-protocols, because Ubuntu is broken by design.

See 8a6e525e, which just downloads what's needed from freedesktop's gitlab (now Debian will be happy, as they want builds that do not access the network).

**Comment by gedalia** [comment]
thanks, I appreciate it, still didn't quite work, I don't see an auto generated wayland-client-protocol.h in the tracy repo, it's coming from /usr/include and it's the old one.

**Comment by wolfpld** [comment]
Ah yes, that comes from the core wayland package.

**Comment by ansssardesa** [comment]
> Oh, that's a much nicer solution, particularly since the Windows binary is prebuilt in the github releases. Worked without any issue, thank you!

@phaedon  What changes did you do for this ? Do we need to change anything within WSL conf ? I have another application which is also publishing data over localhost:8086 and its server in windows is able to capture everything correctly.

But I am having issues for tracy-profiler. At first I thought my client was not integrated properly so I locally built the capture in WSL2 and it was perfectly able to capture the data. But I am facing a lot of issues building the profiler :( 

Could you please help me understand which interface ip shall be used ? @wolfpld I did try all the ips and nothing works :(

**Comment by codingjin** [comment]
> The file you want to update is `/usr/share/wayland/wayland.xml`.

How should I update `/usr/share/wayland/wayland.xml`?

**Comment by codingjin** [comment]
> thanks, I appreciate it, still didn't quite work, I don't see an auto generated wayland-client-protocol.h in the tracy repo, it's coming from /usr/include and it's the old one.

Hi, @gedalia did you figure out the issue? I am now getting stuck at the same problem.

**Comment by bd-gpasternak** [comment]
@codingjin I think I might have just commented out the lines that initialized structures that weren't in assistance. But kinda fuzzy now.
