### ISSUE TITLE
Programmatically specifying thread display order

### ISSUE THREAD

**Issue by fknorr** [wolfpld/tracy#854]
Thanks for this amazing project!

In our application, we're using multiple independent pools of fibers, each representing concurrent asynchronous operations. Whenever we're spawning a new fiber, it gets appended to the bottom of the list of threads, but we'd like to visually group threads / fibers by pool for easier visual parsing. Now I'm aware that it's possible to re-order threads by hand in "Options", but it quickly gets tedious when doing this manually on every profiler run.

Unfortunately we only know the number of pools upfront, not the max number of fibers / threads, so it's impractical to spawn them in the desired visual order. For us, it would be fantastic to have a client API in the shape of `TracySetThreadOrder(int)` that provides a sorting key for the insertion into the thread array displayed by the profiler.

**Comment by wolfpld** [comment]
Added on master.

**Comment by fknorr** [comment]
That was quick!

The new API works for proper threads now, but it doesn't appear to apply to fibers. I've tried:
```c++
TracyFiberEnter(fiber_name);
tracy::SetThreadNameWithHint(fiber_name, hint);
TracyFiberLeave;
```
But that seems to be ignored, the sorting behavior for those fibers remains as it would be for a thread with hint 0 (and that API doesn't look like it was intended to be used that way).

**Comment by wolfpld** [comment]
I have added support for fibers on master, but I don't have a way to check if this works as intended.

**Comment by fknorr** [comment]
Now works flawlessly. Thanks!
