### ISSUE TITLE
Tracy doesn't open on windows 11

### ISSUE THREAD

**Issue by utkusaglm** [wolfpld/tracy#862]
Hi, I downloaded the recent release and I cannot open the tracy-profiler. The window closes itself after I open it. The previous release v0.10.0 works fine.

**Comment by VladimirAndreevich** [comment]
I have the same problem on Windows 10

**Comment by nitrix** [comment]
I have the exact same problem and was trying to collect more information before opening an issue. Glad it's not just me.

Running the program in cmd.exe gives no information. In MinGW, it claims it's a segmentation fault.

GDB points out the problem but the symbols aren't there to relay what's what.

I was suspecting AVX2 (which my computer doesn't support) but looking at the sources, it seems I would've seen a MessageBoxA if that was the case.

I also tried compiling Tracy myself, but it complained about /MZ or whatever MSVC flags, even though I had CMake configured for Clang and Ninja, very weird.

**Comment by atlv24** [comment]
Same here, 0.11 segfaults on win 11

**Comment by utkusaglm** [comment]
@nitrix Yes, my mistake. It is v.10.0 not v0.9.1

**Comment by nitrix** [comment]
Seems solved for me on [0.11.1](https://github.com/wolfpld/tracy/releases/tag/v0.11.1) now :)

**Comment by wolfpld** [comment]
> Seems solved for me on W10 with [0.11.1](https://github.com/wolfpld/tracy/releases/tag/v0.11.1) now :)

Have you installed the up-to-date MSVC Redist package in the meantime? Or updated your installation of MSVC (at least to 17.10)?

**Comment by nitrix** [comment]
Looks like that's what it is. I installed CUDA and it installed MSVC redist packages.
![image](https://github.com/user-attachments/assets/42abf03a-b0de-4cb0-bfb4-70052532d35e)

**Comment by wolfpld** [comment]
Well then, this is "not a bug" and "by design", according to Microsoft.

https://developercommunity.visualstudio.com/t/Visual-Studio-17100-Update-leads-to-Pr/10669759?sort=newest
