### ISSUE TITLE
Discontinuous frames should work without string pooling

### ISSUE THREAD

**Issue by simonvanbernem** [wolfpld/tracy#87]
When I enable on-demand profiling in my application, about 20% of my attempts to connect to the client fail with this error:
![grafik](https://user-images.githubusercontent.com/10748498/89629947-e9f80780-d89e-11ea-87fd-43c6cdf01dfc.png)

The other 80% work fine. When on-demand profiling is disabled, connecting works fine 100% of the time, which leads me to believe this is not an instrumentation failure, but a bug in tracy bookkeeping. I can provide you the executable causing the problem if needed.

I am using up to two sets of non-continuous frames and the main frame set in my application.

**Comment by simonvanbernem** [comment]
Ok, I just saw that the manual says that discontinuous frames may not work correctly if the profiled programm doesn't have string pooling enabled. Indeed, removing the discontinuous frames fixes the issue. Unfortunately, my compiler doesn't even support that option, so it seems like I simply can't use discontinuous frames until this is fixed.

**Comment by wolfpld** [comment]
I think the following workaround should work:

![obraz](https://user-images.githubusercontent.com/600573/94066387-b8a2af00-fdec-11ea-9e49-95c6b8e25953.png)

I wouldn't expect to have it properly handled server-side any time soon.
