### ISSUE TITLE
Problem compiling Tracy 0.11.1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by Tonaion02** [wolfpld/tracy#874]
I had a problem compiling Tracy in version 0.11.1 on Ubuntu 22.04.
I got this error:
![WhatsApp Image 2024-09-03 at 16 05 26](https://github.com/user-attachments/assets/c72020ef-5f05-459d-8cc7-10d0972cc644)

**Comment by fregate** [comment]
@Tonaion02 I've encountered this error too. How you managed it?

**Comment by fregate** [comment]
I've compile with LEGACY=ON
Interesing, how to compile with wayland properly?

**Comment by Tonaion02** [comment]
> how to compile with wayland properly?

In my case wayland-protocols is too old, i think that the only via is to retrieve a newer version of wayland-protocols compiling yourself or to update OS.

**Comment by feishengfei** [comment]
wayland-protocols 1.25-1 on ubuntu 20.04, wayland-protocols 1.34-1 on ubuntu 22.04 is not higher enough for tracy.
refer to https://salsa.debian.org/xorg-team/wayland/wayland-protocols for a higher version.
