### ISSUE TITLE
The Statistics window can not show "Name" and "Location" informations

### ISSUE THREAD

**Issue by shafeng** [wolfpld/tracy#878]
I was using Linux Centos7 and Tracy0.8.0. After I finished the integration and ran both my client and Tracy server. I couldn't see any information about Statistics.
The Name and Location are shown as question marks:

![image](https://github.com/user-attachments/assets/3d9b9689-d6fd-42e9-bd13-b94e33b2b704)

**Comment by wolfpld** [comment]
0.8 was released 2.5 years ago. Use a current release.

**Comment by shafeng** [comment]
> 0.8 was released 2.5 years ago. Use a current release.

Thanks, I`m using this version because I couldn`t open the server-side profiler exe in 0.11 at Win11

**Comment by shafeng** [comment]
> > 0.8 was released 2.5 years ago. Use a current release.
> 
> Thanks. I‘m using this version because I couldn’t open the server-side profiler exe in 0.11.1 at Win11. After double-clicking tracy-profiler.exe, the main window just opened for almost 2 seconds and disappeared.

after installing the latest version of vc_redist, this problem was solved.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by shafeng** [comment]
after installing the latest version of vc_redist, this problem was solved.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
