### ISSUE TITLE
Missing threads when using thread group hints in Tracy 0.11.1

### ISSUE THREAD

**Issue by timo-heinapurola-supercell** [wolfpld/tracy#883]
I have been testing the thread group hint support in Tracy 0.11.1 and have noticed that it seems to somehow affect which threads are reported in the profiler app.

**Steps:**
1. Register the main thread with Tracy (do not provide a thread group hint).
2. Create 4 threads and set their name + thread group hint to value of `2`.
3. Create another group of 8 threads with their thread group hints set to the value of `1`.
4. Launch the application and the Tracy profiler on macOS.
5. Capture using the Tracy profiler.

**Expected outcome:**
All the four threads with the group hint `2` should be visible in the Tracy profiler and they should be listed close to each other, as should the 8 threads with the hint `1`. The main thread should be listed at the top.

**Actual outcome:**
About 50% of the time at least one of the threads in the same group are missing in the app.

**Comment by wolfpld** [comment]
Please see if #879 fixes this for you.

**Comment by timo-heinapurola-supercell** [comment]
It looks like it indeed fixes the issue. Thanks!
