### ISSUE TITLE
Visual Studio 2017 v141 toolchain build error in TracySocket.cpp

### ISSUE THREAD

**Issue by jshofmann** [wolfpld/tracy#90]
At TracySocket.cpp line 574 the following build error is reported by the v141 compiler in Visual Studio 2017 due to Microsoft's unique definition of inet_ntop:

2>c:\...\tracysocket.cpp(571): error C2664: 'PCSTR inet_ntop(INT,PVOID,PSTR,size_t)': cannot convert argument 2 from 'const IN_ADDR *' to 'PVOID'
2>c:\...\tracysocket.cpp(571): note: Conversion loses qualifiers

The fix is trivial, I changed line 569 from "#if __MINGW32__" to "#if __MINGW32__ || defined _MSC_VER". Thanks for releasing Tracy, with that one fix the profiler is fully operational!

**Comment by wolfpld** [comment]
Which SDK are you targetting?

**Comment by jshofmann** [comment]
I'm not sure what you're asking - I'm profiling a game using a Vulkan driver, but the graphics driver I enable when running the game is irrelevant to this problem. Since we don't use git, per Section 2.1 of the user manual I copied TracyClient.cpp, TracyVulkan.hpp, TracyOpenGL.hpp, TracyD3D12.hpp, Tracy.hpp, TracyC.h, and their dependencies (the contents of the client, common, and libbacktrace directories) into our source tree and added TracyClient.cpp to our external dependencies Visual Studio project. The error is reported when TracyClient.cpp is compiled.

**Comment by wolfpld** [comment]
Yes, Windows SDK. I have checked on 10.0.{18362,17763,16299,14393}.0 and in each one the functions signature is valid, i.e.:

```c++
PCSTR
WSAAPI
inet_ntop(
    _In_                                INT             Family,
    _In_                                const VOID *    pAddr,
    _Out_writes_(StringBufSize)         PSTR            pStringBuf,
    _In_                                size_t          StringBufSize
    );
```

This is consistent with the documentation: https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_ntop

Is there a reason why you have 8.1 SDK set? It's out of mainstream support (but still in extended support, so I guess this should be handled by Tracy): https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

**Comment by wolfpld** [comment]
9455c927 should fix this.

**Comment by jshofmann** [comment]
Thanks. The reason the Windows SDK 8.1 is still used is due to legacy - this game was originally written back in 2010 - 2012.
