### ISSUE TITLE
Feature request: show last value of plot when entire plot is scrolled left outside the view.

### ISSUE THREAD

**Issue by mcourteaux** [wolfpld/tracy#907]
Right now, plots go back to ranging from 0 to 0, when there is no plotting data in the viewport. That's very uninformative, as there actually is data left of the viewport, which is still valid (such as memory usage). Simply not having sent any updates for a certain plot doesn't mean that the value is no longer accurate.

I guess the binary search returns the end-iterator, in which case we should use the last available value (if any) to determine the range.

**Comment by mcourteaux** [comment]
Thinking more about this, drawing one extra plot segment from last value to current time might be an even better visualization.

**Comment by wolfpld** [comment]
> Right now, plots go back to ranging from 0 to 0, when there is no plotting data in the viewport. That's very uninformative, as there actually is data left of the viewport, which is still valid (such as memory usage). Simply not having sent any updates for a certain plot doesn't mean that the value is no longer accurate.

Range is the visible range. You can view the total min and max values in plot tooltip.

> Thinking more about this, drawing one extra plot segment from last value to current time might be an even better visualization.

What about data before the first plot item? This is essentially a symmetrical problem, but you end up with invalid data. E.g., if you would have the first memory allocation to be 100 MB, extending the plot before the first item would imply that there was always 100 MB allocated (Tracy actually inserts 0 at 0 ns, but you get the point).

**Comment by mcourteaux** [comment]
I understand what you're saying, but my intuition is that on plots like these (especially with staircase) is that there is a sense of causality. Data is valid once it's produced, and not earlier. Inserting 0 at 0 makes total sense, and the causality of that holds in all reasonable cases I can think of.

**Comment by wolfpld** [comment]
1bd84419 should fix this.

**Comment by mcourteaux** [comment]
Amazing, thanks a lot! Works nicely!
