### ISSUE TITLE
class/namespace not showing in zone name

### ISSUE THREAD

**Issue by toodemhard** [wolfpld/tracy#910]
Zone scopes used to show up as "class::function" but now it only shows up as "function" since I haven't profiled in a while and upgraded to v0.11.1

I tried to setup a minimal program to reproduce the old behavior with v0.11.1 and v0.9 but still couldn't get it to work. I also disabled "zone name shortening" in the options but it didn't change anything. Is there something I'm missing to get the class/namespace to show up in the zone name again?

![image](https://github.com/user-attachments/assets/9e82325a-3cb6-40cd-b0a8-a0c602117410)
![image](https://github.com/user-attachments/assets/2e04f9ed-79d7-4521-bd06-34608a83935d)

**Comment by wolfpld** [comment]
The behavior difference you see is caused by how different compilers expand `__FUNCTION__` macro.

**Comment by toodemhard** [comment]
Oh yeah ```__FUNCTION__``` just expands to function name on Clang and MSVC for me, not sure if it was always like that. I sort of managed to get the old behavior by replacing ```__FUNCTION__``` with ```__PRETTY_FUNCTION__``` for Clang.
```
#define __FUNCTION__ __PRETTY_FUNCTION__
```
Thanks for the help.
