### ISSUE TITLE
TracyProfiler.cpp timer should use mach_absolute_time on Apple

### ISSUE THREAD

**Issue by alecazam** [wolfpld/tracy#922]
Right now macOS is not using the system timer.   rdtsc is not really worth using on Apple Silicon.  So for tvos, visionOS, iOS, and macOS (Apple Silicon).  And this isn't that slow that rdtsc is worth the artifacts.   The following code should just be using mach_absolute_time() on all APPLE platforms. 

The docs state a low-cost timer is used on x64 and arm64, and there do seem to be instructions for that.  But GetTime() isn't using that from what I see.
  
```

#if ( (defined _WIN32 && !(defined _M_ARM64 || defined _M_ARM)) || ( defined __i386 || defined _M_IX86 || defined __x86_64__ || defined _M_X64 ) || ( defined __APPLE__ ) ) <- change
#  define TRACY_HW_TIMER
#endif

#ifdef TRACY_HW_TIMER
#  if defined TARGET_OS_IOS && TARGET_OS_IOS == 1  <- change to #if defined __APPLE__
        if( HardwareSupportsInvariantTSC() ) return mach_absolute_time();
```

These timestamps have to be converted via the following code.  Took this from one of my open-source projects.  I don't see use of mach_timebase calls in Tracy.  So not sure how the timings above are converted.

```

#ifdef TRACY_HW_TIMER
#  if defined __APPLE__ // was defined TARGET_OS_IOS && TARGET_OS_IOS == 1
        if( HardwareSupportsInvariantTSC() )
        {
            auto queryTimerPeriod = [] {
                mach_timebase_info_data_t timebase;
                mach_timebase_info(&timebase);
                
                // This is 1/1 on macOS Intel, 125/3 on iOS/M1, or 1/1 on M2+/A16
                // turns timer into nanos.
                double timerPeriod = (double)timebase.numer / timebase.denom;
                return timerPeriod;
            };
            static double timerPeriod = queryTimerPeriod();
            return int64_t((double)mach_absolute_time() * timerPeriod);
        }

```

**Comment by slomp** [comment]
> `rdtsc` is not really worth using on Apple Silicon.

`rdtsc` is an x64 instruction, so I don't see the connection with Apple Silicon.

**Comment by wolfpld** [comment]
Yeah. @alecazam if you want me to consider the changes you propose, send them as proper PRs, not some kind of do-it-at-home puzzles for me to decipher. Furthermore, the timebase thing you want to be doing is completely unneccessary.
