### ISSUE TITLE
Absolute timestamps

### ISSUE THREAD

**Issue by eibach** [wolfpld/tracy#929]
Is it possible to toggle the view to absolute timestamps? I only see timestamps relative to the start of the session. For correlating sessions from different processes and additional sources like wireshark it would be really helpful to have the absolute time value.

**Comment by wolfpld** [comment]
No. Technically it's doable, as traces have timestamps, but these are seconds precision only.

**Comment by eibach** [comment]
Thanks, I see. Would it be possible to record the origin timestamp, so
absolute timestamps can be derived?

Bartosz Taudul ***@***.***> schrieb am Sa., 23. Nov. 2024,
00:58:

**Comment by eibach** [comment]
Ok, I found the origin timestamp is what you were talking about. I have submitted a pull request to imüplemnt this in the zon info view.
