### ISSUE TITLE
Feature Request - Get Tracy Worker Thread Id's'

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [wolfpld/tracy#933]
I happen to be in a scenario where I hook my own malloc/frees to track memory and also issue TracyAlloc and TracyFree, and every dll and exe in my application calling malloc will go through this including Tracy Symbol Worker thread and other threads.
I would like it If I had access to thread id of tracy's worker threads so I can ignore tracing allocs free for it.
That's basically it. I'm developing on windows and visual studio.

**Comment by Erfan-Ahmadi** [comment]
Ok now that I think about it, it is already possible because unlike other libraries we include all .cpp and inner workings of the api in TracyClient.cpp
so the static variable `s_symbolThreadId` is inside the translation unit I have access to

**Comment by wolfpld** [comment]
Tracy generally should not call `malloc` anywhere, unless unavoidable due to the way some system library behaves. This shouldn't be the case on Windows.
