### ISSUE TITLE
Unsuported protocol when trying to download PPQSort

### ISSUE THREAD

**Issue by SerlemGit** [wolfpld/tracy#934]
Hello ! 

While trying to build for Raspberry pi 4 ( debian / buster ) i was blocked by this error : 

```
CMake Error at PPQSort/cmake/CPM.cmake:19 (file):
  file DOWNLOAD cannot compute hash on failed download

    status: [1;"Unsupported protocol"]
Call Stack (most recent call first):
  PPQSort/CMakeLists.txt:25 (include)
```

i have check all 7 pages of issues and did not find anything relevant. I am still quite new to CMake so i would love some assistante in fixing this issue.

Thank you in advance !

**Comment by SerlemGit** [comment]
Curl -V return : 

`curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06, security patched: 7.64.0-4+deb10u9
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
`

**Comment by wolfpld** [comment]
The most relevant issue seems to be this: https://gitlab.kitware.com/cmake/cmake/-/issues/16208

**Comment by SerlemGit** [comment]
Thank you very much ! I understand where the problem come from now and will try and find a way to fix it. Thanks a lot for taking the time to help me when the issue was not related to your repo !
