### ISSUE TITLE
Client and server can not coexist in same program

### ISSUE THREAD

**Issue by rokups** [wolfpld/tracy#97]
Updating to v0.7 i noticed that both `client/TracyCallstack.hpp` and `server/TracyEvent` have `SymbolData` struct. It no longer is possible to embed tracy in my game editor application since it both views profiling data and executes profiled code.

**Comment by wolfpld** [comment]
Should be fixed in 960c7fb1.

**Comment by rokups** [comment]
Well that was fast, thank you :pray:
