### ISSUE TITLE
Disabling use of capstone

### ISSUE THREAD

**Issue by rokups** [wolfpld/tracy#98]
It is a pretty sizeable dependency that is not bundled with source code of tracy, a way to opt out of it would be useful.

**Comment by rokups** [comment]
Instead of fighting i added capstone to my engine's dependencies ¯\_(ツ)_/¯

**Comment by CBtiger** [comment]
Not sure its worth to open a new issue as its just a question.

As a tracy beginner currently fighting with capstone dependency in Linux am curious to know what functionality in the profiler is tied to capstone and whether it could be described in a few words?

I saw that its included in two *.cpp files only. But that does not necessarily mean its not a central cornerstone of the profiler function. The posts above, however, suggest it isn't, which raised my curiosity.

If there would be a limited function set tied to it that does not seem crucial to me I might try to ifndef'ed it out and see how it works. It would sure make life in offline use cases a lot easier.

**Comment by wolfpld** [comment]
Capstone is used to disassemble binary code, as you can see on the last screenshot in the readme. It's also used to walk through function calls to get code that wouldn't otherwise be known.

For offline use cases see the CPM documentation on setting up a cache.
